### ISSUE TITLE
Internet Connection Status in the prompt?

### ISSUE THREAD

**Issue by dloureiro** [nojhan/liquidprompt#101]
Hi,

I was wondering if it could be interesting to be able to know if the internet connection is up or down?
A first approach could, for example, be to ping google and check the result status of the ping command.
I created a branch in my liquidprompt fork to test this (dloureiro/liquidprompt@da34fd2c04d01480e568089fef90f550907a4d23). Tell me if you want me to propose a PR concerning this feature.

**Comment by Rycieos** [comment]
This has to be rejected. The prompt needs to be fast, and this could never be.

If there were some way to do this async, then maybe we could make this work, but async in the shell is difficult, and how would you know someone was going to hit return ahead of time, or else you would need to go back and edit the prompt after.
