### ISSUE TITLE
Cygwin performance

### ISSUE THREAD

**Issue by madmanu** [nojhan/liquidprompt#130]
I am using liquidprompt on Win7/Cygwin/bash, without any modification in theme or config. It works and looks great, but its performance are somewhat sluggish.

My completely unscientific tests are "just press enter and look at my stopwatch for when I the prompt is displayed again". Without any source repository, I have:
- ~0.8s response time on local hard disk
- ~1.3s on a network share
- ~45s on a local hard disk at the root of a medium-sized SVN checkout (`find ~/svn/trunk | wc -l` ==> 87758)

I'd like to improve it, but I don't know where to start, and how to measure what part(s) of the code take most of the time.

**Comment by dolmen** [comment]
Recent feedback about behavior on Cygwin is welcome!

**Comment by davidknaack** [comment]
I'm running liquidprompt under Cygwin64 on Win8.1. If I have LP_ENABLE_JOBS enabled it takes about 1.6s for the prompt to come up (press enter on a blank prompt, 1.6 seconds later I have a prompt again). With LP_ENABLE_JOBS disabled that goes down to about 0.6s.

In a git directory (with LP_ENABLE_JOBS off) it takes about 1.5s. If I take out the 'git stash list' I get back about 0.6s, which leaves me at about 1 second to render the prompt. Annoying, but usable.

The delays seem to be in the time it takes to start programs. For example, if I start git with 'git stash err' to force a syntax error, on linux the help text is printed immediately. Under Cygwin there is a several hundred millisecond delay before the help text is printed.

Similarly, 'tmux list-sessions' and 'jobs' are both slow to return relative to their speeds on linux.

**Comment by dolmen** [comment]
@davidknaack Thanks! Very useful!

**Comment by madmanu** [comment]
Hi,
Sorry for the loooong delay... During that time the SVN grew a bit (now 88103 files and folder), response time after pressing 'return' is much better : around 25 seconds. Congratulations!

I tested with branch 'develop', as of today (again, with all defaults).

**Comment by dolmen** [comment]
@madmanu You may also have upgraded SVN since 2 years ago...

**Comment by antonpiatek** [comment]
I also find cygwin to perform much slower with liquidprompt than a native linux shell. Disabling LP_ENABLE_JOBS does help, but even in a small git repo (the liquidprompt one) it takes noticeable time to return the prompt. Forking seems to take a long time, which does make it quite annoying

**Comment by dolmen** [comment]
cygwin is slow, by design. I have no hope of making Liquid Prompt usable on that platform. It is much more efficient to use Liquid Prompt inside a full Linux virtual machine under Windows.

**Comment by Rycieos** [comment]
I am having issues with this too. A work around is to gut the config on Cygwin systems to load almost no features, but the startup is still extremely slow. Normal startup takes 10.7 seconds, hitting enter for new prompt takes 1.5 seconds.

I did some profiling, here are my results. First computer is Windows 7, latest Cygwin. Nix system is CentOS 7. Both on latest liquidprompt.
* `wc -l` takes at least 0.12s to run, even when doing nothing. This adds up fast. On my nix system it takes 0.003s max. Alternative is `sed -n '$='`, but it takes just as long.
* `_lp_load_color` has all of it's time in the `read lp_cpu_load eol < /proc/loadavg` line. This suggests disk reading problems... bad Cygwin compatibility layer?
* `git rev-parse --is-inside-work-tree` takes 0.19s when not in a repo, on nix it takes 0.002s.
* `git stash` takes 1.5s to run, when not in a repo. On nix it takes 0.02s.
* `_lp_git_head_status` takes 0.28s to run when in a repo. On nix (in the exact same repo) it takes 0.004s.
* `git status` takes 8.5s to run in a repo! On nix it takes 0.12s.
* `_lp_git_branch_color` takes 6.12s in a repo! On nix it takes 0.091s.
* Total: `_lp_set_prompt` takes 1.633s, On nix takes 0.036s. (No git repo).

This looks like it points toward disk reading issues. Unfortunately the two computers don't have identical disks, so I can't remove that variable.

**Comment by Rycieos** [comment]
Completely gutting the config (disabling everything) brings the startup time down to 9.5s and the new prompt time down to 0.95s. While better, it's obviously still a problem.

**Comment by Jitsusama** [comment]
I'm also noticing really slow prompt displays on Cygwin using Bash in the mintty terminal program. Same experience as others; disabling `LP_ENABLE_JOBS` speeds up the normal prompt, but when in a git project directory, the prompt display is unbearably slow. Wish I didn't have to use Windows at work :P

**Comment by lqueryvg** [comment]
Win7/Cygwin64/zsh

With everything disabled, it takes about 2s for each prompt.

This is me running subsequent date commands.

```
[:~] 130 % set | grep ^LP_ENABLE

LP_ENABLE_BATT=0
LP_ENABLE_BZR=0
LP_ENABLE_FOSSIL=0
LP_ENABLE_FQDN=0
LP_ENABLE_GIT=0
LP_ENABLE_HG=0
LP_ENABLE_JOBS=0
LP_ENABLE_LOAD=0
LP_ENABLE_PERM=0
LP_ENABLE_PROXY=0
LP_ENABLE_RUNTIME=0
LP_ENABLE_SCLS=0
LP_ENABLE_SCREEN_TITLE=0
LP_ENABLE_SHORTEN_PATH=0
LP_ENABLE_SSH_COLORS=0
LP_ENABLE_SUDO=0
LP_ENABLE_SVN=0
LP_ENABLE_TEMP=0
LP_ENABLE_TIME=0
LP_ENABLE_TITLE=0
LP_ENABLE_VCSH=0
LP_ENABLE_VCS_ROOT=0
LP_ENABLE_VIRTUALENV=0
[:~] % date
Fri, Dec 01, 2017 10:09:28 PM
date
[:~] % date

Fri, Dec 01, 2017 10:09:30 PM
date
[:~] % date
eFri, Dec 01, 2017 10:09:31 PM

date
[:~] % date
Fri, Dec 01, 2017 10:09:33 PM
[:~] % date
Fri, Dec 01, 2017 10:09:34 PM
[:~] % date
Fri, Dec 01, 2017 10:09:36 PM
[:~] %
```

Sadly, not usable.
