### ISSUE TITLE
Wifi Signal Strength

### ISSUE THREAD

**Issue by jab416171** [nojhan/liquidprompt#139]
It might be useful to add in the current signal strength of the wifi network. You can get it with this command: `awk 'NR==3 {print $3}''' /proc/net/wireless | cut -d "." -f 1`

**Comment by jbaum98** [comment]
⌔ Unicode number: U+2314

**Comment by soyuka** [comment]
📶

**Comment by nojhan** [comment]
I would be interested (being often connected on text interfaces).
I would suggest displaying an icon if the best signal strength (across interfaces) goes under a threshold, and making it disappear if everything is fine.
Unicode's "antenna with bars" should be a good candidate, too: 📶

**Comment by Rycieos** [comment]
I like that, then it is treated just like battery, temperature, or load in that it only shows up when it is in a "bad" state. I can follow the same model for that too, with a config option for the threshold, and using LP_PERCENTS_ALWAYS as well.

**Comment by nojhan** [comment]
Yes, to me that’s what makes sense in the prompt (as you pointed out, the
permanent state can be displayed in the desktop manager anyway).

**Comment by augmentedfourth** [comment]
If possible, I'd also like for this not to show up if there's a wired network with routing priority. My laptop is always connected to Wi-Fi at home, but when I'm at my desk I'm also hooked into a hub with a wired connection (and the wired connection has priority in my network settings), so at that point I don't really care about wireless signal strength.

**Comment by Rycieos** [comment]
> If possible, I'd also like for this not to show up if there's a wired network with routing priority

Any ideas for how to detect this? Ideally reading data from a file (like the `/proc/net/wireless` example given above) and not from a command, since a file is much faster.

**Comment by Rycieos** [comment]
I just pushed up commit e0c2062c5b111aca5173c8dd9a042b38e2d1a57c on the `develop` branch to implement this. It has backends for both Linux and MacOS, and full test cases for both as well.

Anyone who cares can give it a test.

**Comment by Rycieos** [comment]
I pushed an amended commit b727e02ece9f4c4fbe6d46ecff5977cf1f45fb2f that includes updates to the `external-tool-tester.sh` to get the new info. If anyone finds a bug with this, please include output from that script for debugging.

@augmentedfourth I do not see a way to do your request. I would need a command that could give the answer to the question "is their any IPv4 or IPv6 address that would route to a wireless interface instead of a wired one?" And that doesn't even take into account that there can be multiple wireless interfaces. Not to mention that is a command, which would take a lot longer to run than the simple file read I am doing now. And that is all for Linux, I doubt it is possible to get that information on MacOS.

If you have ideas, I'm all ears.

**Comment by augmentedfourth** [comment]
I'd test it, but `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.` I don't know where to find the fork/commit to pull into a local clone.

**Comment by Rycieos** [comment]
Ah my mistake. I amended again, it's commit 64434357d86672a15e39a1e285b79d29a6855940 now, on the develop branch.

**Comment by augmentedfourth** [comment]
Aha. I found it. It's `64434357` in the repo. Looks good, but I never think about wireless signal in terms of dB or dBm (just the rudimentary concept of "bars"), so I don't think I'll enable this.

**Comment by Rycieos** [comment]
I am not planning on enabling this either. And I agree, dB is not a very intuitive way to think about the signal strength. Maybe I can track down some code that translates dB to "bars", but I doubt there is a standard way to do that...

**Comment by Rycieos** [comment]
I finally found how NetworkManager converts from raw dBm to "strength" (percentage):
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/3a69aa50b8780fa65e6026877c102befeb408ef3/src/core/nm-core-utils.c#L4813-4830
```c
guint8 nm_wifi_utils_level_to_quality(int val)
{
    if (val < 0) {
        /* Assume dBm already; rough conversion: best = -40, worst = -100 */
        val = abs(CLAMP(val, -100, -40) + 40); /* normalize to 0 */
        val = 100 - (int) ((100.0 * (double) val) / 60.0);
    } else if (val > 110 && val < 256) {
        /* assume old-style WEXT 8-bit unsigned signal level */
        val -= 256;                            /* subtract 256 to convert to dBm */
        val = abs(CLAMP(val, -100, -40) + 40); /* normalize to 0 */
        val = 100 - (int) ((100.0 * (double) val) / 60.0);
    } else {
        /* Assume signal is a "quality" percentage */
    }

    return CLAMP(val, 0, 100);
}
```

And then how it converts from strength to "bars":
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/3a69aa50b8780fa65e6026877c102befeb408ef3/src/libnm-core-impl/nm-utils.c#L3559-3572
```c
const char * nm_utils_wifi_strength_bars(guint8 strength)
{
    if (strength > 80)
        return "****";
    else if (strength > 55)
        return "*** ";
    else if (strength > 30)
        return "**  ";
    else if (strength > 5)
        return "*   ";
    else
        return "    ";
}
```

And this is how Gnome wigets does that:
https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/079bf51086c32da859aacdcbe778bdfe39ebb565/panels/network/cc-wifi-connection-row.c#L291-300
```c
      if (strength < 20)
        icon_name = "network-wireless-signal-none-symbolic";
      else if (strength < 40)
        icon_name = "network-wireless-signal-weak-symbolic";
      else if (strength < 50)
        icon_name = "network-wireless-signal-ok-symbolic";
      else if (strength < 80)
        icon_name = "network-wireless-signal-good-symbolic";
      else
        icon_name = "network-wireless-signal-excellent-symbolic";
```

The trick is that there are not Unicode symbols that would work for filling up a WiFi symbol. So I think I'll just stick with the classic. My new commit is 7a16f82. I've converted everything to a "quality", which ranges from 0 (bad) to 100. Then it uses the normal LP_COLORMAP and LP_PERCENTS_ALWAYS to display everything just like battery.

**Comment by augmentedfourth** [comment]
I like the algorithm. However, I'm *right next to* my home WAP and have "full bars," but it still reports under the threshold. Also, the wide Unicode symbol kind of smashes into the numerals.
![Screen Shot 2022-05-12 at 11 55 18 AM](https://user-images.githubusercontent.com/538363/168148387-081c16b3-4fea-4161-ad5c-4d98ef84263f.png)

**Comment by Rycieos** [comment]
> the wide Unicode symbol kind of smashes into the numerals.

Modern terminals are supposed to handle double wide characters correctly, I'm not sure why that is happening. You could always add a space to the MARK after the 📶 character to prevent that.

`67` is above the default threshold of `40`, so either you changed the threshold, or you found a bug. But I can't reproduce that, and all the tests are passing...

**Comment by augmentedfourth** [comment]
I did change the threshold so I could force it to show. My comments were on the display, not the functionality.

**Comment by augmentedfourth** [comment]
and I'm using macOS iTerm2, which I would expect to be better at display than that. The problem may lie in the terminal rather than `liquidprompt`, of course.

**Comment by Rycieos** [comment]
Oh, you mean the symbol? That is what I meant in my comment, that the symbol is static, it doesn't change with the quality percentage.

I'd be open to making the symbol by dynamic if someone can come up with some good symbols for it, but I wasn't able to find any.

> I'm using macOS iTerm2

Me too, and mine doesn't look like that:
<img width="513" alt="Screen Shot 2022-05-12 at 3 22 02 PM" src="https://user-images.githubusercontent.com/8375571/168152721-8e1ea638-d20a-49a4-942b-b1a016d8e4b7.png">

**Comment by augmentedfourth** [comment]
Might be my font, then. I'm pretty obsessive about [Inconsolata](https://fonts.google.com/specimen/Inconsolata).
