### ISSUE TITLE
Directory Styling

### ISSUE THREAD

**Issue by dimitrieh** [nojhan/liquidprompt#149]
Hey I saw in the description the following, however I think this can be extended for better use.

> The current directory in bold, shortened if it takes too much space, while preserving the first two directories;

I described it in the following issue: https://github.com/holman/dotfiles/issues/71

if this is possible i would like to see how very much:)

**Comment by Rycieos** [comment]
This was implemented as part of [v2.0.0-rc.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-rc.1).

By default, the VCS repo root is highlighted and never shortened, no matter which path shortening method is selected (can be disabled with [`LP_PATH_VCS_ROOT`](https://liquidprompt.readthedocs.io/en/latest/config.html#LP_PATH_VCS_ROOT)).

The last directory is the same (highlighted, never shortened).

Both of the formattings can be configured: [`LP_COLOR_PATH_VCS_ROOT`](https://liquidprompt.readthedocs.io/en/v2.0.0-rc.1/config.html#LP_COLOR_PATH_VCS_ROOT) and [`LP_COLOR_PATH_LAST_DIR`](https://liquidprompt.readthedocs.io/en/v2.0.0-rc.1/config.html#LP_COLOR_PATH_LAST_DIR), and if special formatting is not wanted on the last dir, it could be set to the empty string, which will default it to the color of the rest of the path.
