### ISSUE TITLE
Fossil support is slow

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#188]
PR #186 introduced some slow command to count the number of lines impacted by a fossil patch.

**Comment by Rycieos** [comment]
As part of the rework for v2.0, Fossil support got a rework as well. Those changes are now in [v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1).

If there still issues with performance, please open a new issue.
