### ISSUE TITLE
Display only current directory instead of Shorten Path 

### ISSUE THREAD

**Issue by Depado** [nojhan/liquidprompt#219]
I'm searching for a solution to get the same option as "\W" in my bashrc PS1 which is only printing the current working directory and none of the upper directories. That's the way I work, because it doesn't take too much space but the directory name is always complete (setting LP_PATH_LENGTH to  a lower value may cut the name of the current directory)

Is there a way I can do that using the .ps1 file or something like that ? =)

**Comment by Rycieos** [comment]
The behavior of `LP_PATH_KEEP=-1` is old by now, but the documentation has been lacking.

I have now improved the documentation in [v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1):
https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/config.html#LP_PATH_KEEP
