### ISSUE TITLE
Show Ruby version

### ISSUE THREAD

**Issue by simonweil** [nojhan/liquidprompt#249]
Something like this could work:

```
if [ -e ~/.rvm/bin/rvm-prompt ]; then
  RUBY_ENV=$(~/.rvm/bin/rvm-prompt i v g)
else
  if which rbenv &> /dev/null; then
    RUBY_ENV=$(rbenv version | sed -e 's/ (set.*$//' -e 's/^ruby-//')
  fi
fi
```

**Comment by milouse** [comment]
Due to long standing pull request, rebase was a failure. I rebuild the fixing branch from scratch. I consider this code as fully working as expected: I use it in production since 11/2014 without any problem.

**Comment by milouse** [comment]
Rebased and clean up a bit my branch. Warning, I've got a conflict while rebasing. Thus I urge you to better delete your local branch before pulling it again.

**Comment by axos88** [comment]
@milouse Still needs to be doumented in the README.md
