### ISSUE TITLE
Allow setting date and time format

### ISSUE THREAD

**Issue by tiziano88** [nojhan/liquidprompt#281]
Right now the prompt only display the system time, but both bash and zsh support printing formatted time:
bash: `\D{format}`
zsh: `%D{format}`
where `format` is passed to the `strftime` function.
It would be good to have a way to override the default behaviour in the config file, so that if a time format string is specified, liquidprompt would prefer that instead of the default system time.

**Comment by Rycieos** [comment]
I'm moving this to v2.1, since v2.0 is getting large and long already, and this mostly depends on #651, which really should wait until after v2.0.
