### ISSUE TITLE
Broken path inside Midnight Commander

### ISSUE THREAD

**Issue by clneagu** [nojhan/liquidprompt#288]
After running `mc` the path displayed is always `~`.
`prompt_off/on` seems to partially fix things.

The problem only appears if I source liquidprompt from bashrc.
If I source it manually after I start the terminal everything seems ok.

**Comment by dolmen** [comment]
@clneagu Could you check the behavior from MC with the `develop` branch?

**Comment by chthal** [comment]
I tested it and it seems to work well.
