### ISSUE TITLE
Shell blocked accessing directory with mercurial repository

### ISSUE THREAD

**Issue by rubenorta** [nojhan/liquidprompt#296]
My installation works perfectly with GIT repositories but when I try to access to a mercurial repository (2.8.2) the shell blocks and I've to kill it. My bash version is 
GNU bash, version 4.3.0(1)-release (x86_64-pc-linux-gnu). I've the last release of liquidprompt

![selection_019](https://cloud.githubusercontent.com/assets/588526/2602447/4ab0ad6a-bb1f-11e3-90f2-a17b9a35955d.png)

**Comment by Rycieos** [comment]
I'm closing this as this is a very old issue and I cannot reproduce this. Please update if this is still an issue on the latest version of Liquidprompt.
