### ISSUE TITLE
Zsh Vi mode(insert/command) indicator?

### ISSUE THREAD

**Issue by vojnovski** [nojhan/liquidprompt#297]
Afaics there is no indicator in the prompt that tells us whether we're in command or insert mode for those that use the vim bindings for zsh. 

Is something like this within the intended lines for for liquidprompt? (Being that it only pertains to zsh, and even more so, only to those using the vim and not the emacs bindings).

V.

**Comment by liujoey** [comment]
in zsh, prezto is a package as an alternative to oh-my-zsh, the default theme sorin uses three > as prompt indicators, when you switch to vi mode, the > will be changed to three <, which is the best implementation in my opinion.
