### ISSUE TITLE
tmux session on localhost is misinterpreted as telnet session

### ISSUE THREAD

**Issue by wimstefan** [nojhan/liquidprompt#304]
And therefore liquidprompt thinks it is a remote connection and shows the hostname in WARNING RED :)

This is the output from `who`:
```
swimmer  pts/12       2014-06-03 12:53 (tmux(15944).%0)
swimmer  pts/13       2014-06-03 12:53 (tmux(15944).%1)
swimmer  pts/14       2014-06-03 12:53 (tmux(15944).%2)
swimmer  pts/15       2014-06-03 12:53 (tmux(15944).%3)
swimmer  pts/16       2014-06-03 12:53 (tmux(15944).%4)
```

**Comment by flasheater** [comment]
I have a similiar issue. The host name is red inside Guake terminal. This is not the case in Terminal.

I confirmed by setting LP_COLOR_TELNET to some other color, that it is in fact the telnet color. 

This may be a Guake issue.

**Comment by dolmen** [comment]
@wimstefan @flasheater @XDex Please try branch `fix/connection-source-tmux` where I have committed 0d7d3fdcf1a892149c0ffbbc580248deefe0be70.

**Comment by dolmen** [comment]
I still need user feedback on the proposed fix...

**Comment by XDex** [comment]
Just pulled the changes from upstream fix/connection-source-tmux - that fixed the issue on my system..

**Comment by mathieumd** [comment]
The branch `fix/connection-source-tmux` fixes the issue on my system too (Tmux 2.0 into Konsole 15.08.0). Before/After:

```
[mathieu@hostname:/opt/liquidprompt] master ± git checkout fix/connection-source-tmux
Basculement sur la branche 'fix/connection-source-tmux'
Votre branche est à jour avec 'origin/fix/connection-source-tmux'.
[mathieu@hostname:/opt/liquidprompt] fix/connection-source-tmux ± . ~/.bashrc
[mathieu:/opt/liquidprompt] fix/connection-source-tmux ±
```

**Comment by Syllo** [comment]
The fix worked for me as well.
Using: 
Tmux 2.0 and who (GNU coreutils) 8.24 on Konsole 15.04

**Comment by hcgraf** [comment]
fixed for me with merge 2703ee03c83595e95fa60fb68ff6d77c042a7ca0

**Comment by dolmen** [comment]
@hcgraf @Syllo @mathieumd @XDex Thanks for your feedback!

**Comment by daverigby** [comment]
Note this breaks 'local' detection on OS X (Yosemite) - it incorrectly thinks I'm connected via telnet. With this change:

![screen shot 2015-11-11 at 16 54 50](https://cloud.githubusercontent.com/assets/755459/11097051/04beb10e-8895-11e5-9905-ef678e0890af.png)

Reverting (`git revert 0d7d3fdcf1a892149c0ffbbc580248deefe0be70`) :

![screen shot 2015-11-11 at 16 55 17](https://cloud.githubusercontent.com/assets/755459/11097064/17c9db34-8895-11e5-8ad1-e546a8eccae4.png)

**Comment by dolmen** [comment]
@daverigby Please open a new issue with a link to this one, and include in the report the exact version (commit) you are testing.

**Comment by daverigby** [comment]
Done: https://github.com/nojhan/liquidprompt/issues/407
