### ISSUE TITLE
Hostname not shown after 'sudo -s' under tmux

### ISSUE THREAD

**Issue by cyril-bouthors** [nojhan/liquidprompt#328]
Without tmux, the hostname is shown:

```
[cyb@wheezy:~] $ sudo -s
[root@wheezy:~] # 
```

With tmux, the hostname is not shown:

```
[cyb@wheezy:~] $ tmux
(...)
[cyb@wheezy:~] $ sudo -s
[root:~] # 
```

Is there a way to get hostname shown with sudo -s?

Thanks

**Comment by dolmen** [comment]
For the record, `LP_HOSTNAME_ALWAYS` is examined just once when liquidprompt loads, not at every prompt display. So you have to reload liquidprompt after changing the value.
