### ISSUE TITLE
grep: conflicting matchers specified -- output(error?)

### ISSUE THREAD

**Issue by anandjeyahar** [nojhan/liquidprompt#338]
Every time I execute a command it executes the command but also prints this error 

grep: conflicting matchers specified

I haven't customized any configurations, just followed the instructions in README. Colours  and battery work fine.
Am running on latest debian 8(jessie), with GNU bash 4.3.30(1)-release.  Any clues as to how to debug this further? 
P.S: Am just getting used to liquidprompt and love it.

**Comment by dolmen** [comment]
Do you have `grep` aliased like in #340?

**Comment by anandjeyahar** [comment]
Yep.. indeed. .I had grep aliased to grep -G.. Removing the alias removes the message. Still not sure, why it happens only on git repo folders. In any case closing, as I don't really need that alias. 
Thanks.

**Comment by darthmdh** [comment]
Actually this is a bug.  Liquidprompt is acting in ignorance of shell expansion, and assuming system utilities like grep have not been aliased.  Every invocation should have the keyword 'command' prepended to make this assumption true, i.e. use '| command grep [...]'; this is probably true for every invoked utility (not just grep).

**Comment by dolmen** [comment]
@darthmdh `grep` and `git` are now (`develop` branch) called with `\` to escape aliasing. This should be applied to all commands, but is painful to do and obscures the code.
