### ISSUE TITLE
sudo: check for NOPASSWD access to ALL or root

### ISSUE THREAD

**Issue by dolmen** [nojhan/liquidprompt#344]
If root access is enabled without password, the sudo mark should be permanently enabled.

```
$ sudo -l
...
    (ALL) NOPASSWD: ALL
...
    (root) NOPASSWD: ALL
...
```

In this case `_lp_check_sudo` must be a no-op (instead of dynamic) and `LP_COLOR_MARK` fixed to `$LP_COLOR_MARK`.
We could even colorize the username as if he's root (see `LP_USER` and `LP_COLOR_USER_ROOT`).

**Comment by Rycieos** [comment]
Thanks for the enhancement idea, this was pretty simple to implement using `sudo -nvk`, building on the work done in #702
