### ISSUE TITLE
sudo: disable feature if user not in sudoers

### ISSUE THREAD

**Issue by dolmen** [nojhan/liquidprompt#345]
Disable the feature if the user is not in the `sudoers` file. We must absolutely avoid triggering `sudo` security alerts (and disable this feature by default if necessary).

Should probably parse `sudo -l`.

Reported by @jsuter1 as a [comment in #335](335#issuecomment-70603952).

**Comment by jsuter1** [comment]
It looks like `sudo -l` and even `sudo -v` can still trigger alerts if the user isn't in the `sudoers` file.

    Jan 20 16:36:50 hostname sudo:    jsuter1 : user NOT in sudoers ; TTY=pts/2 ; PWD=/home/jsuter1 ; USER=root ; COMMAND=/bin/true
    Jan 20 16:36:55 hostname sudo:    jsuter1 : command not allowed ; TTY=pts/2 ; PWD=/home/jsuter1 ; USER=root ; COMMAND=list
    Jan 20 16:36:59 hostname sudo:    jsuter1 : command not allowed ; TTY=pts/2 ; PWD=/home/jsuter1 ; USER=root ; COMMAND=validate

I'm not too familiar with liquidprompt (just the guy reading the auth logs!) but another approach may be to wait for the user to run `sudo` for the first time and base the feature off that.

Checking for the existence of /var/db/sudo/lectured/**user** crossed my mind, but /var/db/sudo is locked down to 700.

**Comment by dolmen** [comment]
The sudo feature is now completely disabled by default, as there is no way to check sudo rights without triggering a security alert.
d6387f2d4b513051988616a73222201296167db6

**Comment by dolmen** [comment]
https://xkcd.com/838/
![xkcd 838: Incident](https://imgs.xkcd.com/comics/incident.png)
