### ISSUE TITLE
Try to clone or integrate oh-my-git

### ISSUE THREAD

**Issue by ldidry** [nojhan/liquidprompt#348]
Oh-my-git is a customized prompt when you are in a git repo. I think it's even prettier than liquidprompt is. It could be nice to behave like it or to have a way to integrate it.

Say, a configuration variable USE_OH-MY-GIT would use oh-my-git instead of the liquidprompt git behavior. Or change the way liquidprompt handles git repo.

And if liquiprompt could behave like oh-my-git for all vcs it supports… Bazinga !

<https://github.com/arialdomartini/oh-my-git>

**Comment by dolmen** [comment]
What do you think of #342?

**Comment by ldidry** [comment]
Sorry for the duplicate. It wasn't in the issue list but in the PR list, so I didn't saw it.

**Comment by dolmen** [comment]
@ldidry I would like you to review #342. Would it satisfy your need?
