### ISSUE TITLE
Cygwin: set LP_ENABLE_JOBS=0 by default

### ISSUE THREAD

**Issue by dolmen** [nojhan/liquidprompt#350]
On cygwin the `jobs` command is very slow as [reported by @davidknaack](130#issuecomment-76205930). So it would be better to disable it by default on this platform.

**Comment by antonpiatek** [comment]
Not sure whether to put this on a new bug, or here, but on an ubuntu 14.04 install I'm finding the jobs hook for liquidprompt to be very slow. 
The jobs command itself isn't slow it seems, but liquidprompt is very slow with LP_ENABLE_JOBS
