### ISSUE TITLE
Execute "history -a; history -n;" at every command (previously in my PROMPT_COMMAND)

### ISSUE THREAD

**Issue by durdn** [nojhan/liquidprompt#352]
To make sure I can re-use commands across multiple shells I had for a very long time this line in my `.bashrc`:

    export PROMPT_COMMAND="history -a; history -n;"

Liquidprompt is explicit in the documentation that the value will be overwritten but I still would like to execute those to commands at every prompt. Any suggestions on how to accomplish that?

**Comment by waldyrious** [comment]
@durdn can you comment on [this answer](http://superuser.com/a/734410/112593) that says that -n should be avoided?

**Comment by durdn** [comment]
@waldyrious I have used the version with `-n` for a while without much trouble but if there's an even more accurate solution I'll take it! I can go with `history -a; history -c; history -r`. The question stands, how easy is it to add this (i.e. my own custom post or pre-command) to liquid prompt?

**Comment by dolmen** [comment]
@waldyrious

Just set your `PROMPT_COMMAND` *before* loading `liquidprompt`. Everything is supposed to work (despites being documented as not working, but just for safety). Check that your own `PROMPT_COMMAND` is properly saved into `LP_OLD_PROMPT_COMMAND`.

By the way, do not use `export` because `.bashrc` is already loaded in all sub shells, so you do not need the inheritance of this variable.

**Comment by durdn** [comment]
Sorry I am late to comment on the issue.

I solved it by re-defining `PROMPT_COMMAND` like the following after sourcing `.liquidprompt`:

```
source $HOME/.liquidprompt
#make sure the history is updated at every command
shopt -s histappend
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"
```

**Comment by dolmen** [comment]
@durdn Be aware that the `prompt_off`, `prompt_on`, and `prompt_OFF` commands of liquidprompt will not work with your config.

**Comment by kynan** [comment]
@durdn Setting `PROMPT_COMMAND` *before* sourcing liquidprompt works fine for me: history commands are executed as expected.
