### ISSUE TITLE
Connection type detection under Grid Engine

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#358]
I'm often connecting to a random machine in a cluster through the Grid Engine/Open Grid Scheduler batch-queuing system. It uses rsh (not ssh) and CentOS 6.6.

The `_lp_connection` function fails to detect the remote connection and consider it's a local one.

The problem raises because the `who am i` call returns an empty string. I'm not sure how to handle this case, and surely changing the detection method is not a good idea here.

Anyway, the parent session detected with `ps -o comm= -p $PPID` correctly returns `sge_shepherd` (SGE means "Sun Grid Engine", a former name) which may be used to detect the remote session.

Should we add a case for an empty `sess_src` and `sess_parent == sge_shepherd`?

**Comment by dolmen** [comment]
Could you test my `fix/connection-source-tmux` branch?

**Comment by dolmen** [comment]
The `fix/connection-source-tmux` branch is merged. Could you check `develop`?

**Comment by Rycieos** [comment]
Closing this since it seems like it was fixed in 2703ee03c83595e95fa60fb68ff6d77c042a7ca0 and I have no way to test this specific environment case.
