### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by vlkz** [nojhan/liquidprompt#359]
Where would I find different liquidprompt theme files to try?

**Comment by dolmen** [comment]
Nobody ever contributed an alternate theme. So either nobody is using them, or at least nobody is sharing them with the original project.
If you find some, please post the links in this issue.

**Comment by wouterprins** [comment]
The theme that is provided works fine for most people i guess, i made some small adjustments but its not worth creating a new theme for that, which may be the point why noone submits them.

**Comment by nojhan** [comment]
A powerline theme is now available.
