### ISSUE TITLE
liquidprompt joined Debian

### ISSUE THREAD

**Issue by aborrero** [nojhan/liquidprompt#374]
Hi, just to let you know liquidprompt joined Debian.

Some links:
 * https://tracker.debian.org/pkg/liquidprompt
 * https://github.com/aborrero/pkg-liquidprompt

Some things to note in the Debian package:
 * all exported functions were prefixed `liquidprompt`. For example: `liquidprompt_tag` or `liquidprompt_off`. So we get a common namespace for available commands.
 * there is a small script to activate liquidprompt for the current user: `liquidprompt_activate`.
 * small changes to the default config (to get the prompt in similar shape of debian default).
 * a man page was added.

Please, let me know if you are interested in any of these things to be merged upstream.

**Comment by dolmen** [comment]
The code injected by [`liquidprompt_activate`](/aborrero/pkg-liquidprompt/blob/5adf7be49f21e2d99698421b1b72525e9340afc9/debian/liquidprompt_activate) is just awfull. Here is what it should be:
```
[[ $- = *i* ]] && . /usr/share/liquidprompt/liquidprompt
```

Renaming the basic commands that the user interacts with makes it a different user experience. This is a fork. On the first support request that I get that refers to the features of your fork I may ask you to rename it to another name to avoid the confusion.

> Please, let me know if you are interested in any of these things to be merged upstream.

I'm interested in the man page.

**Comment by aborrero** [comment]
`liquidprompt_activate` uses that code to try to be POSIX compliant, the code you propose seems to be a bashisms.
I think we can get `liquidprompt` in shape to be used with lot of shells (apart of `zsh`and `bash`) if we stick to the POSIX standard (however a bit of work is required in the main code).

Regarding the renaming of the functions, the reason is to have a common namespace for all liquidprompt-related commands. I can't guarantee (now or in the future) that there aren't any other packages using the `prompt_tag` name: it's too generic.
In fact, I would suggest merging this upstream.

**Comment by dolmen** [comment]
> `liquidprompt_activate` uses that code to try to be POSIX compliant, the code you propose seems to be a bashisms.
Why is it wrong to use bashisms in `~/.bashrc` and zshisms in `~/.zshrc`?

> I think we can get liquidprompt in shape to be used with lot of shells (apart of zshand bash) if we stick to the POSIX standard (however a bit of work is required in the main code).

It is already a nightmare to maintain `liquidprompt` for both bash and zsh. Forget about porting the current code to be more shell agnostic.
See instead my other project, [angel-PS1](/dolmen/angel-PS1) that use a more radical solution to be able to have a dynamic prompt for bash/zsh/mksh/dash/ksh93/tcsh/fish. Still work in progress.

>Regarding the renaming of the functions, the reason is to have a common namespace for all liquidprompt-related commands.

I understand your reasons.

> I can't guarantee (now or in the future) that there aren't any other packages using the prompt_tag name: it's too generic.

You have to understand my reasons. This is breaking compatibility for a hypothetical future conflict with something else. We'll see when that happens.

>In fact, I would suggest merging this upstream.

No.

**Comment by aborrero** [comment]
>
>
>  It is already a nightmare to maintain liquidprompt for both bash and
> zsh. Forget about porting the current code to be more shell agnostic.
> See instead my other project, angel-PS1 <http:///dolmen/angel-PS1> that
> use a more radical solution to be able to have a dynamic prompt for
> bash/zsh/mksh/dash/ksh93/tcsh/fish. Still work in progress.
>

Ok. I just think that sticking to the POSIX standard should make things
easier. After all, I would see a non-POSIX compliant shell rather
weird/ugly.


>  Regarding the renaming of the functions, the reason is to have a common
> namespace for all liquidprompt-related commands.
>
> I understand your reasons.
>
> I can't guarantee (now or in the future) that there aren't any other
> packages using the prompt_tag name: it's too generic.
>
> You have to understand my reasons. This is breaking compatibility for a
> hypothetical future conflict with something else. We'll see when that
> happens.
>

I understand you as well. I think there is no problem in maintaining the
small patch [0] in the Debian world to make the rename. You can consider it
the 'debian flavour' of liquidprompt.
If I have to report a Debian bug here, I will take the rename into account.
So it's more or less 'transparent' for you.
A similar thing happens with the default configuration [1].

Best regards.

[0]
https://github.com/aborrero/pkg-liquidprompt/blob/master/debian/patches/function_prefixes.patch
[1]
https://github.com/aborrero/pkg-liquidprompt/blob/master/debian/patches/debian-default-cfg.patch
-- 
Arturo Borrero González
