### ISSUE TITLE
extra @ symbol

### ISSUE THREAD

**Issue by sbhal** [nojhan/liquidprompt#375]
With 
LP_USER_ALWAYS=0 and
_LP_HOST_SYMBOL=""

the '@' symbol between user@host-name should also disappear.

**Comment by dolmen** [comment]
`_LP_HOST_SYMBOL` is an internal variable, as the `_LP_` prefix implies. Setting it to another value is unsupported.

If you want a particular behaviour of liquidprompt, explain what you would like and we'll see if it is possible with the current code and how I can help you to tweak variables or what must be changed.

**Comment by sbhal** [comment]
I like the idea of minimalist prompt. In a scenario where you only use one remote server and don't really need to see 'user@hostname' stub in prompt. I wanted to achieve this using liquidprompt.

For this, I made
LP_USER_ALWAYS=0 and _LP_HOST_SYMBOL=""

Now my prompt looks like:
1d [@:/local/mnt/workspace/sbhal] $
and I want it to look like
1d [/local/mnt/workspace/sbhal] $

Also, I think _LP_HOST_SYMBOL should be made external if someone desires not to see hostname of remote logged-in machine.

**Comment by dolmen** [comment]
Try this in your .bashrc, just after loading liquidprompt:
```
LP_HOST=
```
