### ISSUE TITLE
hddtemp

### ISSUE THREAD

**Issue by dolmen** [nojhan/liquidprompt#378]
`hddtemp` (temperature info from disk drive) is another source of temperature info on a Linux system.

**Comment by jaesivsm** [comment]
```hddtemp``` is only executable by root (at leat on debian) and quite slow from what I remember. Plus it'd require either conf so that it'd query the wanted disks or a discovery processus to list existing disks.
For those reasons I can't really see a good implementation of hddtemp happening in liquidprompt.

**Comment by dolmen** [comment]
Thanks for the feedback.
