### ISSUE TITLE
Support for Conda environment manager

### ISSUE THREAD

**Issue by tobanw** [nojhan/liquidprompt#384]
I'm using [Conda](http://conda.pydata.org/docs/using/envs.html) instead of virtualenv for python environment management. However, it seems that liquidprompt only looks for the `VIRTUAL_ENV` environment variable (used by virtualenv), but Conda sets `CONDA_DEFAULT_ENV` [instead](https://github.com/conda/conda-env/blob/develop/bin/activate).

It looks like you would just need to add another else-if block to check for the conda variable [here](https://github.com/nojhan/liquidprompt/blob/master/liquidprompt#L1566).

**Comment by DancingQuanta** [comment]
This issue should be closed now that I can see conda environments.

**Comment by Rycieos** [comment]
This enhancement should be working for a while now with #425 merged in commit 07be96765bbd742c5c2846ef6adbb0c253948216.
