### ISSUE TITLE
pwd is displayed wrong when it contains a $ char

### ISSUE THREAD

**Issue by dserodio** [nojhan/liquidprompt#389]
We have some buggy scripts which create directories containing `$` characters. When inside one of these directories, the current directory shown by liquidprompt is wrong:

    [/tmp] $ mkdir '$foo'
    [/tmp] $ cd '$foo'
    [/tmp/] $ pwd
    /tmp/$foo

**Comment by dolmen** [comment]
Confirming this bug is still in develop b53e53b6a5a5b783896b8fd75d341dbb1d7d5e5c.
