### ISSUE TITLE
Asynchronous Right Prompt

### ISSUE THREAD

**Issue by jasonszhao** [nojhan/liquidprompt#396]
I have gotten a asynchronous right prompt working on my machine. I was wondering this idea could make it as a pull request. It would only work in Zsh, and could fail nicely in Bash.

It is based off of [this article](http://www.anishathalye.com/2015/02/07/an-asynchronous-shell-prompt/) by @anishathalye.

This demo is on iTerm2, OS 10.11. I have added a `sleep 1` in the `_lp_set_prompt` for the right-side one to emphasize the asynchronousness.  
![async-liquid-rprompt](https://cloud.githubusercontent.com/assets/5283282/10421105/5753a138-7056-11e5-9718-266394967b7b.gif)

I am aware of #154, which discusses right prompts in general.

**Comment by dolmen** [comment]
As right prompt and asynchronous prompt reset are zsh only, this is out of scope for liquid prompt.

But as @paulvt has shown in #154, you can use liquid prompt functions to build your own right prompt.
