### ISSUE TITLE
`git rev-parse --inside-work-tree` doesn't exist.

### ISSUE THREAD

**Issue by pjvandehaar** [nojhan/liquidprompt#397]
It should be `git rev-parse --is-inside-work-tree`, unless I misunderstand what you're doing at https://github.com/nojhan/liquidprompt/blob/master/liquidprompt#L723

If you change it to `git rev-parse --is-inside-work-tree`, then it might need to check for `true` in the standard output.

**Comment by dolmen** [comment]
This has been fixed 10 months ago in 64029ad75d108a0619958c337fd64fe18560988e.
Please check the `devel` branch (yes, I have to make a release!).
