### ISSUE TITLE
Is `LP_ENABLE_VCSH` ever used?

### ISSUE THREAD

**Issue by pjvandehaar** [nojhan/liquidprompt#398]
Is there a reason for `LP_ENABLE_VCSH` to be at  https://github.com/nojhan/liquidprompt/blob/dbe3c15026afdb8b35d5a758081fdf7c2c860ad0/liquidprompt#L292?

(Apologies if this is a stupid question.)

**Comment by dolmen** [comment]
I don't think so. Cc: @clneagu

Related to #287

**Comment by nojhan** [comment]
Commented out.
