### ISSUE TITLE
grep: Unmatched ) or \

### ISSUE THREAD

**Issue by tconstans** [nojhan/liquidprompt#401]
Dear all,

liquidprompt is displaying this error message:
>grep: Unmatched ) or \)
bash: let: detached=: syntax error: operand expected (error token is "="

Seems to be caused by ) not being escaped on line 679 :

`$_LP_ENABLE_SCREEN && let detached=$(screen -ls 2> /dev/null | grep -c '[Dd]etach[^\)]*\)$')` 

Best regards

**Comment by dolmen** [comment]
Which operating system? Which version of grep?

**Comment by dolmen** [comment]
Could you also give me the output of `screen -ls 2>/dev/null` when this issue occurs?

**Comment by tconstans** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hello Olivier,

I am not a screen user

screen -ls
No Sockets found in /var/run/screen/S-root.

grep --version
grep (GNU grep) 2.20

cat /etc/redhat-release
CentOS release 6.7 (Final)

I get the same issue on on CentOs 7.1.1503 which is also using grep v 2.
20


I have ran the following line on different systems (no screen running) :
let detached=$(screen -ls 2> /dev/null | grep -c '[Dd]etach[^)]*)$')

debian 7.9 - grep 2.12 OK
centos 6.7 - grep 2.20 "grep: Unmatched ) or \)"
centos 7 - grep 2.20 "grep: Unmatched ) or \)"

Best regards

I get the same result wether i use tmux or not.
Le 26/10/2015 14:29, Olivier Mengué a écrit :
> Could you also give me the output of `screen -ls 2>/dev/null` when
> this issue occurs?
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/nojhan/liquidprompt/issues/401#issuecomment-1511333
07
>
> 
- -- 
Thomas Constans
Services en informatique libre
T: 33(0)6 23 37 87 85
@: http://opendoor.fr
#: https://twitter.com/ThomasConstans
gpg: 0xBA19745F80410541
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJWLnGzAAoJELoZdF+AQQVBwkYIAKfoBMQ2MsMWZqASR5LDUuVc
Ji5v/HAOlxTnGMNa//j+Op9+ks5TLxQwAASNObU/pbPlcq/xjrO0nlX4QA4fLWx6
iLLvaiFGD96+jfsEpS5Gl/E6w+lp59MCKhssmq0pbf7VS7hfNzvx5IWmdyP60H64
DdfQlvud/1F4LYKqH6mptcZBUgmkd83xSHANjS8NwyElPXF0vmotQZxY9KHzNxcM
Ng/vqhLoVqTKZM011CwmDrLmIPZzQR75MwSUA9+k0gsriVEo/mHrY56yC2pQz674
Tt+R/9ZNnJAGobSGjqiNDhmXK5a7ECNd+kEa79HjGkrNhPVjrEeqaEzJeAqkWvg=
=NTt/
-----END PGP SIGNATURE-----

**Comment by dolmen** [comment]
In the `develop` branch the code is:

```
screen -ls 2> /dev/null | \grep -c '[Dd]etach[^)]*)$'
```

There is a backslash before `grep`. Could you check that the issue still happens with the `develop` branch?

Could you check:
- if grep is aliased: `alias grep`
- if $GREP_OPTIONS is set: `echo $GREP_OPTIONS`
Some workaround for both cases are implemented in the `develop` branch.

**Comment by tconstans** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Olivier,

I confirm it is related with grep being realiased by RedHat / CentOS

if i unalias all my alias, use /usr/bin/grep or \grep i no longer get
the error.

Bear in mind these aliases are not setup by me but distributor.

I'll have a look at the development branch

Thanks for the quick feedback

keep up the good work



Le 26/10/2015 19:52, Olivier Mengué a écrit :
> In the `develop` branch the code is:
> 
> ``` screen -ls 2> /dev/null | \grep -c '[Dd]etach[^)]*)$' ```
> 
> There is a backslash before `grep`. Could you check that the issue
> still happens with the `develop` branch?
> 
> Could you check: - if grep is aliased: `alias grep` - if
> $GREP_OPTIONS is set: `echo $GREP_OPTIONS` Some workaround for both
> cases are implemented in the `develop` branch.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/nojhan/liquidprompt/issues/401#issuecomment-1512467
57
>
> 
- -- 
Thomas Constans
Services en informatique libre
T: 33(0)6 23 37 87 85
@: http://opendoor.fr
#: https://twitter.com/ThomasConstans
gpg: 0xBA19745F80410541
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJWLnmiAAoJELoZdF+AQQVBseIH+wUcItG802EUlC3bidzfw5v3
wkobHfTmfu2GJIH66nUmTfxn9uwv8VhgMu3zDns5Qm112DyOTvQsLaMLj9iYKGUP
eCjwM0sFHSJh1ZJsOIuHQtHVJWtmoAr5wpBZT+FA2Mfq/FnUoDgtugsIRilGxBpa
R31lw50X7CMpIQKDE5hx8HxHfh3A1IgscOzrb3rOlP/RHS+TWvrSX2OoYE5/vFQ/
+h2G6nnebuVrv7RF3wXp0O5UKYaNRwHKJqAufzrm0IiKx97j7rghxxeTDI8yG0Fu
kDHAo0+cMdvK1VPEaUOXsSGbCX6aRIqeUTZleKKVhTTv+aFJhwi6ymXsutZgl8k=
=Aoh5
-----END PGP SIGNATURE-----

**Comment by dolmen** [comment]
Already fixed by 724feebf0bb4ff61916f1fbda421794c25415ca3 and 3c4d8eb5c65b0579a51f8b3134c06ee0a3840576.
