### ISSUE TITLE
Debian sid desktop: "No support for device type: thermal" message

### ISSUE THREAD

**Issue by sebrem** [nojhan/liquidprompt#410]
Hi,

as of recent I have

    No support for device type: thermal
    ⌂131% [sebrem:~] $

showing in every new prompt. Maybe it's more a bug in Debian/acpi but I didn't find it yet. Any ideas? I run debian unstable with latest kernel

    [sebrem:~] $ uname -a
    Linux neocortex 4.3.0-trunk-amd64 #1 SMP Debian 4.3-1~exp1 (2015-11-04) x86_64 GNU/Linux
    No support for device type: thermal
    [sebrem:~] $ cat /etc/issue
    Debian GNU/Linux stretch/sid \n \l
    [sebrem:~] $ apt show liquidprompt
    Package: liquidprompt
    Version: 1.9-4
    [...]

I think this started like 3 or 4 weeks ago when a new acpi version was uploaded to Debian but I didn't find any hint there.

**Comment by dolmen** [comment]
I'm sorry. The Debian fork of Liquidprompt is not supported here. Contact @aborrero who made this package.

You should instead try the `develop` branch in this repo. Your issue is probably already fixed. If this is not the case, open another issue mentioning the last commit sha1 on the develop branch.

**Comment by aborrero** [comment]
I'm sorry. Is not fixed in liquidprompt in the develop branch.

Last commit is 8f5ef7de2d3b5eb8672c3b3f12ed0c06679081f3

**Comment by aborrero** [comment]
BTW, you insist in calling the debian package 'a fork', while the difference is just the name of 3 functions.
I don't understand your position of 'not supported here', it seems you are against distro packaging. That isn't how the linux world works.

I know where is the issue, but with your apparently non-collaborative behaviour makes me thinking of fixing this issue just in the debian package.

Let's not be so negative. I would really like to thank you for pinging me in this bug report. Thanks, and thanks for maintaining liquidprompt, it's really appreciated :-)

**Comment by dolmen** [comment]
@aborrero My position is that I only reply to tickets against the latest commit of the `develop` branch. A packaged version made from a released version of liquidprompt is frozen from many months ago so tracking changes is too much effort for me while an interested user can make the effort of reproducing the issue from the develop branch.

**Comment by dolmen** [comment]
> I'm sorry. Is not fixed in liquidprompt in the develop branch.

What is the output of the following commands?

    acpi -t ; echo $?

**Comment by aborrero** [comment]
Every time acpi is called and there is no support for a device type, acpi writes to stderr.
As you can't control from liquidprompt the acpi configuration/support, I would suggest to simply redirect to /dev/null all stderr produced by acpi calls.

Compare these two calls:
https://github.com/nojhan/liquidprompt/blob/develop/liquidprompt#L1162
https://github.com/nojhan/liquidprompt/blob/develop/liquidprompt#L1447

The first redirects stderr, the second don't, hence the problem.

I'm sending a pull request.

**Comment by aborrero** [comment]
Also, I would suggest releasing more often, let's say every 6 month. Last release 1.9 seems was release more than a year ago.
By releasing a bit more often user could do better error reporting and bug triaging may be easier.

**Comment by dolmen** [comment]
> Every time acpi is called and there is no support for a device type, acpi writes to stderr.

This is not the case with acpi 1.7 (Ubuntu 14.04).

> As you can't control from liquidprompt the acpi configuration/support, I would suggest to simply redirect to /dev/null all stderr produced by acpi calls.

The difference between a battery and a thermal sensor is that the battery can be temporaly removed. This is why errors from `acpi --battery` are catched at runtime.

Instead, thermal sensor are here forever (well, at least the shell session), so it is better to completely disable the `TEMP` feature at prompt install time. If an error occurs at runtime (when the prompt is computed) as reported here, this shows that the install time check does not catch all failures. This is the kind of error that I don't want to be hidden.

**Comment by dolmen** [comment]
I'm still waiting for the result of this command:

    acpi -t ; echo $?

**Comment by sebrem** [comment]
Sorry, there was such a big side-discussion I didn't feel like this was addressed me ;-)

    No support for device type: thermal
    ⌂178% [sebrem:~] 1 $ acpi -t ; echo $?
    No support for device type: thermal
    0
    No support for device type: thermal
    ⌂169% [sebrem:~] $ 

Thank you!

**Comment by dolmen** [comment]
Please try the `fix/410-better-thermal-init` branch. It is supposed to fix your issue (as well as #319, #381, #387 for errors reported by `sensors`).
Cc: @jaesivsm

**Comment by sebrem** [comment]
yes, thank you very much, that seems to fix it:

    No support for device type: thermal
    [sebrem:/usr/local/src/liquidprompt] c5be630 ± source ./liquidprompt
    ⌂76% [sebrem:/usr/local/src/liquidprompt] c5be630 ±

**Comment by dolmen** [comment]
Merged with b816d59a8c6232557b46ff7e5e7dd239715da57b
