### ISSUE TITLE
Please release more often

### ISSUE THREAD

**Issue by aborrero** [nojhan/liquidprompt#417]
Dear liquidprompt team,

please release more often, last release 1.9 is more than a year old.

best regards.

**Comment by dolmen** [comment]
As you have probably noticed I did many changes recently and that is to cleanup things before a incoming release.

**Comment by aborrero** [comment]
On 23 December 2015 at 11:51, Olivier Mengué <notifications@github.com>
wrote:

> As you have probably noticed I did many changes recently and that is to
> cleanup things before a incoming release.
>
>
> Great!

thanks.
-- 
Arturo Borrero González

**Comment by aborrero** [comment]
ping

**Comment by dolmen** [comment]
After one very stable month (no issue submitted), v_1.10 is now tagged.
