### ISSUE TITLE
USER always displayed within Tmux even when LP_USER_ALWAYS set to 0

### ISSUE THREAD

**Issue by rdlugosz** [nojhan/liquidprompt#418]
In [my config](https://github.com/rdlugosz/dotfiles/blob/master/liquidpromptrc) I have the `LP_USER_ALWAYS` variable set to `0`. When I open a new terminal I do not see my username in the prompt (as expected). Then, I'll start a fresh Tmux session and my username will appear in the prompt (unexpected).

Versions:
liquidprompt: def86eb
tmux: 2.1
zsh: 5.0.8
OSX: 10.11.2

**Comment by dolmen** [comment]
I've not been able to reproduce your issue.

Could you check the value of the LP_USER_ALWAYS variable in your tmux session from the shell prompt?
Are you under the root user or any other user?

**Comment by rdlugosz** [comment]
wow - sorry for leading down a wild goose chase... I've restarted the system since creating this issue and now I'm not seeing the problem. My apologies!

I suspect I may have been reconnecting to a tmux session rather than spawning a new one. :confused:
