### ISSUE TITLE
use $XDG_CONFIG_HOME and $XDG_CONFIG_DIRS according to XDG basedir spec

### ISSUE THREAD

**Issue by smcv** [nojhan/liquidprompt#420]
liquidprompt has `~/.config/liquidpromptrc` as a supported config file, which is great. However, it does not follow the rest of the [freedesktop.org (XDG) basedirs specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), which is what popularized `~/.config`. Part of the value of that spec is that it gives a small number of environment variables which can be overridden once, to divert all basedir-compatible programs' configuration, cached files or other internal data (as appropriate) to a different location, with configuration and internal data using a `$PATH`-like search path rather than just a single directory.

Current implementation:

```
    elif [[ -z "$XDG_HOME_DIR" ]]
    then
        configfile="$HOME/.config/liquidpromptrc"
    else
        configfile="$XDG_HOME_DIR/liquidpromptrc"
    fi
```

`$XDG_HOME_DIR` is not part of the basedir spec and it is unlikely that users will have set it. The correct implementation would be to look in `${XDG_CONFIG_HOME:-"$HOME/.config"}` as top priority, and then in each `:`-separated element of `${XDG_CONFIG_DIRS:-/etc/xdg}` in decreasing priority order (like `$PATH`). You could either go through those in decreasing priority order and source the first file found, or go through them in reverse (increasing priority) order and source all of them (so that higher priorities override lower, like the existing support for the personal config file overriding `/etc/liquidpromptrc`).

Sample code for sourcing the first one is something like this:

```bash
if [[ -f "$HOME/.liquidpromptrc" ]]; then
    configfile="$HOME/.liquidpromptrc"
else
    local _lp_IFS="$IFS"
    local IFS=":"
    local path
    for path in "${XDG_CONFIG_HOME:-"$HOME/.config"}" $XDG_CONFIG_DIRS:-/etc/xdg}; do
        if [[ -f "$path/liquidpromptrc" ]]; then
            configfile="$path/liquidpromptrc"
            break
       fi
    done
    IFS="$_lp_IFS"
fi
if [[ -n "$configfile" ]]; then
    . "$configfile"
fi
```

**Comment by dolmen** [comment]
Related to #415.

**Comment by smcv** [comment]
> go through them in reverse (increasing priority) order and source all of them

Having implemented that, I think I prefer it - it isn't really any more complicated, and it's consistent with the current fallback from ~/.liquidpromptrc to /etc/liquidpromptrc. I've effectively inserted the XDG_CONFIG_* entries as an intermediate priority between those two extremes.

**Comment by jcrben** [comment]
+1 for `XDG_HOME_DIR` not really being a thing.

**Comment by dolmen** [comment]
@jcrben Liquidprompt is both for bash AND zsh. I can't choose between `${XDG_CONFIG_HOME}/bash` and `${XDG_CONFIG_HOME}/zsh.

**Comment by jcrben** [comment]
Why can't  you support both? And check to see which shell is loaded, using http://stackoverflow.com/a/3327022/4200039?

I will probably use this for both bash and zsh (probably with a symlink to keep them in sync), as I fall back to bash sometimes.

**Comment by smcv** [comment]
> `$XDG_HOME_DIR` is not part of the basedir spec

This part was in fact already fixed in the `develop` branch. If `develop` will continue to be the focus of development (equivalent to the use of `master` in projects like git and Linux), please consider marking it as the default branch in GitHub.

> The correct implementation would be to look in `${XDG_CONFIG_HOME:-"$HOME/.config"}` as top priority, and then in each `:`-separated element of `${XDG_CONFIG_DIRS:-/etc/xdg}` in decreasing priority order (like `$PATH`).

This part is still missing from `develop`. Updated PR for `develop`: #427.

> Also, it shouldn't really go into `~/.config` directly. It should go into `~/.config/bash` or `~/.config/zsh`.

I disagree. `liquidpromptrc` isn't (directly) configuration for bash or zsh, it's configuration for liquidprompt, and the fact that you're considering using a symlink suggests that looking in different places for different shells would just be creating more work for yourself. If you do want different configuration for bash-with-liquidprompt and zsh-with-liquidprompt, you could test `$BASH_VERSION` and/or `$ZSH_VERSION` like liquidprompt itself does.

If it's in a subdirectory at all, then I'd expect that subdirectory to be `~/.config/liquidprompt/`, but I think it's fine without a subdirectory: various other things on my system use files placed directly inside `~/.config`, including [xdg-user-dirs](https://wiki.freedesktop.org/www/Software/xdg-user-dirs/).

[The basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) mentions subdirectories in the sense that its example used to describe the desired lookup rules is `subdir/filename`, but that's obviously a placeholder, and I don't think the authors intended that to be forbidding files not in a subdirectory.

**Comment by jgottfried** [comment]
> If it's in a subdirectory at all, then I'd expect that subdirectory to be ~/.config/liquidprompt/, but I think it's fine without a subdirectory: various other things on my system use files placed directly inside ~/.config, including xdg-user-dirs.
> 
> The basedir spec mentions subdirectories in the sense that its example used to describe the desired lookup rules is subdir/filename, but that's obviously a placeholder, and I don't think the authors intended that to be forbidding files not in a subdirectory.

It's true, it's not forbidden to use a subdirectory, but it would still be a reasonable idea to do so. Right now the liquidprompt file is a behemoth of about 1800 lines. At some point it will make sense to split that into multiple files (imho that is already the case) and then you will want a directory, so why not prepare this now?

**Comment by dolmen** [comment]
@jcrben The `liquidpromptrc` file is loaded as a shell script: it is just executed. This means you can use any shell statements in the file. So you could reduce your `~/.config/liquidpromptrc` to this single line to use config either from `~/.config/bash/liquidpromptrc` or `~/.config/zsh/liquidpromptrc`:
```sh
source ~/config/"$(basename "$0")"/liquidpromptrc
```

**Comment by smcv** [comment]
> Right now the liquidprompt file is a behemoth of about 1800 lines. At some point it will make sense to split that

This issue is about where to find the `liquidpromptrc` configuration file for liquidprompt, not the liquidprompt implementation itself. If liquidprompt itself was split into multiple files, that wouldn't necessarily mean that it was necessary or even useful to split liquidpromptrc into multiple files.

**Comment by zakame** [comment]
Just some testing breakage, see https://github.com/nojhan/liquidprompt/commit/36914a089aee00ec1f41c96cb227638cbd0ec53c#commitcomment-17172220

**Comment by smcv** [comment]
> testing breakage

See 0a196a913cbdf9d632019a7b6a52ea27d7b2554a (also submitted on updated PR #427) to fix that.
