### ISSUE TITLE
[bash] Return value or runtime isn't shown if used with other tools that ose $PROMPT_COMMAND 

### ISSUE THREAD

**Issue by schorsch3000** [nojhan/liquidprompt#436]
I use [direnv](http://direnv.net/), it also hooks as $PROMPT_COMMAND.

accoourding to the order i source direnf and liquidpromt i'll get a $PROMPT_COMMAND as:
`_direnv_hook;_lp_set_prompt`
this will have a working rumtime in my prompt, but the prompt doesn't show my the returncode of the command i've used. this is due to _direnv_hook overwrites $? before lp can get it.

the other way arround:
`_lp_set_prompt;_direnv_hook`
gives me the right return value, but a false runtime.
i'll get the time since the last prompt, nut the runtime.

my hacky solution to this problem is:

```
function _CATCH_RET_VAL(){
    export _CATCHED_RET_VAL=$?
}
function _THROW_RET_VAL(){
    return $_CATCHED_RET_VAL
}
export PROMPT_COMMAND="_CATCH_RET_VAL;_direnv_hook;_THROW_RET_VAL;_lp_set_prompt"

```
So, this is not something i needed to be solved, it'S more a notice that this problem exists :)

**Comment by dolmen** [comment]
Good hack!
But note that you don't have to use `export`. Here is your code, fixed and simplified:
```
function _throw_ret_val(){
    return $_ret_val
}
PROMPT_COMMAND='_ret_val=$?;_direnv_hook;_throw_ret_val;_lp_set_prompt'
```

**Comment by dolmen** [comment]
Note that Liquidprompt has native support for wrapping an existing $PROMPT_COMMAND. It is supposed to work, but I admit I have never used it myself.

So have you tried to setup direnv first so that $PROMPT_COMMAND is set when liquidprompt initialize?

**Comment by schorsch3000** [comment]
your shorter and less verboste fix works fine, thx.
as described, i've tried both, with different results.
