### ISSUE TITLE
Redesign the temperature indicator

### ISSUE THREAD

**Issue by dolmen** [nojhan/liquidprompt#448]
We are currently averaging all the temperature we collect.
I discovered that during the few last years the Linux kernel has exposed more and more temperature sensors. Averaging was ok when we got only temperature from 2 CPUs. But averaging temperature from a CPU and a GPU doesn't make sense. See [this example of `sensors -u` output](445#issuecomment-224237936) that has 10 temperature sensors.

**The temperature indicator should be completely redesigned.**

This ticket is to collect design ideas.

**Comment by Rycieos** [comment]
Just so it is clear

> We are currently averaging all the temperature we collect

is not how it is done anymore. (In fact, that seems to have been changed 8 years ago in 2f7cd163cde7637ada27d9cd66f2553ae22b3982).

We are instead returning the highest temperature found. That can be seen here:
https://github.com/nojhan/liquidprompt/blob/64e567af364a6a9c875bd31daec8a7eedd92290f/liquidprompt#L2546-L2551
and here:
https://github.com/nojhan/liquidprompt/blob/64e567af364a6a9c875bd31daec8a7eedd92290f/liquidprompt#L2559-L2564

But the point on CPU and GPU temperatures still stands. And there are many issues with `sensors` that can be found in many issues in this project. Not to mention possible speed improvements from removing binary/forking calls.

Right now the best proposal (in my opinion) is #623. It needs more work, but if anyone wants to work on this, that is the place to start.

**Comment by cmm** [comment]
regardless of how the temperature is calculated, why is retaining the highest value a good idea?  the effect is that if the temperature crossed the threshold once and liquidprompt happened to catch that, the prompt continues to show that high temperature value, red and bold, forever.  I struggle to see how exactly this is useful, but as usual I'm probably missing something

**Comment by Rycieos** [comment]
Thanks for the feedback.

Two parts here. First, imagine a scenario where your host was using a lot of GPU, but no CPU. Your GPU will naturally have high temps, but not your CPU. Averaging the sensors of the CPU with the GPU doesn't make sense, as you want to be aware of the high GPU. This is what the original issue is talking about.

What would make some sense is to average all the sensors on one device, like all the sensors on the GPU. This is difficult to automatically detect though.

> 
> the effect is that if the temperature crossed the threshold once and liquidprompt happened to catch that, the prompt continues to show that high temperature value, red and bold, forever.

Yeah, good point. So the second part is that we capture temperature data at a single moment. Ideally we would take an average or median of values over a time period. But this is not trivial. We cannot synchronously take multiple samples, as that would cause the prompt to hang. So we either need to run a background daemon to take samples over time and report back, or live with a single sample. And adding a background process would be a large undertaking for this project.

This is similar to why we don't report CPU utilization. Except for CPU it is worse: a single point in time is worthless, you need an average over time.

But the prompt doesn't show that value "forever", it gets reset the next time the prompt is generated. Unless you mean that the previous prompts stay in your terminal scrollback, in which case, well yes, but how would we fix that?

**Comment by cmm** [comment]
> But the prompt doesn't show that value "forever", it gets reset the next time the prompt is generated

That's not what I'm observing, and the code seems to confirm it: `lp_temperature` is never reset and is updated only when the new temperature is higher than the current value of `lp_temperature`.

**Comment by Rycieos** [comment]
> That's not what I'm observing, and the code seems to confirm it: `lp_temperature` is never reset and is updated only when the new temperature is higher than the current value of `lp_temperature`.

That's a bug then, every value in the prompt should update at every prompt. Huh, I can replicate that. I probably broke that at some point, not sure how I never noticed. You can open a new issue for that if you want the credit for the report.

**Comment by cmm** [comment]
Sure thing, https://github.com/nojhan/liquidprompt/issues/686

**Comment by Rycieos** [comment]
I am closing this. Since the original request was based off a flawed assumption, I do not think that this request is needed. I also think that most users would agree with me that the current implementation is good.

If anyone disagrees, please open a new issue and describe how it could be improved.
