### ISSUE TITLE
Error message related to CPU load at every prompt

### ISSUE THREAD

**Issue by DGrady** [nojhan/liquidprompt#449]
Operating system: Mac OS 10.10.5
Liquid Prompt version (tag, commit): dcc18d2454a57e0fb52722530d36b63a59a3efb6

On a new line before every prompt, I see `_lp_cpu_load:5: can't create temp file for here document: permission denied` printed to the terminal.

**Comment by DGrady** [comment]
This turned out to be due to something that had changed the permissions on `/private/tmp`; running Disk Utility's Repair Disk Permissions corrected the problem.

**Comment by dolmen** [comment]
Oh, this shows that `read ... <<<"$( ... )"` use a temporary file. I will see how to avoid this...
So thanks for the report! It was worth it!
