### ISSUE TITLE
_lp_set_prompt error on su

### ISSUE THREAD

**Issue by logological** [nojhan/liquidprompt#450]
Operating system: openSUSE 13.2
Liquid Prompt version (tag, commit): dcc18d2454a57e0fb52722530d36b63a59a3efb6

I'm trying out Liquid Prompt for the first time.  The tool works fine from my user account, but whenever I `su` to another account (such as root), the prompt is prepended with an error message about `_lp_set_prompt`:

```
[miller:~] $ su
Password: 
If '_lp_set_prompt' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf _lp_set_prompt
desktop-152:/home/miller # echo

If '_lp_set_prompt' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf _lp_set_prompt
desktop-152:/home/miller # exit
exit
1& [miller:~] 38s $
```

The other accounts don't have any bash dot files so I don't think anything there should be interfering with Liquid Prompt.  Though perhaps openSUSE's `/etc/bash.bashrc` has some incompatibility?

**Comment by dolmen** [comment]
I suspect that the `PROMPT_COMMAND` is exported in your environment. Liquid Prompt doesn't do that, but something else in openSUSE (or your own .bashrc) may do that.

Could you give me the output of this command from a `miller` shell:
```
export | grep PROMPT_COMMAND
```

**Comment by logological** [comment]
Your suspicion seems to be correct:

```
$ export | grep PROMPT_COMMAND
declare -x PROMPT_COMMAND="_lp_set_prompt"
$ fgrep PROMPT_COMMAND .bashrc
export PROMPT_COMMAND="history -a"
```

This was added to my `.bashrc` in hopes of preserving my history across sessions but maybe [the advice to do this](http://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows) wasn't so sound.

**Comment by dolmen** [comment]
At least, remove the `export` keyword.
As `.bashrc` is loaded in every shells (including non-interactive ones) you should set your `PROMPT_COMMAND` in a `[[ $- = *i* ]]` block like Liquid Prompt.

**Comment by logological** [comment]
Yes, that solved the problem.  Thanks for the explanation and advice; feel free to close this issue.
