### ISSUE TITLE
bash $_ variable

### ISSUE THREAD

**Issue by gex** [nojhan/liquidprompt#451]
Operating system: os x el capitan 10.11.5
Liquid Prompt version (tag, commit): 

```
[gex:~] $ brew list --versions liquidprompt
liquidprompt 1.10
```

i tried to search in the issues first but i didn't find anything related (#309 seems irrelevant, i didn't modify the configuration and the default is `LP_ENABLE_RUNTIME=0`). i'd like to use the `$_` variable in bash but i get an error:

```
[gex:~] $ mkdir somethingreallylongdirectoryname && cd $_
-bash: cd: _lp_runtime_before: No such file or directory
```

expected result (like without liquidprompt):

```
mbp:~ gex$ mkdir somethingreallylongdirectoryname && cd $_
mbp:somethingreallylongdirectoryname gex$
```

**Comment by dolmen** [comment]
The default value of `LP_ENABLE_RUNTIME` is 1 since e3e172606a84a2dd1f4747d7c18fb3231a351e90. It looks like I missed that when writing the 1.10 release notes.

The only solution I see is to explicitely disable the `RUNTIME` feature. Set `LP_ENABLE_RUNTIME=0` in your `liquidpromptrc`.

**Comment by varunturlapati** [comment]
Setting it to 0 or 1 doesn't seem to have any effect. `$_` is broken. Am I missing something else?

**Comment by Rodsevich** [comment]
Setting LP_ENABLE_RUNTIME=0 solved the issue for me. But what does RUNTIME does? What I'm loosing in exchange?
May you want to take a look here?
https://unix.stackexchange.com/questions/548630/bashs-var-not-expanding?noredirect=1#comment1018263_548630

**Comment by augmentedfourth** [comment]
`LP_ENABLE_RUNTIME` has the prompt report how long a command executes, if the execution time was longer (in seconds) than `LP_RUNTIME_THRESHOLD`.

**Comment by Rodsevich** [comment]
:cry: That's one of the greatest features. Isn't there anything that can be done to have the $_ var functional?

**Comment by Rycieos** [comment]
Not without serious changes to liquidprompt.

I'd call this a bug for sure. Let's leave this issue open as a bug, not a support ticket.

**Comment by Rycieos** [comment]
One of those times where I'm happy to say I was wrong: this turned out to be quite simple and is now fixed on master. Will be in the upcoming `v1.12`.
