### ISSUE TITLE
liquidprompt: LP_COLORMAP_x variables are deprecated. Update your theme to use LP_COLORMAP array.

### ISSUE THREAD

**Issue by crazy-canux** [nojhan/liquidprompt#452]
Operating system:  Ubuntu14.04
Liquid Prompt version (tag, commit):  dcc18d2454a57e0fb52722530d36b63a59a3efb6

**Comment by dolmen** [comment]
So, just fix your theme definition as requested.
If you don't know how to do that that's what you should ask.

**Comment by dolmen** [comment]
You closed the issue without telling why.
Did you solved your issue? Would you have appreciated more help?

**Comment by crazy-canux** [comment]
Do what promoted.
Modify the parameter.
Nothing else.
