### ISSUE TITLE
Can I install it with oh-my-zsh

### ISSUE THREAD

**Issue by crazy-canux** [nojhan/liquidprompt#454]
Shell: bash/zsh
Operating system: ubuntu
Liquid Prompt version (tag, commit):  last one.

**Comment by dolmen** [comment]
I had to guess what you are asking for. If you want to know if there is an [oh-my-zsh](/robbyrussell/oh-my-zsh) [plugin](/robbyrussell/oh-my-zsh/tree/master/plugins) to install Liquid Prompt, the answer is *no*. Liquid Prompt is just standalone and doesn't need oh-my-zsh.

**Comment by crazy-canux** [comment]
Ok, I got it.
Thx.
