### ISSUE TITLE
Error: "-bash: declare: -g: invalid option" on Centos

### ISSUE THREAD

**Issue by jpwgarrison** [nojhan/liquidprompt#474]
Shell: bash
Operating system: Centos 6.5
Liquid Prompt version (tag, commit): master

Apparently declare does not have the "-g" option in centos? I thought it was the bash version (4.1.2) so I upgraded to 4.4 and get the same option.

`man declare `shows `-aAfFilrtux` as the only options. 

I commented out the following line (1912) and the error goes away, FWIW:
`declare -g +x PROMPT_COMMAND`

**Comment by dolmen** [comment]
According to bash release notes, [`-g` was added in bash 4.2](http://git.savannah.gnu.org/cgit/bash.git/tree/NEWS?id=a0c0a00fc419b7bc08202a79134fcd5bc0427071#n428). I will disable the line on olders bash.

**Comment by dolmen** [comment]
Fixed by 18fd3fba035f080abc9d9e64b214dc48c81a6b3d
