### ISSUE TITLE
Shell inside Guake is detected as Telnet

### ISSUE THREAD

**Issue by tribut** [nojhan/liquidprompt#483]
Shell: bash
Operating system: Ubuntu 16.10
Liquid Prompt version (tag, commit): 9c1c8a3

It was already mentioned in https://github.com/nojhan/liquidprompt/issues/304, but somehow got lost. When a shell is started inside [Guake](http://guake-project.org/), it is wrongly detected as being a telnet session. The output from `who am i` looks like this:

    felix    pts/1        2016-11-09 10:24 (hostname)

Not sure if there is a generic way to solve this, but Guake sets `$GUAKE_TAB_UUID` which would be an easy way to detect this.

**Comment by tribut** [comment]
This might actually require a more fundamental solution. I seem to get the same behavior when I open a new `gnome-terminal` when no other gnome-terminal windows are already open. Further windows return an empty string for "who am i", so they do not have the problem.
I've removed telnet detection from my copy, maybe this is even the best way to go.

**Comment by dolmen** [comment]
I just tried to use Guake on Ubuntu 16.04, but it is completely unusable: it did not work at all before I launched guake-prefs, and once I did that I only got a 21x4 terminal window (maybe a HiDPI issue?). So Guake has severe issues, and I can only expect that the way it implements terminal emulation is flawed too.
Have you tried to knock at Guake's door?

**Comment by tribut** [comment]
Hm, never had the problems you describe with guake (on a HiDPI display).
Is returning the string above in some way incorrect? Tmux/Screen already have their special detection code so I was wondering if maybe telnet detection is simply not reliably possible this way.
If you had any documents I could cite when opening a bug against Guake, I would be grateful.

**Comment by dolmen** [comment]
Screen and Tmux do not have the special detection code you imply. They have code for counting sessions.

The only dirty terminal hack we have in Liquid Prompt is for `Apple_Terminal` and I don't intend to add more.

> If you had any documents I could cite when opening a bug against Guake, I would be grateful.

A full guide about programming TTY: http://www.linusakesson.net/programming/tty/
But I can't tell what part applies to you Guake issue.

**Comment by tribut** [comment]
I was referring to [liquidprompt:597](https://github.com/nojhan/liquidprompt/blob/3ca1a386511de6d63b93acafeacaa44b52d1224a/liquidprompt#L597).
Without this special treatment, tmux would be detected as telnet as well.

**Comment by dolmen** [comment]
You are right: both `screen` and `tmux` have a special treatment at that line.

**Comment by LaurentDumont** [comment]
Same issue in Debian Unstable. Starting a terminal window seems to work fine though.

**Comment by pcuinty** [comment]
same on Ubuntu 16.04

**Comment by saildata** [comment]
Still true in 2019 (Guake 3.4, liquidprompt 6f5af89)
