### ISSUE TITLE
default stash character (+) gets included in double-click highlight of branch

### ISSUE THREAD

**Issue by dogeared** [nojhan/liquidprompt#487]
Shell: bash
Operating system: OSX
Liquid Prompt version (tag, commit): 9c1c8a3

![stash](https://cloud.githubusercontent.com/assets/364562/20436752/564f3d30-ad7f-11e6-9ad9-1d710d117c58.png)

I propose changing the default to a character that is not automatically highlighted in this way, such as `:`

![stash2](https://cloud.githubusercontent.com/assets/364562/20436794/6efcc7e4-ad7f-11e6-8d3e-ea0e33b4db28.png)

**Comment by dolmen** [comment]
This is a major breaking change that will affect current users that just use the defaults. I can't accept it.

But anyone can change it in his/her own configuration.

And by the way, I personally think that this is more a bug in graphical terminal emulators: they should stop selection on attribute (color) change.
