### ISSUE TITLE
battery info does not display correctly on mac

### ISSUE THREAD

**Issue by dogeared** [nojhan/liquidprompt#489]
Shell: bash
Operating system: OSX El Capitan
Liquid Prompt version (tag, commit): 9c1c8a3

Displaying any battery information on mac seems to be broken altogether.

**Comment by jasmas** [comment]
I just tested #476 and it appears to fix this issue, but it must not yet be merged?

**Comment by augmentedfourth** [comment]
Can #476 be merged to fix this issue?

**Comment by dolmen** [comment]
Closing as the fix is in #476 (and verified by @dogeared in comment in #490)

**Comment by augmentedfourth** [comment]
The fix may be in #476, but that was requested over a year ago and never merged. Can that be merged ASAP, please?
