### ISSUE TITLE
Shell inside Tmux 2.3 is detected as Telnet

### ISSUE THREAD

**Issue by kianby** [nojhan/liquidprompt#492]
Shell: bash
Operating system: Debian Stretch
Liquid Prompt version (tag, commit): def86eba38703dd69e655a77ae610923e9a19051

'who am i' returns something new with TMUX 2.3: 

    johndoe   pts/3        2016-11-29 20:53 (tmux(2262).%0)

It is not yet managed by _lp_connection(). I put this workaround locally but there is probably a better code to write:

    _lp_connection()
    {
        if [[ -n "$SSH_CLIENT$SSH2_CLIENT$SSH_TTY" ]] ; then
            echo ssh
        else
            # TODO check on *BSD
            local sess_src="$(who am i | sed -n 's/.*(\(.*\))/\1/p')"
            local sess_tmux="$(who am i | sed -n 's/.*(\(tmux.*\))/\1/p')"
            local sess_parent="$(ps -o comm= -p $PPID 2> /dev/null)"
            if [[ -z "$sess_src" || "$sess_tmux" = "tmux"* || "$sess_src" = ":"* ]] ; then
                echo lcl  # Local
            elif [[ "$sess_parent" = "su" || "$sess_parent" = "sudo" ]] ; then
                echo su   # Remote su/sudo
            else
                echo tel  # Telnet
            fi
        fi
    }

**Comment by dolmen** [comment]
Looks like a duplicate of #304

**Comment by Rycieos** [comment]
Note that #304 is not the same issue: the fix for #304 created a new bug, which was reported in #407. This issue is a duplicate of #407.

This issue was reported before the fix of #407, in commit 119477c. If @kianby tries the latest from master, his problem might be fixed.

**Comment by kianby** [comment]
Validated on Manjaro
