### ISSUE TITLE
Macos installation

### ISSUE THREAD

**Issue by Mehran** [nojhan/liquidprompt#494]
Shell: bash
Operating system: Macos
im git clone last version , `source liquidprompt/liquidprompt` worked but how can i see battery usage and other ?  now i just see `[mehran:~] $` . 

what that mean ? is it run correct my mac ?

**Comment by dolmen** [comment]
Battery state is shown only if below a given threshold. See LP_BATTERY_THRESHOLD in ~/.liquidpromptrc.

**Comment by dolmen** [comment]
Your issue may also be related to #476.
