### ISSUE TITLE
CPU load scale is off on MacOS

### ISSUE THREAD

**Issue by alyssais** [nojhan/liquidprompt#499]
Shell: zsh
Operating system: macOS
Liquid Prompt version (tag, commit): 1.11

***

Often the CPU load percentage reported by liquidprompt is well over 100%. This means it won't be coloured by the gradient scale.

I've investigated a bit and found that liquidprompt uses `sysctl -n vm.loadavg` to find the current CPU usage, then it divides it by the number returned from `sysctl -n ncpu` (in my case this is 4) and multiplies by 100.

The values from `sysctl -n vm.loadavg` can be well over 400%, though. I've seen it as high as `10.88`. So, it looks like liquidprompt is using the wrong value as the upper bound (though I couldn't tell you what that should be).

**Comment by alyssais** [comment]
#455 would partially fix this because then the load would at least be coloured.

**Comment by dolmen** [comment]
The main issue is that loadavg is used with an incorrect expectation of a [0,1] range. See #391 where the bug was introduced.

**Comment by Rycieos** [comment]
The no colors problem has been fixed in a70e80f0f501031ef97ea8baf88ca6d7ef56ad8a.

I'm consolidating the discussion for the load scale being off on #530. Despite this issue being made first, the other has some suggested fixes already. Please continue the discussion there.
