### ISSUE TITLE
Root prompt seems to ignore a default mark

### ISSUE THREAD

**Issue by iainhallam** [nojhan/liquidprompt#501]
Shell: bash
Operating system: Debian Jessie
Liquid Prompt version: 1.11

I've been experimenting with LP as root, and tried to set a default mark as I would for a user account, which works fine, but as root I keep getting the # mark. I've set it in .config/liduidpromptrc, and can see the resulting variable in my environment:

set | grep ^LP_MARK_DEFAULT
LP_MARK_DEFAULT='>'

However:

set | grep ^LP_MARK=
LP_MARK=$'\\$\\[\E(B\E[m\\] '

Do I need to enable something extra as root to get the default mark to be respected?

**Comment by dolmen** [comment]
`.config/liduidpromptrc` is not the right file. But I suppose this is just a typo...

I just reproduced your issue. A fix is on the way...

**Comment by iainhallam** [comment]
Yes, that was a typo! Thanks for the fix; I've confirmed that it works on my copy.
