### ISSUE TITLE
grep -E not supported in SunOS

### ISSUE THREAD

**Issue by Rycieos** [nojhan/liquidprompt#504]
Shell: bash
Operating system: SunOS 11.3
Liquid Prompt version (tag, commit): master, 47126c7d973ee27fec0ee38296d70fa8bc9b1ab1

Liquidprompt uses grep -E in two places, [line 553](https://github.com/nojhan/liquidprompt/blob/47126c7d973ee27fec0ee38296d70fa8bc9b1ab1/liquidprompt#L553) for sudo version checking, and [line 895](https://github.com/nojhan/liquidprompt/blob/47126c7d973ee27fec0ee38296d70fa8bc9b1ab1/liquidprompt#L895) for git untracked files checking. SunOS, with it's old and feature lacking binaries, doesn't support the -E flag for grep. I only noticed this now as I was just now able to use git, hence the git problem. Even though the -q flag is passed, grep errors out each time the prompt is run in a git repo, which gets annoying fast.

Thankfully, the git one is easy to fix:
```grep -Eq '^\?\?'```
can be changed to
```grep -q '^\?\?'```
since the extended features aren't even used.

The sudo one is more complicated: 
```grep -qE '^Sudo version (1(\.([789]\.|[1-9][0-9])|[0-9])|[2-9])'```
If the -E flag was removed, every () and | would need a backslash before it. That would look ugly, and I don't use that feature, so I don't care either way.

**Comment by dolmen** [comment]
Fixed by merge of #508. Thanks Mark!
