### ISSUE TITLE
Show git tag in detached state

### ISSUE THREAD

**Issue by cburschka** [nojhan/liquidprompt#506]
Shell: bash/zsh
Operating system: Linux / MacOS
Liquid Prompt version (tag, commit): 47126c7 

Currently _lp_git_branch() shows a branch if possible, and otherwise falls back on a short commit hash.

It would be nice to see a tag, if one is available. `git describe --tags --exact-match` does exactly that - though the error needs to be suppressed if no tag exists. If that command returns an error, fall back on the commit hash.

**Comment by Rycieos** [comment]
[v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1) has a new function supporting this: [`_lp_vcs_tag()`](https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/functions/data/vcs.html#lp_vcs_tag). See the link for documentation.

The default theme now falls back to a tag if a branch is not found. See [`_lp_vcs_details_color()`](https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/functions/theme.html#lp_vcs_details_color) for details.

The details of the implementation are here:
https://github.com/nojhan/liquidprompt/blob/6e7f4c77044bea7ab92970e820997601926bcbea/liquidprompt#L1211-L1224

Thanks to @cburschka and @LlinksRechts for the implementations which helped me get this working.
