### ISSUE TITLE
Breaks oh-my-git

### ISSUE THREAD

**Issue by mfiano** [nojhan/liquidprompt#510]
I would like to use this, but it breaks oh-my-git. It's secondary prompt line is not displayed at all for paths containing a git repository if LP is sourced.

Shell: bash
Operating system: Arch Linux
Liquid Prompt version (tag, commit): 93df016

**Comment by Rycieos** [comment]
oh-my-git is a prompt just like liquidprompt. Neither of them claim to have compatibility with other dynamic prompts.

**Comment by dolmen** [comment]
I confirm what @Rycieos said.

The fix is easy: don't use oh-my-git if you use liquidprompt.
