### ISSUE TITLE
Why _lp_connection() doesn't check SSH_CONNECTION?

### ISSUE THREAD

**Issue by mathieumd** [nojhan/liquidprompt#513]
Shell: bash/bash
Operating system: Debian
Liquid Prompt version (tag, commit): develop, 93df016

When I connect to my machine through SSH, liquidprompt should display the hostname (as required by `LP_HOSTNAME_ALWAYS=0`), but it does not.

It seems that's caused by `_lp_connection()` which verify `${SSH_CLIENT-}${SSH2_CLIENT-}${SSH_TTY-}`_[1]_ but not `$SSH_CONNECTION`.

Is there a reason?

Of course, manually adding it solves this problem.

_[1]_ By the way, what's the meaning of the trailing `-`?

**Comment by Rycieos** [comment]
The meaning of the trailing `-` is part of [parameter substitution](http://www.tldp.org/LDP/abs/html/parameter-substitution.html). The meaning here is simply if the variable is null (not set), replace it with the empty string (`''`) without creating an error. Normally a shell would do that anyway, but if the shell has [set -u](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_25), then it would error.

I have a machine that doesn't set any of these SSH vars, and I manually set and export one of them before loading liquidprompt on that machine. Not an ideal solution, but it works just fine.

If there is widespread use of `$SSH_CONNECTION`, I would say that it is worth adding to the list of vars to check. A short search shows that whenever `$SSH_CONNECTION` is set, `$SSH_TTY` should be also, so I'm not sure what is happening in your case.

**Comment by mathieumd** [comment]
Thanks for you reply.

It seems to be because I use `tmux` as soon as I'm logged:
```
client$ ssh host
host$ set|grep ^SSH_
SSH_CLIENT='172.16.1.1 58802 22'
SSH_CONNECTION='172.16.1.1 58802 172.16.1.42 22'
SSH_TTY=/dev/pts/28

host$ tmux new-session
host(tmux)$ set|grep ^SSH_
SSH_CONNECTION='172.16.1.1 56998 172.16.1.42 22'
```

**Comment by Rycieos** [comment]
That looks like a bug in tmux. Why wouldn't it be keeping all enviroment vars?

While it would be possible to add the check for `$SSH_CONNECTION`, since the spec says that both that and `$SSH_TTY` should be set, I'm not sure we would be adding any value, except in this buggy situation.

**Comment by dolmen** [comment]
If I remember well, we can't rely on `$SSH_CONNECTION` because old versions of `sshd` do not set it.

**Comment by nojhan** [comment]
That should be explained in the "Known Limitations and Bugs" section of the README.

**Comment by Rycieos** [comment]
@mathieumd is this still a problem for you? I could add a check for `$SSH_CONNECTION` if there is a constant need for it.

**Comment by mathieumd** [comment]
@Rycieos I guess this issue could be closed. Thanks for the followup.
