### ISSUE TITLE
Recent change in `LP_MARK_UNTRACKED` behavior

### ISSUE THREAD

**Issue by alexprengere** [nojhan/liquidprompt#514]
e21a4c2 (PR #508 by @Rycieos) introduced a change in the prompt behavior.

The initial behavior was to add the `LP_MARK_UNTRACKED` only if a file is not tracked by git. After the commit, the mark will show also if a change is not committed. Reverting this commit fixes this for me.

**Comment by Rycieos** [comment]
This specific issue was reported and fixed in #509.

**Comment by alexprengere** [comment]
I was using `develop`, my bad. Indeed this is now fixed on `master`.
