### ISSUE TITLE
changes in git not detected if root contains file named HEAD

### ISSUE THREAD

**Issue by dpinol** [nojhan/liquidprompt#517]
Shell: bash
Operating system: OSX 10.12.4 
Liquid Prompt version (tag, commit): 1.11

when there are git changes on a git checkout whose root contains a file named HEAD, the prompt does not display them (remains in green).

Problem is with line 929
`        shortstat="$(LC_ALL=C \git diff --shortstat HEAD 2>/dev/null)" 
`
This is because git does not know if we refer to the HEAD file or the HEAD revision
```
master* ± git diff --shortstat HEAD
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]
```

I suggest this patch
`        shortstat="$(LC_ALL=C \git diff --shortstat HEAD -- 2>/dev/null)" 
`

**Comment by Rycieos** [comment]
liquidprompt 1.11 is 25 commits behind master. You should update and try to reproduce.

I have the same version of git, and cannot reproduce this problem.

Note that the original line is a diff between the working directory and the HEAD commit. Your amended line is a diff between the working directory and the staging area. There should be no change in behavior between different git versions.

**Comment by dpinol** [comment]
@Rycieos thank you your you prompt :-) answer. You're completely right, I rewrote the issue. The problem is that I had a file named HEAD.

**Comment by Rycieos** [comment]
An interesting issue. Not strictly relevant, but why do you have a file named "HEAD"?

There very well might be many more locations where this could be a problem. Anywhere that a HEAD, master, or origin is referenced might break in a similar way. Maybe it's worth it to evaluate other such possible problem locations?
