### ISSUE TITLE
LP_PS1_POSTFIX="\n>" is too literal in zsh

### ISSUE THREAD

**Issue by krux02** [nojhan/liquidprompt#518]
Shell: zsh
Operating system: arch linux
Liquid Prompt version: yaourt git version of date of writing this issue

I did this setting, and it is my only setting:
```
LP_PS1_POSTFIX="\n>"
```
now my prompt looks like this:
```
⏚ θ72° [arne:~/proj/nim/fancygl/examples] master(+84/-48)* ± \n>
```
not what I expected, I expected more something like this:
```
⏚ θ72° [arne:~/proj/nim/fancygl/examples] master(+84/-48)* ± 
>
```
That is by the way also how it looks like in bash.

**Comment by dolmen** [comment]
Try this to get a literal line feed:
```
LP_PS1_POSTFIX='
'
```

**Comment by krux02** [comment]
Not shure if the tag `question` and an answer solves this issue. Setting ``LP_PS1_POSTFIX="\n>"`` is an explicit part of the tutorial, and there is no mentioning at all that it only works on bash, not zsh. But the answer does work, so thank you.
