### ISSUE TITLE
a simple powerline support

### ISSUE THREAD

**Issue by dreamcat4** [nojhan/liquidprompt#520]
Shell: bash
Operating system: ubuntu linux / gnome3 / solarized light theme
Liquid Prompt version (tag, commit): latest

Hi there,
I noticed there was some other generic powerline PS1 prompt... with fewer features (than this liquidprompt). However it has a powerline support, which is not requiring python, or any troublesome fonts install.

https://github.com/riobard/bash-powerline

So maybe, a similar approach may be helpful for this project. If you are interested?
Kind Regards

**Comment by nojhan** [comment]
This is just using unicode characters and color scheme, which liquidprompt
already do.
You just have to custom your own theme to do that.
Feel free to propose yours.

This is far from being close to Powerline-like, as it lacks those special
characters that allow to have chevron-shapped limits between fields.
But anyway, a liquidprompt theme using Powerline fonts would also be
interesting.

**Comment by dreamcat4** [comment]
Ak okay i see... this has already been discussed #359 and #486. Many thanks for replying / clarifying this.

**Comment by jblaine** [comment]
@dreamcat4 Please close this issue. I would but I can't.

**Comment by nojhan** [comment]
Done.

**Comment by Rycieos** [comment]
[v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1) has a two new included themes based off of Powerline: https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/theme/included/powerline.html

And if they do not meet your needs, the [improved theme engine makes creating custom themes much easier](https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/theme/custom.html).
