### ISSUE TITLE
Bash version detection fails for non-numeric minor versions (e.g. bash 3.05b.*)

### ISSUE THREAD

**Issue by flopp** [nojhan/liquidprompt#522]
Shell: bash 3.05b.*
Operating system: any
Liquid Prompt version (tag, commit): master, 9c80396021a8106bfaeade9a1ea51b85152e951d

The initial bash version detection fails for BASH_VERSIONs with a minor version containing a non-numeric suffix, e.g. `BASH_VERSION="3.05b.0(1)-release"`.
Such a BASH_VERSION results in a bash error:
```
-bash: 05b: value too great for base (error token is "05b")
```

Stripping a non-numeric suffix from `bminor` in `liquidprompt` resolves the issue.

**Comment by Rycieos** [comment]
A fix for this is now in master as 0234a581d023fb6c40e5339f6dcbd619a33b4553 and in [v1.12-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v1.12-beta.1).

Your fix proposed in #523 that was merged into develop was not merged into master. While testing that fix, I discovered `$BASH_VERSINFO[@]`, which offers a more stable way to check versions.
