### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by DamienCassou** [nojhan/liquidprompt#526]
The previous release is more than a year old. What about releasing current master?

**Comment by aborrero** [comment]
+1

**Comment by aborrero** [comment]
ping?

**Comment by Rycieos** [comment]
I have a release candidate out now if anyone is interested in testing: [v1.12-rc.1](https://github.com/nojhan/liquidprompt/releases/tag/v1.12-rc.1).

**Comment by Rycieos** [comment]
I just released [v1.12.0](https://github.com/nojhan/liquidprompt/releases/tag/v1.12.0).

**Comment by augmentedfourth** [comment]
Home-brew PR for this release: https://github.com/Homebrew/homebrew-core/pull/58139
