### ISSUE TITLE
Allow background colours

### ISSUE THREAD

**Issue by phunni** [nojhan/liquidprompt#528]
Shell: bash
Operating system: Linux (Arch)
Liquid Prompt version (tag, commit): 1.11

I'd like to be able to tweak the background colour of my username and hostname - a bit like this user has for their bash shell  [here](http://i.imgur.com/YngKVae.png?1)

**Comment by Rycieos** [comment]
Your link is dead (links back to this issue).

**Comment by phunni** [comment]
Apologies - I'm trying to link to http://i.imgur.com/YngKVae.png?1 Maybe be getting the markdown wrong...

**Comment by Rycieos** [comment]
It's actually really simple, and you don't need to use a theme, it works right in a .ps1 file.

Set your .ps1 file in your rc file, then you can add backgrounds to the PS1.

```
BG="\[$(tput setab 245)\]"
...
LP_PS1="${LP_PS1}${LP_BRACKET_OPEN}${BG}${LP_USER}${NO_COL}${LP_HOST}${LP_PERM}"
```
Note the `$BG` and `$NO_COL` surrounding `$LP_USER`. This will add a background color to the user string.

If you want to change the colors without messing with the .ps1 file, you will need to figure out themes.

**Comment by phunni** [comment]
Works beautifully - thanks!

**Comment by phunni** [comment]
Except for the host... Surrounding $LP_HOST with $BG & $NO_COL colours the "@"...

**Comment by Rycieos** [comment]
You might have to get a little hacky.

The easy way would be to strip the `@` off, by doing `${LP_HOST:1}`, then add the `@` back on before the background color. Otherwise, customizing how the `$LP_HOST` is put together might take messing with the rc and/or theme files.

**Comment by phunni** [comment]
thanks for the reply - sorry to be a pain, but is there any chance you could give me an example of how that line would now look in the .ps1 file?

**Comment by Rycieos** [comment]
Hm, I was spit balling there, I guess that wouldn't work quite as well as expected.

It is grouped into one so that when the hostname shouldn't show up, the separator (`@`) won't show up either, so hacking it will break that. Also, since the color codes are part of the mark, doing a substring isn't exactly the right way to do it. Probably themes are the right way, I'll see if I can get something to work.

**Comment by Rycieos** [comment]
I'm doing this in a theme file, but it is doing the mark (`@`) colored as well:

```
BG1="\[$(tput setab 160)\]"
# Current user
LP_COLOR_USER_LOGGED="$BG1"           # user who logged in
LP_COLOR_USER_ALT="$BG1$BOLD"         # user but not the one who logged in
LP_COLOR_USER_ROOT="$BG1$BOLD_YELLOW" # root

BG2="\[$(tput setab 184)\]"
# Hostname
LP_COLOR_HOST="$BG2"            # local host
LP_COLOR_SSH="$BG2$BLUE"        # connected via SSH
LP_COLOR_SU="$BG2$BOLD_YELLOW"  # connected remotely but in new environment through su/sudo
LP_COLOR_TELNET="$BG2$WARN_RED" # connected via telnet
LP_COLOR_X11_ON="$BG2$GREEN"    # connected with X11 support
LP_COLOR_X11_OFF="$BG2$YELLOW"  # connected without X11 support
```

I'm not sure if this is a limitation of liquidprompt themes, or if I am doing something incorrectly. I would assume that since the mark and the hostname can have different colors, there is a way to give only the hostname a background.

However, glancing through the source, I can't figure out where the `@` is being added to the `$LP_HOST` string.

**Comment by Rycieos** [comment]
Found it, it hides.
https://github.com/nojhan/liquidprompt/blob/9c80396021a8106bfaeade9a1ea51b85152e951d/liquidprompt#L629

Omiting the `$BG2` on the X11 lines fixes the problem, since the `@` is colors by those lines. You could add a different BG color to those vars to color the `@` differently.

**Comment by phunni** [comment]
thanks - I'll give that a go

**Comment by phunni** [comment]
that seems to work beautifully - I just got to pick some better colours ;-)

**Comment by phunni** [comment]
Since we're now in theme land - is there any way to figure out the numerical values of the existing colours so that I can mix and match text and background colours?

**Comment by Rycieos** [comment]
This stackexchange answer is what I use.
https://unix.stackexchange.com/a/269085

**Comment by nojhan** [comment]
There is now a powerline-like theme, with an easy to use background-color support, check powernerd.ps1 and powernerd.theme on develop.
