### ISSUE TITLE
LP_ENABLE_SHORTEN_PATH=1 messes up readline when SSHed into macOS Sierra

### ISSUE THREAD

**Issue by augmentedfourth** [nojhan/liquidprompt#529]
Shell: bash
Operating system: macOS Sierra
Liquid Prompt version (tag, commit): 1.11; 'master' branch on 2016-08-18 (though it's been like this for a while on both 1.11 and HEAD)

If I have LP_ENABLE_SHORTEN_PATH turned on, and I'm logged in over SSH from a macOS machine into another macOS machine, then I type a command line that extends onto the next line of the terminal, instead the new characters start overwriting the beginning of the current line rather than wrap onto a new line.

This is only when I'm logged in over SSH, and only when I'm from macOS Sierra TO macOS Sierra. I can't test any earlier versions of macOS or OS X, it doesn't happen when I SSH into a Debian system, and it doesn't happen locally on my Mac. Very oddly, I also just discovered that if I log in from a Debian server into my macOS server, readline works as expected. So it's only when SSHed from my macOS laptop directly into my macOS server.

**Comment by Rycieos** [comment]
Tag 1.11 is very out of date, the latest commit is 9c80396021a8106bfaeade9a1ea51b85152e951d from 2017-04-04. Please try to reproduce the bug on latest master.

This sounds a lot like some of our other issues with line wrapping, but I won't link them unless this is confirmed an issue.

If you still have the issue after updating, can you post the output of
```
echo "$PS1" | od -c
locale
```

**Comment by augmentedfourth** [comment]
I'm sorry; I meant 2017-08-18. I just pulled `9c80396` and it's still functioning in exactly the way described above.

**Comment by augmentedfourth** [comment]
Also, looked at the output of those commands. Oddly, my macOS server has the locale set to "C" when I SSH in directly from my Mac, but "en_US.UTF-8" when I log in from a Linux machine.

My local Mac has the locale set to "en_US.UTF-8" as well. I'm not sure how this got in this state, but when I set the LANG/LC variables to "en_US.UTF-8" on the server, the line wrapping seems to work fine even when the path in the prompt is shortened.

Do you know what the usual/best-practice method is for setting the locale on a Mac? If not I'll do mor research on my own; it seems like this is the problem. Thanks for pointing me in the right direction.

**Comment by augmentedfourth** [comment]
Aha. My Linux server had `SendEnv LANG LC_*` in /etc/ssh/ssh_config, and my Mac server has `AcceptEnv LANG LC_*` in /etc/ssh/sshd_config. My local Mac terminal had a "set locale variables automatically" setting enabled, but the ssh client wasn't configured to send them.

I put these in the `~/.bash_profile` on my macOS server, and all is working as desired now.
```export LANG="en_US.UTF-8"
export LC_ALL="$LANG"```
