### ISSUE TITLE
Better screenshot...

### ISSUE THREAD

**Issue by oldgaro** [nojhan/liquidprompt#537]
Shell: bash/zsh
Operating system:  ArchLinux
Liquid Prompt version (tag, commit):  master

Not complaining at all, but I avoid installing liquidprompt twice cause of that confusing and ugly screenshot...

Would be great a new one? haha.

wonderful project...

**Comment by Rycieos** [comment]
Could you describe what you don't like about the current screenshot, or suggest what you would like in it?

I agree that it is quite cluttered, but it does show off the majority of the available features.

**Comment by oldgaro** [comment]
Nah, just ignore! haha
