### ISSUE TITLE
Use hashvis to represent git hashes

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#538]
hashvis will parse hashes from standard input and visualize them as blocks of color in a xterm-16color (or better, supports UTF-8): https://github.com/boredzo/hashvis

**Comment by Rycieos** [comment]
Cool project and concept, but I see some issues:
1. How would we display this in the prompt? The outputs are huge, and don't fit in a line.
2. Why? Rarely do people need to see the git commit hash on the prompt line, so in what case would adding this be useful? When there isn't a matching branch or tag? That is rare.
3. I'm color blind. Not completely black and white vision, but this color block isn't easy for me to skim like the docs claim. I know I won't find use in this, and I'm sure there are others too.

As usual, I'm open to others implementing this feature, but I won't be.
