### ISSUE TITLE
LP_PWD and LP_PS1

### ISSUE THREAD

**Issue by esby** [nojhan/liquidprompt#539]
Shell: bash
Operating system: Debian 9.3
Liquid Prompt version (tag, commit): v_1.9-250-g9c80396

I don't know is this a bug or not, but I can't get the (current) path to be displayed with LP_PS1 by using ${LP_PWD} or ${pwd} (as taken from the examples).

It will output the path the LP_PS1 variable was defined and will not change when the user changes the path in the terminal...

eg:
```

export LP_PS1=`echo -ne "[\${LP_USER}\${LP_HOST}: \$(pwd) ] \${LP_GIT} \\\$ "`
```
will output:
```
[esby: /home/esby ]  $ pwd
/home/esby
[esby: /home/esby ]  $ cd liquidprompt/
[esby: /home/esby ]  $ pwd
/home/esby/liquidprompt
```

Is this intented?

**Comment by esby** [comment]
As I wrote, it is according the the documentation and the example.

I am directly testing it via an export in a bash shell.

I don't see how using simple quotes will help here, since the the variables will not be interpretated.

Also, using \${LP_PWD} does not give any results.

the only way to correct it I see to correct it is to create an alias for cd command that changes the LP_PS1 each time a cd is performed...

**Comment by Rycieos** [comment]
My apologizes, you are setting `LP_PS1` like in the docs.

What do you see when echoing `$LP_PS1`?
What do you see when echoing `$PROMPT_COMMAND`?

Are you setting `LP_PS1` in a `*.ps1` file, or in `.bashrc` or similar?

I realize this issue is old, but does this behavior still happen with the latest version?

**Comment by esby** [comment]
I am using the last git version.
As I said, I am/was setting it manually. 
Is this not supposed to work manually and then works when setted in scripts ?

I just checked if I set it via LP_PS1 and it works.
If I set it via .bashrc or manually it will fail.

Maybe the documentation could be more explicit here:

mkdir -p ~/.config/liquidprompt/
cd ~/liquidprompt
cp liquid.ps1  ~/.config/liquidprompt/liquid.ps1
uncommented the LP_PS1_FILE line, and set it to the file you have created.
echo 'LP_PS1_FILE=~/.config/liquidprompt/liquid.ps1' >>

then edit ~/.config/liquidprompt/liquid.ps1' to your needs.
(so your config does not get overwritten if you edit / flush your installation of liquidprompt)


I guess this can be toggled to 'solved'.

For your questions:

cd ~/liquidprompt
export LP_PS1=`echo -ne "[\${LP_USER}\${LP_HOST}: \$(pwd) ] \${LP_GIT} \\\$ "`
echo $LP_PS1
[\u\[\]\[\]@\[\]\h\[\]: /home/<user>/liquidprompt ] $

export LP_PS1=`echo -ne "[\${LP_USER}\${LP_HOST}: \${LP_PWD} ] \${LP_GIT} \\\$ "`
echo $LP_PS1
[\u\[\]\[\]@\[\]\h\[\]: \[\]~/liquidprompt\[\] ] $

(same issue, except it show '~/liquidprompt')

echo $PROMPT_COMMAND
_lp_set_prompt

**Comment by Rycieos** [comment]
I agree that the documentation is confusing there, it should be clarified by someone who understands the `LP_PS1` section of code.

I would have assumed that setting it in `.bashrc` would have worked, but if not, maybe using a `*.ps1` config file is the only way that works.
