### ISSUE TITLE
Conf-flag to separate status-line and prompt-char with newline

### ISSUE THREAD

**Issue by ozra** [nojhan/liquidprompt#541]
Shell: bash
Operating system: [edit:] Ubuntu 17.10
Liquid Prompt version (tag, commit): v_1.11, 9c80396021a8106bfaeade9a1ea51b85152e951d

This is literally the first thing I thought when I used it. How do I turn on newline, so that the prompt-info is on one line, and the beginning of entry is on the next line. 

I often work with three columns of terminals, editors, you name it. As such I have about 80 chars worth of columnar space (just a bit over the average of what is optimal line length for human beings according to studies). This gives very little space for long prompts making one write everything wrapped over two lines in practice.

Separating over two lines, give a good division of actions in the history, and allows a very full status line.

So, see it like that. A "status line", and then the actual "prompt", which is just the one last char, on a new line.

**Comment by Rycieos** [comment]
There are multiple ways to achive this already. The simplest would be to add a [postfix](https://github.com/nojhan/liquidprompt#adding-a-prefixpostfix), by setting `LP_PS1_POSTFIX="\n"` or something similar. However, this wouldn't have the `$` on the new line, so if that doesn't fit the bill...

You can setup your own [PS1 file](https://github.com/nojhan/liquidprompt#rearranging-the-prompt), copying the default file, and just adding a `\n` in the spot that you want it. For example, I made the 39th line look like this:
```
LP_PS1="${LP_PS1}${LP_RUNTIME}${LP_ERR}${LP_MARK_PREFIX}\n${LP_MARK}${LP_PS1_POSTFIX}"
```

Which gave me a prompt that looks like this:
```
2d/1& [rycieos@jaguar:~]
$
```

**Comment by ozra** [comment]
Thanks for the hints! I ended up hacking the main file, since there was a horde of things I wanted in different ways. Only thing I haven't figured out is how to strip composited strings of escape-codes to measure they're "visible lengths", I'm trying to accomplish justification of a "left" (user/host/path) and "right"-justified (all variable things, like git-branch, etc.) part of the status line. Bash gave me a headache and I gave up there XD. Anyway, I'll close this.

**Comment by nojhan** [comment]
For the records: you can set LP_PS1 in the configuration file, there is no need to edit the main code file (have a look at `*.theme` files). To set up left-aligned prompt, you will have to use some special escaped characters and build your own LP_PS1.
To have a string stripped of escape code, you can use the `_lp_as_text` function, that do just that (it is used to set up the title of the terminal window).
