### ISSUE TITLE
Disabling pink error code

### ISSUE THREAD

**Issue by atsaloli** [nojhan/liquidprompt#543]
Shell: bash
Operating system: RHEL 6
Liquid Prompt version (tag, commit): 9c80396 (2017-04-04)

Is there any way to disable the pink reporting of the exit status code of the last command when non-zero?

I looked in the config file and in the `liquid.ps1` file but I didn't see anything... did I miss it, or where is it?

Thanks! Love the product.  =)

**Comment by Rycieos** [comment]
You would have to use a [theme](https://github.com/nojhan/liquidprompt#themes) to change default colors. If you copy the default theme file, the line you are looking for is the [LP_COLOR_ERR](https://github.com/nojhan/liquidprompt/blob/9c80396021a8106bfaeade9a1ea51b85152e951d/liquid.theme#L73).

**Comment by augmentedfourth** [comment]
@atsaloli If you want to get rid of the whole thing, you can comment out lines 1702-1707 in the main liquidprompt script. Even better, put a conditional around those lines and add a config parameter to turn it on/off, then send in a pull request. 😉

**Comment by atsaloli** [comment]
Thanks, @augmentedfourth! It's a small world! =)  

And thanks @Rycieos!  =)

**Comment by augmentedfourth** [comment]
@nojhan Was that added in another pull request? #544 was closed without merging due to @Rycieos stating that we shouldn't be adding new parameters like `LP_ENABLE_ERR`. The official solution was to take `${LP_ERR}` out of the theme file rather than add the new `.liquidpromptrc` option.

**Comment by nojhan** [comment]
I was unaware of this discussion, I added the feature without a PR (I'm not even sure I can do a PR toward my own repo?). To avoid such mistake, this kind of thought should definitely be written down as comment in the code, we cannot expect contributors to read all closed PRs.
Additionally, if the config flags number is a problem, maybe it would be better to remove them entirely in favour of a cleaner LP_PS1_FILE system?

**Comment by Rycieos** [comment]
@nojhan you can do a PR against your own repo; the benefit being other contributors can read and give suggestions before merging.

I agree that it would be better to have some sort of modular configuration system, where instead of checking configuration variables, each construction function was called only if it was wanted.

**Comment by Rycieos** [comment]
This is fixed in [v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1), which has a new config option: [`$LP_ENABLE_ERROR`](https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/config.html#LP_ENABLE_ERROR). See the link for documentation.
