### ISSUE TITLE
Extra @ at beginning of prompt: what is it?

### ISSUE THREAD

**Issue by mathomp4** [nojhan/liquidprompt#553]
Shell: bash
Operating system: SLES12 SP3
Liquid Prompt version (tag, commit): master as of 2018-Aug-07 morning

All, this might be a simple thing, but it's baffling to me. I've enabled liquidprompt on a MacBook as well as on a CentOS 7 box and both worked well. The prompt is what I expect.

But, on a SLES12 machine I'm moving to liquidprompt, my prompt looks like:

`@04:50:56 [mathomp4@pfe22:~] $ `

I have *no* idea where that `@` is coming from. I've scrubbed my `.bashrc`, my `.bash_profile` just sources `.bashrc`, I don't have a `.profile`. 

If I issue, say `prompt_tag yaya` I then get:

`@yaya 04:54:33 [mathomp4@pfe22:~] $ `

I'm just stumped. Is this some feature of liquidprompt I don't know about?

**Comment by mathomp4** [comment]
Additional details:

I also have in my `.bashrc`: 
`   LP_PS1_PREFIX="\[\e]0;\u@\h: \w\a\]"`
in order to set the terminal title, but even if I comment this out, the `@` is still there.

**Comment by Rycieos** [comment]
Can you post your output of the `env` command?

**Comment by mathomp4** [comment]
@Rycieos I figured it out. It was a 'fun with dotfiles' collision. Somehow:
`set show-mode-in-prompt on`
got into my `.inputrc` so it was showing me I had emacs bindings on. Grr.

Sorry for being dumb.
