### ISSUE TITLE
Homebrew package installation question

### ISSUE THREAD

**Issue by augmentedfourth** [nojhan/liquidprompt#555]
Conversation on #554 has diverged from the original issue. I'll fork the unrelated conversation here so that issue can return to the original topic. (tl;dr: how can I help in producing a new release? Is there anything?)

From myself (@augmentedfourth) in that thread:
> Note that I've now got an open pull request with homebrew to add the `master` branch as a `--devel` target in between the `--HEAD` (on liquidprompt's `devel` branch) and the official release tarball.
>
> Homebrew/homebrew-core#31302

Then, again from me (@augmentedfourth):
> So apparently they rejected that PR with the following reason:
>
>> Homebrew/homebrew-core#31302 (comment)
>> `devel` is for versions that are tagged, but have pre-release status. In short, `devel` does not follow a moving target (like `head` does) but is only used to test inside Homebrew upcoming versions, that will be released soon.
>
> Currently, installing via Homebrew on macOS is either old (the 1.11 release) or broken (the develop issue discussed here). I can stay on `master` with a one-off non-packaged install, but I'd rather not do that.

@Rycieos responded:
> Maybe the `devel` version should follow `master` instead? It depends on how @nojhan is planning on doing branches in the future.
>
> On that note, it's been time for a long time for a new official release.

New comments in this issue:

The point of the `HEAD` version in homebrew is to get the latest un-tested code, so it makes sense to point at `develop`. I tried to get them to point the `devel` installation target at `master`, but they want a defined pre-release rather than to point at a moving branch tip.

I might be able to get them to take the current `master` SHA1 as the `devel` target, but it would be easier to just release 1.12 at the current state of `master`. Is there a process doc for that? Can I help in any way?

**Comment by dolmen** [comment]
To make a new release some help would be welcome on checking the state of the CHANGES file. I'm not sure it reflects all the changes since the last release, so if you want to contribute that...

**Comment by augmentedfourth** [comment]
In #554, I said:
> It seems, in order to get the current master status back into Homebrew, liquidprompt should either prepare a new official release (discussed a bit in #555) or perhaps attempt to re-do the Homebrew pull request to point the devel installation at the specific commit hash currently at the tip of master rather than a moving target.

Which path should liquidprompt pursue? @dolmen? Given that Homebrew's intention is for `develop` targets to be a test version that will be "released soon", it seems that a new release is in order in the near-ish future either way, and preparing a new release would save us the trouble of trying to figure out what the pre-release version should be called (https://github.com/nojhan/liquidprompt/issues/555#issuecomment-416000072).

I would really like to have time to prepare/edit the CHANGES file, and I'll work on that if I can, but unfortunately I just don't have the ability to contribute to open-source projects very much right now (note that it's been a couple of months since I even found a moment to comment on these issues).

**Comment by augmentedfourth** [comment]
@GaryBoone ^^

**Comment by Rycieos** [comment]
@augmentedfourth time to resurrect this.

1. I am fast approaching a v1.12 release. I hope to get a v1.12-rc.1 out soon.
2. I want to get rid of the `develop` branch, since it breaks some stuff and doesn't reflect how I'm developing this project.

What needs to be done with Homebrew to make this happen? Is there a release pointing at the `develop` branch right now?
Can we get them to point a release at master, or do I need to push a v1.12-rc.1 tag out first?

**Comment by augmentedfourth** [comment]
@Rycieos The `HEAD` Homebrew "moving target" release currently points to the `develop` branch. And the 1.11 "main" release points directly to https://github.com/nojhan/liquidprompt/archive/v_1.11.tar.gz.

I can send Hombrew a PR to change the "moving target" release to `master`. Additionally, they can provide a `devel` installation, for things like testing/QA/UAT builds. If you push out a release candidate tag as suggested, I can add that to the formula as a `devel` target at the same time.

**Comment by Rycieos** [comment]
That would be great! Please do so. Let me know when that is merged and it is safe to delete the `develop` branch.

I'll update this thread when I have a `v1.12-rc.1` release ready.

**Comment by augmentedfourth** [comment]
@Rycieos Apparently Homebrew won't accept test/beta/QA versions anymore. They changed their spec to all installing different/multiple versions of things, but the only unstable build they'll allow now is `HEAD`: https://docs.brew.sh/Versions

I've submitted this PR to change the liquid prompt HEAD to use branch `master`: https://github.com/Homebrew/homebrew-core/pull/57166
It installs fine and I'm currently running 869d4ab locally.

**Comment by Rycieos** [comment]
So if I'm reading their spec right, they only want a `HEAD` and major.minor versions? I don't know about supporting older versions than the latest stable, but I guess if people want to install or keep their older version then that's fine.

So when I cut 1.12, we really need to make another PR to say
```diff
-  url "https://github.com/nojhan/liquidprompt/archive/v_1.11.tar.gz"
+  url "https://github.com/nojhan/liquidprompt/archive/v1.12.tar.gz"
```
? That seems frustrating.

**Comment by augmentedfourth** [comment]
Yep. But they've got a ton of automation around the accepting of formula revisions, though. That's a pretty standard PR for the project, and 99% of the work is done in CI.

I don't intend to create a separate `liquidprompt@1.11` formula after 1.12 becomes stable. That's just silly.

**Comment by augmentedfourth** [comment]
https://github.com/Homebrew/homebrew-core/pull/57166 is merged to change the branch for HEAD installations.

**Comment by Rycieos** [comment]
Hopefully this means we will get more testers of the latest fixes. I know there was a few bugs on the `develop` branch too, so this is good.

**Comment by augmentedfourth** [comment]
Now that 1.12rc1 is out, testers should install it with:
`brew unlink liquidprompt && brew install --HEAD liquidprompt`

You can update the HEAD installation to the latest `master` commit with:
`brew upgrade --fetch-HEAD liquidprompt`

To return to the release build, once 1.12 is fully out and committed in homebrew:
`brew unlink liquidprompt && brew install liquidprompt`

**Comment by augmentedfourth** [comment]
Apparently you can also switch/link versions with something like `brew switch liquidprompt HEAD-4a9169e` if you have multiple versions currently installed.
