### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by imsky** [nojhan/liquidprompt#559]
It'd be great to see the current Kubernetes config context. It's most helpful as a persistent display, so it should probably be off by default. Also, since context names can become quite long, the display should probably be truncated.

Shell: bash
Operating system: macOS 10.12.6
Liquid Prompt version (tag, commit): eda83efe4e0044f880370ed5e92aa7e3fdbef971

**Comment by Rycieos** [comment]
I merged @mschuett's commit 0660342 in #578, which implements exactly what is described here. Will be part of the v2.1 release.
