### ISSUE TITLE
${return_code} on terminal with zsh

### ISSUE THREAD

**Issue by kj96** [nojhan/liquidprompt#560]
Shell: bash/zsh
Operating system: Manjaro
Liquid Prompt version (tag, commit): 
![image](https://user-images.githubusercontent.com/17710098/49916440-da090400-fec0-11e8-9703-42f300d83296.png)

Its showing `${return_code}` where it used to display emojis.

**Comment by kj96** [comment]
Working Fine now after changing the theme from `re5et` to `liquidprompt`

**Comment by kj96** [comment]
Working Fine now after changing the theme from `re5et` to `liquidprompt` in .zshrc

**Comment by kj96** [comment]
I have removed` oh-my-zsh` from my **`.zshrc`**, it is still the same

**Comment by kj96** [comment]
I have removed` oh-my-zsh` from my **`.zshrc`** and rebooted, it is fine now +1:

**Comment by Rycieos** [comment]
If your issue is resolved, please close this issue.

For others that find this, liquidprompt is not compatible with other prompts like oh-my-zsh.

**Comment by jeromescuggs** [comment]
> If your issue is resolved, please close this issue.
> 
> For others that find this, liquidprompt is not compatible with other prompts like oh-my-zsh.

hello, 
i've only recently encountered this issue despite using both OMZ and liquidprompt for quite some time, and after playing around a bit i found that calling for liquidprompt *before* sourcing OMZ seems to fix the issue (though it seems like i am now getting two return codes per line, but that's a bit more tolerable than either removing OMZ or dealing with the #{return_code} eyesore)

adding the code to source liquidprompt in where one would normally source the OMZ prompt is both convenient for keeping zshrc organized as well as fixing this issue
![wPBp8zt](https://user-images.githubusercontent.com/43969717/57986594-673a2100-7a3c-11e9-823f-dc9406f4800d.png)
