### ISSUE TITLE
tmux session not always have $TERM set to screen

### ISSUE THREAD

**Issue by liujoey** [nojhan/liquidprompt#563]
https://github.com/nojhan/liquidprompt/blob/6f5af893a3aba29d54005366ba88c3b10c72bcb6/liquidprompt#L584

I feel this line is not covering all cases. I set $TERM=tmux-256color when using TMUX and generate my own terminfo for it. Is there a better way to detect whether it is running inside a multiplexer?

**Comment by dolmen** [comment]
You're right. Checking `$TMUX` would be helpful here like I do in [angel-PS1](https://github.com/dolmen/angel-PS1/blob/devel/lib/AngelPS1/Plugin/Term/tmux.pm).

**Comment by Rycieos** [comment]
Fixed on master and in [v1.12-rc.1](https://github.com/nojhan/liquidprompt/releases/tag/v1.12-rc.1).
