### ISSUE TITLE
misspelling variable name

### ISSUE THREAD

**Issue by liujoey** [nojhan/liquidprompt#564]
https://github.com/nojhan/liquidprompt/blob/eda83efe4e0044f880370ed5e92aa7e3fdbef971/liquidprompt#L487

typeset _LP_ENABLE_DETACHED_SESSION here, but used _LP_ENABLE_DETACHED_SESSIONS elsewhere.

And typeset should have -x option, otherwise the _LP_ENABLE_SCREEN and _LP_ENABLE_TMUX value is not visible in function _lp_jobcount_color(). At least on my Mac OS Mojave, i have to add -x to the typeset to make this function work.

**Comment by dolmen** [comment]
Thanks for the catch! Fixed.
