### ISSUE TITLE
Conflict with zsh theme agnoster

### ISSUE THREAD

**Issue by kmahyyg** [nojhan/liquidprompt#566]
Shell: zsh
Operating system: Arch Linux
Liquid Prompt version (tag, commit): https://github.com/nojhan/liquidprompt/commit/eda83efe4e0044f880370ed5e92aa7e3fdbef971

After `source` the liquidprompt:

```
⌁27% [kmahyyg:~] %                                                                                                                       $RPROMPT_PREFIX$(build_right_prompt)$reset_color$RPROMPT_SUFFIX
```

**Comment by Rycieos** [comment]
liquidprompt does not work with other prompts or themes as they will conflict. See 510 for a similar situation.
