### ISSUE TITLE
The error code isn't added to prompt even when an error occurs

### ISSUE THREAD

**Issue by kapad** [nojhan/liquidprompt#568]
Shell: bash
Operating system: Ubuntu
Liquid Prompt version (tag, commit): master, eda83efe4e0044f880370ed5e92aa7e3fdbef971

I just updated and tested this again before creating the issue. Where more information can I add to this issue? And where can I find this information?

**Comment by Rycieos** [comment]
What is your bash version?

Are command times showing up properly? If you run `sleep 20`, does the next prompt show `20s` as part of it?

If you make a command fail (eg `type aaaaaaaa`) then run `echo $LP_ERR`, what get's printed?

Do you have a custom `.ps1` file?

**Comment by kapad** [comment]
> What is your bash version?

GNU bash, version 4.4.19(1)-release-(x86_64-pc-linux-gnu)

> Are command times showing up properly? If you run sleep 20, does the next prompt show 20s as part of it?

I have command times disabled in the liquidpromptrc. Does it need to be enabled to get the error messages printed. 
I've just done a fresh ubuntu install, and saw this problem after that. Previously, the error code would get printed. 

> If you make a command fail (eg type aaaaaaaa) then run echo $LP_ERR, what get's printed?

$LP_ERR isn't set. 

> Do you have a custom .ps1 file?

Nope. 
Both my liquid.ps1 and .liquidpromptrc are the default files.

**Comment by kapad** [comment]
So my .liquidpromtrc doesn't even set $LP_PS1.

**Comment by kapad** [comment]
I tried some debugging.. and this seemed odd. 

my changes to the liquidprompt shell script
```
    # Display the return value of the last command, if different from zero
    # As this get the last returned code, it should be called first
    local -i err=$?
    echo "debug liquidprompt"
    echo $err
    if (( err != 0 )); then
        LP_ERR=" $LP_COLOR_ERR$err$NO_COL"
    else
        LP_ERR=''     # Hidden
    fi
```

Output: 
```
[kapad:~/opt/liquidprompt] $ aaaaaaaaaaaaa
aaaaaaaaaaaaa: command not found
debug liquidprompt
0
```

**Comment by Rycieos** [comment]
Everything seems normal. I don't think timing needs to be enabled to see error code; it doesn't in my testing. You could try using a default `liquidpromptrc` and see if that fixes it to see if it is related.

Otherwise my guess is something is running before the `$?` is evaluated. Are you setting `$PROMPT_COMMAND` manually or something? What does `echo $PROMPT_COMMAND` print?

If you are brave, you could run `set -x` to turn debugging on, and trace what happens when you run a command that errors. Example:
```
[rycieos:~] $ type aaaa
++ _lp_runtime_before
...
+ type aaaa
-bash: type: aaaa: not found
+++ _lp_runtime_before
+++ ((  _LP_RUNTIME_SKIP  ))
+++ ((  _LP_RUNTIME_SECONDS=SECONDS-_LP_RUNTIME_LAST_SECONDS  ))
+++ [[ _lp_set_prompt != \_\l\p\_\s\e\t\_\p\r\o\m\p\t ]]
+++ _LP_RUNTIME_SKIP=1
++ _lp_set_prompt
++ local -i err=1
++ ((  err != 0  ))
++ LP_ERR=' \[\]1\[\]'
```

**Comment by kapad** [comment]
> Otherwise my guess is something is running before the $? is evaluated.

This is what I thought as well. But how can I know for sure if that is the case? And how can I tell what the last command is that was run? 

> What does echo $PROMPT_COMMAND print?

`_fasd_prompt_func;_pyenv_virtualenv_hook;_lp_set_prompt`

> If you are brave, you could run set -x to turn debugging on, and trace what happens when you run a command that errors. Example:

This worked. The issue was that I'm also using [fasd](https://github.com/clvv/fasd), and though this is loaded after liquidprompt in my .bashrc, what I think it is doing is running a post-hook. After I commented out fasd, the error code was displayed in liquidprompt. 
```
+ aaaaa
+ '[' -x /usr/lib/command-not-found ']'
+ /usr/lib/command-not-found -- aaaaa
aaaaa: command not found
+ return 127
++ _fasd_prompt_func
++++ history 1
++++ sed 's/^[ ]*[0-9]*[ ]*//'
+++ fasd --sanitize aaaaa
++ eval 'fasd --proc aaaaa'
++ _pyenv_virtualenv_hook
++ local ret=0
++ '[' -n '' ']'
+++ pyenv sh-activate --quiet
+++ local command
+++ command=sh-activate
+++ '[' 2 -gt 0 ']'
+++ shift
+++ case "$command" in
+++ command pyenv sh-activate --quiet
+++ pyenv sh-activate --quiet
+++ true
++ eval false
+++ false
++ true
++ return 0
++ _lp_set_prompt
++ local -i err=0
++ ((  err != 0  ))
++ LP_ERR=
++ local 'IFS= 	
'
++ local GREP_OPTIONS=
++ eval ''
++++ _lp_jobcount_color
++++ ((  LP_ENABLE_JOBS  ))
++++ local ret=
++++ local -i r s
++++ ((  _LP_ENABLE_DETACHED_SESSIONS  ))
+++++ jobs -r
+++++ wc -l
++++ ((  r = 0  ))
+++++ jobs -s
+++++ wc -l
++++ ((  s = 0  ))
++++ echo -nE ''
+++ _lp_sr ''
+++ [[ -n '' ]]
++ LP_JOBS=
++++ _lp_temperature
++++ ((  LP_ENABLE_TEMP  ))
++++ local -i temperature
++++ temperature=0
++++ _lp_temp_sensors
++++ local -i i
+++++ sensors -u
+++++ sed -n 's/^  temp[0-9][0-9]*_input: \([0-9]*\)\..*$/\1/p'
++++ for i in $(sensors -u |
                sed -n 's/^  temp[0-9][0-9]*_input: \([0-9]*\)\..*$/\1/p')
++++ ((  45 > 0  ))
++++ temperature=i
++++ for i in $(sensors -u |
                sed -n 's/^  temp[0-9][0-9]*_input: \([0-9]*\)\..*$/\1/p')
++++ ((  45 > 45  ))
++++ for i in $(sensors -u |
                sed -n 's/^  temp[0-9][0-9]*_input: \([0-9]*\)\..*$/\1/p')
++++ ((  41 > 45  ))
++++ for i in $(sensors -u |
                sed -n 's/^  temp[0-9][0-9]*_input: \([0-9]*\)\..*$/\1/p')
++++ ((  40 > 45  ))
++++ for i in $(sensors -u |
                sed -n 's/^  temp[0-9][0-9]*_input: \([0-9]*\)\..*$/\1/p')
++++ ((  43 > 45  ))
++++ for i in $(sensors -u |
                sed -n 's/^  temp[0-9][0-9]*_input: \([0-9]*\)\..*$/\1/p')
++++ ((  25 > 45  ))
++++ for i in $(sensors -u |
                sed -n 's/^  temp[0-9][0-9]*_input: \([0-9]*\)\..*$/\1/p')
++++ ((  36 > 45  ))
++++ ((  temperature >= LP_TEMP_THRESHOLD  ))
+++ _lp_sr ''
+++ [[ -n '' ]]
++ LP_TEMP=
++++ _lp_load_color
++++ ((  LP_ENABLE_LOAD  ))
++++ local lp_cpu_load
++++ _lp_cpu_load
++++ local eol
++++ read lp_cpu_load eol
++++ lp_cpu_load=083
++++ lp_cpu_load=83
++++ lp_cpu_load=83
++++ local -i load=83/8
++++ ((  load > LP_LOAD_THRESHOLD  ))
+++ _lp_sr ''
+++ [[ -n '' ]]
++ LP_LOAD=
++++ _lp_battery_color
++++ ((  LP_ENABLE_BATT  ))
++++ return
+++ _lp_sr ''
+++ [[ -n '' ]]
++ LP_BATT=
++ _lp_time
++ :
++ _lp_sudo_check
++ :
++ [[ 1, = 1,?* ]]
++ LP_PROXY=
++ [[ 1, = 1,?* ]]
++ LP_VENV=
++ [[ 1, = 1,?* ]]
++ LP_SCLS=
++++ _lp_runtime
++++ ((  LP_ENABLE_RUNTIME && _LP_RUNTIME_SECONDS >= LP_RUNTIME_THRESHOLD  ))
++++ :
+++ _lp_sl ''
+++ [[ -n '' ]]
++ LP_RUNTIME=
++ [[ LP:/home/kapad != \L\P\:\/\h\o\m\e\/\k\a\p\a\d ]]
++ [[ -n '' ]]
++ [[ -f '' ]]
++ [[ -z '' ]]
++ PS1=
++ PS1+='[\u\[\]\[\]:\[\]'
++ PS1+='\[\]~\[\]]'
++ PS1+=
++ PS1+=' \[\]\$\[\] '
+++ _lp_title '[\u\[\]\[\]:\[\]\[\]~\[\]] \[\]\$\[\] '
+++ ((  LP_ENABLE_TITLE  ))
+++ echo -nE '\[]0;'
+++ _lp_as_text '[\u\[\]\[\]:\[\]\[\]~\[\]] \[\]\$\[\] '
+++ echo -nE '[\u\[\]\[\]:\[\]\[\]~\[\]] \[\]\$\[\] '
+++ sed -r 's,\\\[([^\]+|\\[^]])*\\\],,g'
+++ echo -nE '\]'
++ LP_TITLE='\[\]'
++ PS1='\[\][\u\[\]\[\]:\[\]\[\]~\[\]] \[\]\$\[\] '
```

**Comment by Rycieos** [comment]
> The issue was that I'm also using fasd, and though this is loaded *after* liquidprompt in my .bashrc

Yeah that's what I thought. You need to load it first, then it _should_ work, though is not supported.

See #546 and https://github.com/nojhan/liquidprompt/issues/352#issuecomment-87701786.
