### ISSUE TITLE
Display containerization status

### ISSUE THREAD

**Issue by alanhoyle** [nojhan/liquidprompt#569]
Shell: bash/zsh
Operating system: 
Liquid Prompt version (tag, commit): 

Feature request: in HPC environments, we sometimes run interactive sessions in container software like Docker, LXC, or Singularity.  It would be great if there was some indications that a given command prompt was in a container or running natively.  

Detecting Singularity may be done by looking for the existence of these environment variables:
```
SINGULARITY_CONTAINER=ubuntu-latest.simg
SINGULARITY_NAME=ubuntu-latest.simg
```

Detecting Docker may be done by looking for the existence of the file `/.dockerenv` or looking at `/proc/1/cgroup` and noting that things look something like this:

```
$ cat /proc/1/cgroup 
11:memory:/docker/925[...]22f
10:hugetlb:/docker/925[...]22f
```

My understanding is that LXC may be done with something similar to the `/proc/1/cgroup` as above with Docker, but the values are like `11:memory:/lxc/[...]` but I can't test this.  

Note:  if I can figure out how to do this, I'll submit a pull request.

**Comment by alanhoyle** [comment]
Pull request submitted: https://github.com/nojhan/liquidprompt/pull/570

**Comment by Rycieos** [comment]
I like this feature, and I think it needs to happen, but I'm wondering how you are getting Liquidprompt into a container.

If you run `zsh` from bash, it will get all the exported vars from bash. But that doesn't happen when you run `docker exec -it ... bash`.

So what are you doing? Are you mounting Liquidprompt and your config file into the container and the sourcing it? Are you also mounting your `.bashrc` into the container for when you log in?

**Comment by alanhoyle** [comment]
I think I followed-up with this answer at some point, but I'm not sure.  as I said above, I'm working in an HPC environment where we run scientific workflows and containerizing our software lets us more reproducibly run them.  In addition to batch-mode scripted runs, this use-case is for development, experimentation, ad-hoc analyses, etc.  

We mostly used it in the following cases:  

*  Inject the $USER into the container, and it mounts the user's home directory (we had a plugin that did this for Docker)
* Inject environment variables with `docker run -e VAR ...` or `... --env-file FILE ...`
* User-space containers using Singularity. This normally both mounts the calling user's $HOME, and mostly inherits the environment unless cleaned with `singularity run [-e/--cleanenv] ...`  

The Singularity case is by far our most common case in our current architecture, and having the prompt obviously show "You're running in a Singluarity container!" is really helpful.  

For default Docker containers, you
