### ISSUE TITLE
unable to run commands within command prompt

### ISSUE THREAD

**Issue by anEffingChamp** [nojhan/liquidprompt#573]
Shell: bash/zsh
Operating system: OSX 10.12.6 (16G29)
Liquid Prompt version (tag, commit): 1.11

http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x279.html

I can not find a place to run any external commands. When I write them into the available LiquidPrompt variables, they run once on initialization, and then never again. That limits my customization options.

**Comment by Rycieos** [comment]
The recommend way is to run commands in your `liquid.ps1` file, since that is sourced each time the prompt is drawn. For example, I have this in mine:

```
# Function for getting amount of mail in inbox for prompt
_new_mail() {
  if [ -r "$MAIL" ]; then
    NEWMAIL="$(grep -c '^Subject: ' "$MAIL")"
    if [ "$NEWMAIL" -gt -0 ]; then
      echo "${NEWMAIL}m "
    fi
  fi
}

# add time, jobs, load and battery
LP_PS1="${LP_PS1_PREFIX}$(_new_mail)${LP_TIME}${LP_BATT}${LP_LOAD}${LP_JOBS}"
...
```

**Comment by anEffingChamp** [comment]
I see what my problems was. The `liquidpromptrc` only runs at startup, but still has access to the internally defined functions and variables. In this case, I was still using the provided colors variables.

However these variables are not available at runtime in `liquid.ps1`. So in this case:

- I had a function to choose a color.
- The color was based on a liquidprompt variable, but it was not available.
- I thought that the function was not running.

Now I know. I updated my function to use Linux color codes rather than the liquidprompt variables, and it runs just fine.
