### ISSUE TITLE
git colors broken

### ISSUE THREAD

**Issue by Stunkymonkey** [nojhan/liquidprompt#575]
Shell: bash
Operating system: arch-linux
Liquid Prompt version (tag, commit): eda83efe4e0044f880370ed5e92aa7e3fdbef971

![Screenshot-2019-06-11_000032](https://user-images.githubusercontent.com/1315818/59229947-36cd4900-8bdc-11e9-83b9-4199427b5264.png)
the docs say after pushing the color should not be yellow

**Comment by Rycieos** [comment]
What is your `bash` and `git` versions?

If you change out of that directory, does your prompt update correctly to not show any git info?

What branch is your master branch set to track off of? You can find out with this command:
```
git rev-parse --abbrev-ref master@{upstream}
```
It should be something like `origin/master`.

What does this command return?
```
git rev-list --count refs/remotes/$(git rev-parse --abbrev-ref @{upstream})..HEAD
```
I would assume it returns `34` since that is what your prompt is showing, but it doesn't make much sense then why `git push` says there is nothing to push.

Also add the output of `git remote show origin` just to check all the bases.

**Comment by Stunkymonkey** [comment]
> What is your bash and git versions?

```
[felix:~] $ bash --version
GNU bash, version 5.0.7(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[felix:~] $ git --version
git version 2.22.0
```

> If you change out of that directory, does your prompt update correctly to not show any git info?

yes

> What branch is your master branch set to track off of? You can find out with this command:

there is no upstream configured, so the command fails. this is the [repo](https://github.com/Stunkymonkey/dotfiles)


> Also add the output of git remote show origin just to check all the bases.

```
[felix:~/.dotfiles] master(34) 2s ± git remote show origin
* remote origin
  Fetch URL: git@github.com:Stunkymonkey/dotfiles.git
  Push  URL: git@github.com:Stunkymonkey/dotfiles.git
  HEAD branch: master
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

**Comment by Rycieos** [comment]
> there is no upstream configured

That doesn't add up, since in the `remote show` output it says
> Local ref configured for 'git push':
>    master pushes to master (up to date)

Your `master` branch is configured to track `origin/master`.

What does this output?
```
git rev-list --count refs/remotes/origin/master..HEAD
```

**Comment by Stunkymonkey** [comment]
> That doesn't add up, since in the remote show output it says
```
[felix:~/.dotfiles] master(34) ± git remote
bene
origin
```
the bebe remote is only used to cherry-pick some commits. i do not have write permissions to this repo

> git rev-list --count refs/remotes/origin/master..HEAD

```
[felix:~/.dotfiles] master(34) ± git rev-list --count refs/remotes/origin/master..HEAD
34
```

**Comment by Rycieos** [comment]
Kinda strange...

That last command you ran is showing the "34" that liquidprompt is showing, git is saying that there are that many commits different between `origin/master` and `HEAD`. I'm still thinking this is a git repo issue.

What happens if you do an explicit `git fetch origin`? Or an explicit `git push origin master`?

**Comment by Stunkymonkey** [comment]
```
[felix:~/.dotfiles] master(34) ± git fetch origin
From github.com:Stunkymonkey/dotfiles
 * branch            master     -> FETCH_HEAD
[felix:~/.dotfiles] master(34) 2s ± git push origin master
Everything up-to-date
[felix:~/.dotfiles] master(34) 5s ±
```
still the same

**Comment by Rycieos** [comment]
That fetch command looks weird, if it was actually up to date it shouldn't have fetched anything. What happens if you run that fetch again?

I have a feeling your remote and local branches aren't actually the same. What does `git branch -a -vv` show?

**Comment by Stunkymonkey** [comment]
fetch does not fetch anything new.
```
$ git branch -a -vv
* master                62b6181 [sway] prevent xwayland-firefox from idleing
  remotes/bene/master   99aacc9 Fix Stupid commit
  remotes/origin/master 40a66c5 [alacritty] add minus to decrease font-size
```

**Comment by Rycieos** [comment]
That's the problem right there, your local copy of the remote is wrong. Your actual origin's `master` points to `62b6181`, but your `remotes/origin/master` says it's `40a66c5`.

If you are sure that `git fetch` is working correctly, you could always whack your remote settings and see if that fixes it:
```
git remote remove origin
git remote add origin git@github.com:Stunkymonkey/dotfiles.git
git fetch origin
git branch -u origin master
```

**Comment by Stunkymonkey** [comment]
yes this fixes it
thanks for your time
awesome work you are doing
