### ISSUE TITLE
Duplicate character with completion menu select search 

### ISSUE THREAD

**Issue by mxmilkiib** [nojhan/liquidprompt#584]
Shell: bash/zsh
Operating system: Arch 
Liquid Prompt version (tag, commit):  master eda83ef

When I have have liquidprompt enabled and ```zstyle ':completion:*' menu select=0 search``` near the top of my completion config file, I get a duplicate character being printed after I press Tab.

![rose_2019-08-22-155833](https://user-images.githubusercontent.com/108225/63525498-b8532880-c4f5-11e9-8532-95210d549c96.png)

The top right term is after I press Ctrl-C and hit backspace twice. If I were then to press return, then the l would disappear. If I hit Ctrl-C again, it stays.

**Comment by mxmilkb** [comment]
Actually, it's not caused by that completion config. I'm not sure what it's caused by.

**Comment by Rycieos** [comment]
What shell and shell version are you using? And do you still have this issue with the latest Liquidprompt version? And some reproduction steps would be helpful.

**Comment by mxmilkiib** [comment]
I'm using zsh. I had moved to powerlevel10k because of this issue but I've just switched back using zgen to liquidprompt.

The major problem I was having is that the display of the text is shunted one character to the right because of the duplicated initial character, but the underlying text still appears to be in the correct position, which often made editing any text I entered in a very confusing experience.

It happens on the second tab, i.e., if i type "test" then press tab, I get "ttest". If I type "2" then I get "2to3", if i press tab again, that turns into "22to3". If I were to hold down backspace, I'd be left with an unremovable "t" or "2".

I just made my .zshrc [this](https://gist.github.com/mxmilkiib/4fea6b13405b862eaf35fa376debe3af), commenting out everything but zgen and the lp load line, no change. (Removing the lp line does indeed disable lp, adding it again and trying (all with zgen resets and a new zsh in between) offers no change.

**Comment by Rycieos** [comment]
I boiled my `.zshrc` down to just `. ~/dev/liquidprompt/liquidprompt`. I don't have `zgen` installed, but I can't imagine that it would inject anything weird, right? I'm running zsh 5.5.1.

I can't reproduce this. It seems to be a Unicode character draw length issue like some others I can't reproduce right now either...

Can you give me any more information about your setup? Shell version? It looks like you were testing in Tmux, does it happen without that?

**Comment by mxmilkiib** [comment]
Plain zsh from the Arch repos; extra/zsh 5.8, but this has been happening for a few zsh versions now.

That's just a tiling window manager (bspwm), not Tmux, so multiple instances of urxvt (rxvt-unicode).

The font is [gohu](https://font.gohu.org/) so no Unicode characters.

Hmm, confusing stuff! Thinking about it now, the only thing I haven't done yet I haven't taken out my own ps configuration, I'll try that in the next day or so..

**Comment by mxmilkiib** [comment]
Bingo, the problem is caused by my prompt setup.

I have this so that when a command finishes, it sets of a visual bell which is translated into an urgent window so that the desktop the command is on gets hightlighted in a taskbar desktop pager.

```
# echo a bell character, bell as urgent, visual urgent = sway workspace notification on end of command
LP_PS1_POSTFIX="$(echo '\a')"
```

Commenting it out resolves the problem.

**Comment by Rycieos** [comment]
Glad you could track it down.

We actually have such a feature now, just recently merged. See
https://github.com/nojhan/liquidprompt/blob/25cd5dcba4832c2f0a374e954e56ec63c105d94e/liquidpromptrc-dist#L134-L141
You could set `LP_RUNTIME_BELL_THRESHOLD` to 0 to make it always ring.

But if you want to try debugging this, it might help me solve some other related issues. Does it get fixed if you replace it with this?
```
LP_PS1_POSTFIX="${_LP_OPEN_ESC}$(echo '\a')${_LP_CLOSE_ESC}"
```
Note that using `echo` is probably not a good idea anyway, maybe try `tput bel`?
```
LP_PS1_POSTFIX="${_LP_OPEN_ESC}$(tput bel)${_LP_CLOSE_ESC}"
```

**Comment by mxmilkiib** [comment]
Yes, that fixes the problem, thank you! :)
