### ISSUE TITLE
use emoticons in prompt depending on $?

### ISSUE THREAD

**Issue by monperrus** [nojhan/liquidprompt#591]
Hi!

I would like to have different emoticon in the prompt depending the result of the command.

```
$ true
🙋
$ false
😠
```

How to do that?

**Comment by Rycieos** [comment]
You would need to make a custom ps1 file.

The value of `$LP_ERR` will only be something if there was an error, so if you replace this line in the default theme:
https://github.com/nojhan/liquidprompt/blob/af63c4cfb8afe3f3161f3ace4aba3b940847a7a8/liquid.ps1#L44

with this:
```bash
if [[ -n $LP_ERR ]]; then
    my_err=😠
else
    my_err=🙋
fi

LP_PS1="${LP_PS1}${LP_RUNTIME} ${my_err}${LP_MARK_PREFIX}${LP_MARK}${LP_PS1_POSTFIX}"
```

This should work for you, let me know if you have any issues with it.
