### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by sukhchain99** [nojhan/liquidprompt#595]
Shell: bash
Operating system: Windows
Liquid Prompt version (tag, commit): 

Hi, it's me back again.
I can't find any instructions on how to install liquidprompt on Windows.
If you can tell me where it is or if it's possible to install it on windows or not, then I would appreciate that.

**Comment by mariusstrom** [comment]
Works in Windows under the Bash Subsystem just fine.

**Comment by Rycieos** [comment]
Following the normal install instructions works in any Unix shell in Windows, like Cygwin, GitBash, or the Windows Bash Subsystem.

**Comment by sukhchain-mansa** [comment]
Ok!

**Comment by sukhchainn** [comment]
Edit: After using it for a while I noted that it's not slow, it just take 2-3 secs to startup.

**Comment by Rycieos** [comment]
Slowness on Cygwin is a known and unfixable issue. See #130.
