### ISSUE TITLE
Terraform Workspace Support

### ISSUE THREAD

**Issue by afmsavage** [nojhan/liquidprompt#600]
Shell: bash/zsh (either)
Operating system: Any
Liquid Prompt version (tag, commit): master

I was hoping to add the functionality to display the current Terraform Workspace to the prompt.  `terraform workspace show` outputs the name of the currently selected workspace.

https://www.terraform.io/docs/commands/workspace/show.html

**Comment by afmsavage** [comment]
Found a simple shell script in this repo that adds this functionality.

https://github.com/amatellanes/terraform-workspace-prompt

``` shell
#!/usr/bin/env bash

function terraform_prompt()
{
    if [ -d .terraform ]; then
        workspace="$(command terraform workspace show 2>/dev/null)"
        echo " (${workspace})"
    fi
}

export PS1='\u@\h \[\033[38;5;135m\]\w\[\e[38;5;99m\]\[\e[1m\]$(terraform_prompt)\e[0m\$ '
```

**Comment by Rycieos** [comment]
Thanks for the request. This is something obvious that should be in the prompt, but until performance improves it will have to wait.

**Comment by afmsavage** [comment]
Terraform 0.13.0 beta was just announced recently.  Hopefully it brings with it some improvements to some of the speeds.  I understand on the speed thing, it's pretty slow even running the commands manually.

**Comment by Rycieos** [comment]
> it's pretty slow even running the commands manually.

Yeah, Terraform can be a bit slow. But even besides that is the overhead when the feature is disabled. Right now, every feature added also adds two subshell runs at the least to check if the feature is enabled. I am working to change this, but right now it means even if you have every feature disabled in your config, you are paying a heavy cost in runtime just to check those toggles.
