### ISSUE TITLE
sensors -u error messages unfiltered

### ISSUE THREAD

**Issue by Rmano** [nojhan/liquidprompt#611]
Shell version: ZSH 5.4.2

OS: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

Liquid Prompt version:  v1.12-beta1 commit b460519ff5d63a063d67afb176013a4be90aae3e

`sensors -u` spams the prompt with this:
```bash
ERROR: Can't get value of subfeature temp1_input: Can't read                    
θ63° [romano:~] % 
ERROR: Can't get value of subfeature temp1_input: Can't read                    
θ63° [romano:~] % 
ERROR: Can't get value of subfeature temp1_input: Can't read                    
[romano:~] % 
```

### Possible Solution

This patch fixes it, although maybe is not the correct way:
```diff
θ69° 1& [romano:~/software/liquidprompt] master(2)* ± git diff origin/master
diff --git a/liquidprompt b/liquidprompt
index 415acc6..c8e6ed8 100755
--- a/liquidprompt
+++ b/liquidprompt
@@ -1510,7 +1510,7 @@ if (( LP_ENABLE_TEMP )); then
         # Return the hottest system temperature we get through the sensors command
         # Only the integer part is retained
         local -i i
-        for i in $(sensors -u |
+        for i in $(sensors -u 2> /dev/null|
                 sed -n 's/^  temp[0-9][0-9]*_input: \([0-9]*\)\..*$/\1/p'); do
             (( $i > ${temperature:-0} )) && temperature=i
         done
```

### Steps to Reproduce

Just configure the temperature in the propt.

**Comment by Rycieos** [comment]
This is a commonly reported issue, see the [FAQ](https://github.com/nojhan/liquidprompt/wiki/FAQ#sensors-throw-an-error-each-prompt) (and #445).

This issue is fresh and has an active reporter, so feel free to continue the discussion here.

The commonly suggested "fix" (same as yours) is not acceptable, as it would suppress the errors that users need to see to know they need to fix their broken hardware. I think we need to do something, as we get soooooo many reports on this, but suppressing all errors isn't it.

As suggested elsewhere once, maybe we print the error one time on startup, then suppress after that?

**Comment by Rmano** [comment]
> As suggested elsewhere once, maybe we print the error one time on startup, then suppress after that?

Well, that could be (even if it's still not optimal).

This thing comes from the radeon video card in my laptop; this is (supposedly) activated only on-demand:

```
radeon-pci-0100
Adapter: PCI adapter
temp1:
ERROR: Can't get value of subfeature temp1_input: Can't read
  temp1_crit: 120.000
  temp1_crit_hyst: 90.000
``` 
The error comes out becasue *in this moment* the card is not enabled (but it can become enabled), so it's not clear that I should suppress the pitput as put in the FAQ. Granted, the error is from `sensors`, it shouldn't use stderr just to say that a card sensor is disabled. 

So I am not sure.

**Comment by jkugler** [comment]
Another data point. In my laptop, I am getting `ERROR: Can't get value of subfeature curr1_input: Can't read`

It has to do with the current input for the laptop. When just running `sensors` it simply prints
```
curr1:            N/A  
```
with no error message.

However, when run with `sensors -u` we see the error message `ERROR: Can't get value of subfeature curr1_input: Can't read`

So, in this case, it isn't an error message really...or maybe it's a bug in the sensors package?

**Comment by Rycieos** [comment]
Please see the latest discussion on issue #445. Looking now, I'm not sure why @Rmano opened a new issue for this, since they were part of the original discussion on #445.

Though the 3.5 years would make me forget about my Github comments, so I suppose that can be forgiven 😄

**Comment by Rmano** [comment]
Oops, I completely forgot the other issue and I don't know why I opened another one. Could be closed as duplicate, I think.
