### ISSUE TITLE
terminal not supported error with zsh and alpine

### ISSUE THREAD

**Issue by azmeuk** [nojhan/liquidprompt#615]
Shell: zsh 5.8

Operating system: Alpine linux 3.8

Liquidprompt version: v1.12-rc.1

### Steps to Reproduce

1. Open a SSH connection to a ZSH shell with liquidprompt on a Alpine host.

### Expected Behavior
I expect no error messages, and prompt colors to be displayed correctly.

### Current Behavior
I get this error message at connection.
> liquidprompt: terminal xterm-256color does not support foreground colors
> liquidprompt: terminal xterm-256color does not support background colors
> liquidprompt: terminal xterm-256color does not support foreground colors
> liquidprompt: terminal xterm-256color does not support background colors

Also my prompt shows no color.

### Additional context
My terminal is alacritty, but I tested with some others and the result is always the same.
I have the right terminfos installed in my remote session.
```bash
$ ls /etc/terminfo/x/
xterm  xterm-256color  xterm-color  xterm-xfree86
```

My local session has also alacritty + zsh + liquidprompt, and everything goes well.

I just stumbled upon #586. My local session has `tput` but the remote alpine session does not.

**Comment by azmeuk** [comment]
Fixed with `sudo apk add ncurses` to add `tput` support.

**Comment by Rycieos** [comment]
I'm actually going to reopen this, this specific case deserves a better error message. Thanks for the report.

**Comment by Rycieos** [comment]
Also, strange that you see the error messages twice. Any chance you are loading Liquidprompt twice?

**Comment by azmeuk** [comment]
Actually yes. Once in `~/.zshrc` and once in `/etc/zsh/zshrc`.

**Comment by Rycieos** [comment]
I added a warning on startup if `tput` isn't available. Should be more obvious now what the problem is.
