### ISSUE TITLE
Bash history setting `history -a [..]` via PROMPT_COMMAND not honored

### ISSUE THREAD

**Issue by ottok** [nojhan/liquidprompt#616]
I have these settings in my custom `.bashrc`:

```
# Save history in real time
# idea from http://www.cuberick.com/2008/11/update-bash-history-in-realtime.html
# http://stackoverflow.com/questions/103944/real-time-history-export-amongst-bash-terminal-windows
HISTTIMEFORMAT="[%F %T] "        # time entry for .bash_history
HISTSIZE=10000000                # big big history
HISTFILESIZE=10000000            # big big history
shopt -s histappend              # append to history, don't overwrite
PROMPT_COMMAND="history -a; history -c; history -r;$PROMPT_COMMAND"
HISTCONTROL=ignoredups:ignorespace
```

My `.bash_history` has the contents:
```
$ tail .bash_history 
#1595453912
cd
#1595453915
cat .bashrc
#1595453934
cat ~/.bashrc_otto
#1595453953
test
#1595453961
tail .bash_history 
```

It seems that the setting `PROMPT_COMMAND="history -a; history -c; history -r;$PROMPT_COMMAND"` does not apply while the other settings apply.

This is a problem, because I want all my commands to be added to the bash history after each command, so that I have the same (and recent) bash history available in all of my parallel bash sessions. Currently this does not have effect, and new .bash_history entries are written only when I close a session.

I am a power user. Could you please give me some hints on how I should debug this? What is the recommended way to inject `PROMPT_COMMAND="history -a; history -c; history -r;$PROMPT_COMMAND"`to Liquidprompt to get real-time bash history working again?

Having as much history as possible might also be aligned with the goals of Liquidprompt. Maybe you want to add native support for this feature?

Running version 1.11-3ubuntu1.

**Comment by Rycieos** [comment]
Since you are modifying your `$PROMPT_COMMAND`, are you doing it before loading Liquidprompt? I bet that is your problem. See [this in the FAQ](https://github.com/nojhan/liquidprompt/wiki/FAQ#prompt-timing-isnt-working).

Note that 1.11 isn't the latest version, if this doesn't fix your issue, I'll need to you to test this on 1.12.0 before we can dig deeper.

**Comment by ottok** [comment]
Ok, I figured it out. It is because I've added the workaround https://github.com/nojhan/liquidprompt/issues/609#issuecomment-649750066 in my .bashrc and that definition of `$PROMPT_COMMAN` overrided the previous one. Fixed it by moving the history line below it.

Sorry for bothering, this was not a bug.

Closing as invalid.
