### ISSUE TITLE
Different output first time?

### ISSUE THREAD

**Issue by mxmilkiib** [nojhan/liquidprompt#620]
I'm not sure if this is a feature or support request.

I have a `tput bel` in the prompt so that I get indication when an app finishes and the shell returns, but this also is triggered when I open the terminal window, i.e., the first time the prompt appears.

Is there or could there be a method in LP, or just a general if/typeset solution that could be used to affect the correct change for this first-time instance? Thanks for any assistance!

**Comment by Rycieos** [comment]
We have a feature called "runtime bell" which will send a bell terminal code when a command completes, which I think is what you are looking for. See [the docs](https://github.com/nojhan/liquidprompt#feature-configuration) for `$LP_ENABLE_RUNTIME_BELL` and `$LP_RUNTIME_BELL_THRESHOLD`. It is off by default, and set to 10 seconds. Meaning any command that runs for 10 seconds or more will ring the bell when it completes. You could set it to 0 seconds if you want it to run after every command.
