### ISSUE TITLE
Support for custom monitoring functions

### ISSUE THREAD

**Issue by rfc1036** [nojhan/liquidprompt#622]
### Description

I would like to be able to provide custom versions of functions like `_lp_battery()` and `_lp_temp_foo()`. Would you accept patches to implement this? Do you already have a design in mind? E.g. for temperature I was thinking of using just accepting the value of `$_LP_TEMP_FUNCTION` if it were already set.

### How will this be useful?

My goal is to define custom functions which can report exactly what I want and are much faster since they do not need to fork an external command. The `acpi` command is very old and does not fully describe modern hardware.

### Example prompt

This is an example custom replacement for `_lp_temp_acpi()`:

```
_lp_temp_hwmon() {
  local -i temp
  #read temp < /sys/class/hwmon/hwmon2/temp1_input      # CPU package
  read temp < /sys/class/hwmon/hwmon4/temp1_input       # chipset
  temperature=$((temp / 1000))
}
# currently this does not work because the variable is reset at startup :-(
_LP_TEMP_FUNCTION=_lp_temp_hwmon
```

**Comment by Rycieos** [comment]
If you want a quick fix, you can do what you want by setting `$_LP_TEMP_FUNCTION` _after_ you load Liquidprompt.

> Would you accept patches to implement this? Do you already have a design in mind?

Probably not, because yes I do have a design in mind. See below.

> functions which can report exactly what I want and are much faster since they do not need to fork an external command.

This is the center of my design. Reduce forking and expose as much data as possible so users and themes can use whatever data they want. Ideally we don't have to change the functions names, just how they work.

I'd be happy to accept PRs doing those kind of changes. I won't promise to merge them right away, since this rework is complicated, but any work will help!

**Comment by rfc1036** [comment]
I have linked in #607 a couple of optimized functions and I would be happy to work on more.
Still, development would be much easier if liquidprompt were restructured to allow redefining or otherwise configuring the functions which provide data as I suggested here.

**Comment by Rycieos** [comment]
> Still, development would be much easier if liquidprompt were restructured to allow redefining or otherwise configuring the functions which provide data as I suggested here.

Agreed, though

> allow redefining ... the functions which provide data

I'm not sure that is the ideal solution. Ideally we would have each data providing function work for all users without any changes. We can allow that redefining, sure, but ideally we make the data functions just work. (I'm also not sure how we could block data function redefining, as shell has no such protections.)

My idea is thus: each data function returns as much data as possible from its data source. For example, a Git data function would return current branch, current working directory status, changed file count, changed line count, etc. Then a separate formatting function would take that data and turn it into a string that would be embedded in the prompt. This is not how is it split today; each function does both jobs. This split would allow other themes to replace the formatting function, and not have to mess with the data gathering at all.

**Comment by Rycieos** [comment]
[v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1) is out, which contains a lot of refactoring to break data sources into their own functions. See [Data Functions](https://liquidprompt.readthedocs.io/en/v2.0.0-beta.1/functions/data.html).

I would still rather improvements to data sources be added to Liquidprompt directly. And any improved functions that won't apply to all OSs or users can use an interface similar to Temperature where we select which data source to use on startup. So if you have ideas/implementations for better data sources, please, send patches!
