### ISSUE TITLE
Hostname wrongly colored over SSH for root user

### ISSUE THREAD

**Issue by sjaks** [nojhan/liquidprompt#629]
When working locally, the hostname color stays the same:
![image](https://user-images.githubusercontent.com/44066308/97716629-86abf900-1acc-11eb-95b5-46f9752ba6a5.png)

When working over SSH, the hostname becomes **yellow when it should be purple**:
![image](https://user-images.githubusercontent.com/44066308/97716966-ebffea00-1acc-11eb-8f5c-671acd1383b5.png)

All users in the screenshots use the same config and liquidprompt version is ` 1.11-3ubuntu1` on both machines.
My config includes:
```
LP_COLOR_HOST=${BLUE}
LP_COLOR_SSH=${PURPLE}
LP_ENABLE_SSH_COLORS=0
```
https://github.com/sjaks/.files/blob/master/rc/liquidpromptrc

**Comment by Rycieos** [comment]
Note that v1.11 is not the latest version, [v1.12.1](https://github.com/nojhan/liquidprompt/releases/tag/v1.12.1) is. Though maybe no one is updating the Ubuntu packages? I thought they were tracking with Debian packages...

Anyway, the check for an SSH connection does have priority over if it is root. However, it depends on environment variables. `sudo` does not pass env vars to the program it runs by default. You have two options:
* `sudo -E su`: the `-E` tries to pass current env vars to the new program. `sudo` asks for _your_ password.
* `su`: `su` by itself takes env vars while switching users. The difference is here you must type the password of the user you are switching to.

I have confirmed that both of these options work.

There is no way to detect an SSH connection if these env vars are missing and we are running under a different user than the one that opened the SSH connection, so there is no bug to fix here.
