### ISSUE TITLE
Activating liquidprompt clobbers completion options

### ISSUE THREAD

**Issue by nedbat** [nojhan/liquidprompt#641]
When I set a zsh completion option, and then activate liquidprompt, my completion option is gone.

In my case, I have a git shortcut function, and I set the completion to be the same as for git:
```
g() { git "$@"; }
compdef g=git
source ~/liquidprompt/liquidprompt
```
Now the completion for "g" doesn't work properly.  If I define the completion after the prompt, then it does work:
```
g() { git "$@"; }
source ~/liquidprompt/liquidprompt
compdef g=git
```

Shell: zsh 5.8 (x86_64-apple-darwin17.7.0)
Operating system: MacOS 10.13.6
Liquidprompt version: v2.0.0-beta.2

### Possible Solution

Why invoke "compinit" when activating the prompt? Leave that out.

**Comment by Rycieos** [comment]
Referencing this line:
https://github.com/nojhan/liquidprompt/blob/f445eff684558e8bf200df2f3f897c09374b7d6c/liquidprompt#L374

I read the Zsh manual on this module: http://zsh.sourceforge.net/Doc/Release/Completion-System.html
Which describes calling `compinit` in the `.zshrc` or similar. So I didn't call `compinit`, but then you get this error when calling `compdef`:
```
lp_activate:20: command not found: compdef
```
So `compinit` *must* be called first.

My thought process was why not enable completion. But I didn't realize that running `compinit` after it was already called (and some configuration was done) would wipe all previous configuration.

So I see a few solutions:
1. Only add this completion if the user has already called `compinit`. How would we test for that?
2. Call `compdef` no matter what, and ignore errors.

Any ideas on how to detect the current state of the completion system?

Actually, it looks like a function:
```
$ type compdef
compdef not found
$ autoload -Uz compinit && compinit
$ type compdef
compdef is a shell function from /usr/share/zsh/5.5.1/functions/compinit
```

So I think this patch should work:
```diff
-        autoload -Uz compinit && compinit && compdef __lp_theme_zsh_complete lp_theme
+        # Enable the autocomplete if the autocomplete system is initialized.
+        __lp_is_function compdef && compdef __lp_theme_zsh_complete lp_theme 
```

Would that fix your issue?

**Comment by nedbat** [comment]
That was fast! Thanks.

I tried your patch, and it fixes my issue, yes.  I don't know what completion that compdef is enabling, so I can't confirm that it still enables it though.

**Comment by Rycieos** [comment]
It's for the `lp_theme` function. Hitting `<Tab>` after should autocomplete `default`, or more options if you source another file like `themes/powerline/powerline.theme`.
