### ISSUE TITLE
add _lp_git_staged_lines and _lp_git_staged_files for themes

### ISSUE THREAD

**Issue by Orgams** [nojhan/liquidprompt#644]
### Description

Hello, i customize a power line theme and i has surprise by the base commend git for _lp_git_uncommitted_lines : is the addition of diff in working and stage.

maybe add _lp_git_staged_lines and _lp_git_staged_files for themes

### How will this be useful?

Can use this for show diff line/file in working ant staging zone in same time

### Example prompt

![image](https://user-images.githubusercontent.com/6304178/104121964-79b84b00-5342-11eb-85e6-6bb33aa2d79d.png)

PS : with a little  help i can make a PR

**Comment by Rycieos** [comment]
I am not completely sure I understand what you are asking for.

> i has surprise by the base commend git for _lp_git_uncommitted_lines

I think you are misunderstanding the code in `_lp_vcs_details_color()`:
https://github.com/nojhan/liquidprompt/blob/7c4958bb4c0c3a33f620005e0fb92abd60bd18b7/liquidprompt#L1279-L1291

This section will detect if a VCS provider supports a staging area (like Git) or not (like Mercurial), and if it does, show the diff to staging, and if not, show the diff to the last commit.

Are you asking for the default theme to show both staged and uncommitted line counts? I doubt that many users would find that very helpful, and keeping the default theme the same as users have come to expect is important. But you are welcome to create a theme that does that. If you do, I would want to see it.

Please correct me if I did not understand your request.

**Comment by Orgams** [comment]
After thinking about it, do not modify _lp_git_uncommitted_lines but maybe create a new :
* _lp_git_uncommitted_lines use `git diff --shortstat HEAD` (exists)
* _lp_git_unstaged_lines use `git diff --shortstat` (exists)
* _lp_git_staged_lines use `git diff --shortstat --cached` (new)

Not to integrate it in the default LiquidPrompt but to use it in the theme

**Comment by Rycieos** [comment]
> 
> 
> After thinking about it, do not modify _lp_git_uncommitted_lines but maybe create a new :
>
> * _lp_git_staged_lines use `git diff --shortstat --cached` (new)
> 
> 
> Not to integrate it in the default LiquidPrompt but to use it in the theme

I'm fine with that. I had considered adding a `_lp_vcs_staged_files()` and `_lp_vcs_staged_lines()` before, but didn't since I wasn't going to add them to the default theme, and had not thought of a theme that would use them. But if you could find a use for them, sure, I can add them.

**Comment by Rycieos** [comment]
The linked PR is a proposed fix. Could you give it a try and see if it is what you were expecting?

The docs for the new functions can be found [here](https://liquidprompt--645.org.readthedocs.build/en/645/functions/data/vcs.html#lp_vcs_staged_files).

**Comment by Orgams** [comment]
I look this in WE.
Thank you!
