### ISSUE TITLE
[ZSH] LP_MARK_PREFIX="\n" does not work as expected on zsh

### ISSUE THREAD

**Issue by imran27** [nojhan/liquidprompt#655]
`LP_MARK_PREFIX="\n"` adds a newline as expected, on BASH
![image](https://user-images.githubusercontent.com/6375554/106705511-0ba53200-6629-11eb-806a-0e0792cd5b8a.png)

On ZSH however:
![image](https://user-images.githubusercontent.com/6375554/106705611-41e2b180-6629-11eb-8abe-20bebc4e210f.png)

OS:
`uname -a` 
Linux DNX467-840G6 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 GNU/Linux

`cat /proc/version`
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01:00 PST 2020

liquidprompt-git (commit: e3c908c)

**Comment by Rycieos** [comment]
Note that the [Zsh docs on prompt expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html) do not specify that backslash escaped sequences are expanded. As far as I know, the only way that Zsh supports putting a newline in the prompt is by putting a newline literal character in PS1. And Liquidprompt does not do anything special with the contents of `LP_MARK_PREFIX` other than inject it directly into PS1.

`LP_MARK_PREFIX=$'\n'` should do what you want.

If you had this assumption from reading our (old) docs:
> To postfix the prompt, use the `LP_PS1_POSTFIX` variable. For example, to add a newline and a single character:
>
>     LP_PS1_POSTFIX="\n>"

Then yeah, that part of the docs was bad. Someone else noticed that and opened PR #589 to fix it. I wanted even more improvements, but the contributor hasn't updated the PR yet, so now that you have reported this and v2.0.0 is about to drop, I think I will make that fix myself.
