### ISSUE TITLE
theme-preview.sh reports liquidprompt: line 2775: _LP_RUNTIME_SECONDS: unbound variable

### ISSUE THREAD

**Issue by LudovicRousseau** [nojhan/liquidprompt#656]
I try to generate theme preview.

Shell: ± bash 3.2.57(1)-release

Operating system: macOS Mojave 10.14.6, Darwin imac.xxx.fr 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64

Liquidprompt version: v2.0.0

### Steps to Reproduce

1. $ lp_theme --list
default
2. ± ./tools/theme-preview.sh default
liquidprompt: line 2775: _LP_RUNTIME_SECONDS: unbound variable

### Expected Behavior
I expect a nice theme preview.

### Current Behavior
Error:  liquidprompt: line 2775: _LP_RUNTIME_SECONDS: unbound variable

### Possible Solution
I used `export _LP_RUNTIME_SECONDS=0` I then get a new error:
`liquidprompt: line 1368: _LP_ENABLED_VCSS[@]: unbound variable`

**Comment by Rycieos** [comment]
Ah, of course I failed to test that script under  Bash-3.2. Should be a simple fix. I should add a test just to check that this script doesn't error.

**Comment by Rycieos** [comment]
I pushed 827fb9fa39c7e11235180f3307df91298f4b89ba that should fix this, could you give it a try please?

**Comment by LudovicRousseau** [comment]
It works fine now.
I get:
![theme](https://user-images.githubusercontent.com/398496/107125049-b9be0f80-68a7-11eb-81fa-aecb81f4bc47.png)

**Comment by Rycieos** [comment]
[v2.0.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.1) released, which fixes this issue. Thanks for the report!
