### ISSUE TITLE
Hyperlinks on path elements in graphical session

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#659]
I guess most of users spend their time in the terminal under a graphical session, thus having access to the mouse and graphical apps. It happens to me quite often to start a graphical file browser from within the terminal, to do something that is more easily done in it (like image browsing, complex files selection, etc.). As of now, you have to write down the command starting the browser to actually start it from the current directory. It would be easier if it was just one click away from where the user is: the terminal.

Fortunately, there is a set of OSC escape sequences which can add an hyperlink into a text and which is now quite supported by terminal emulators (see [[1]](https://github.com/mintty/mintty/wiki/CtrlSeqs#hyperlinks)[[2]](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda)).

For example, this hides the `file:///home/nojhan/code/` URL within the `code` text, which is then displayed with a dotted underline:
`printf '\e]8;;file:///home/nojhan/code/\e\\code\e]8;;\e\\\n'`

The path formatting function (`_lp_path_format`) should have an option to insert `file://` URLs behind each path element.

**Comment by Rycieos** [comment]
Interesting idea. I would think it is a feature some would find useful.

Would this be a feature supported regardless of theme? Like a LP_ENABLE_PATH_LINKS. That makes the most sense to me.

Would you want each directory in the path to be a link? Or just the path as a whole to the current working directory?

I'll have to find a different terminal emulator to try this, it looks like my current one does not support it.

**Comment by nojhan** [comment]
Yes I think a global setting and a separate link on each path elements are the best options.
