### ISSUE TITLE
Link to documentation on README on stable version is empty. 

### ISSUE THREAD

**Issue by rodo-nunez** [nojhan/liquidprompt#660]
The README on the master branch for the last commit goes to this site:

https://liquidprompt.readthedocs.io/en/stable/#

which looks like this

![image](https://user-images.githubusercontent.com/10286777/108717912-98426200-74fc-11eb-8a42-2f1807ba2573.png)

But the "latest" version does have the documentation 

https://liquidprompt.readthedocs.io/en/latest/install.html

![image](https://user-images.githubusercontent.com/10286777/108718140-e3f50b80-74fc-11eb-949a-99f601f60c50.png)

It would be nice to update the stable version.

Thanks for maintaining this repo! =)

**Comment by Rycieos** [comment]
Thanks for letting us know.

I swear that this version was working correctly before I left for vacation, but it seems like it reverted somehow. I have forced a build, which seems to have fixed it.

I'll try to keep an eye on it to see if it breaks again.

**Comment by rodo-nunez** [comment]
Great. Thanks! =D
