### ISSUE TITLE
Error: _lp_ruby_env:11: bad pattern:  (set*

### ISSUE THREAD

**Issue by mithaler** [nojhan/liquidprompt#667]
Got an error after updating to master:
```
_lp_ruby_env:11: bad pattern:  (set*
```
My `.liquidpromptrc` file is empty.

Shell: ZSH 5.7.1

Operating system: Darwin COMP-C02CF0S7LVDN 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,2 Darwin

Liquidprompt version: 9f878488b4747795f4440deee9069a293dd68163 (This is the first bad commit, which I located with  `git bisect`.)

### Steps to Reproduce

1. Checkout 9f878488b4747795f4440deee9069a293dd68163.
2. Use `rbenv`, not `rvm`.
3. Run shell, with liquidprompt enabled. (I'm enabling it with antibody, for what that's worth.)

### Expected Behavior

The prompt should start working.

### Current Behavior

The prompt does not appear, and I get the error above.

### Possible Solution

I ran `git bisect` to locate the first commit with the issue. I believe the issue is in this block:
https://github.com/nojhan/liquidprompt/blob/145f146e9cb4fb3c30a22e6c35529120f4650a28/liquidprompt#L1163-L1167
but I'm not enough of a ZSH expert to tell you what it is exactly.

**Comment by Rycieos** [comment]
Yup, can reproduce this on Zsh. Works fine on Bash (where I tested this patch originally). Should be easy to fix I think...

**Comment by Rycieos** [comment]
It was a simple fix. I also added a test case (which we should have done when adding the feature) to prevent a regression. Thanks for the report!

**Comment by mithaler** [comment]
Thanks for the quick fix!
