### ISSUE TITLE
Teperature only goes up

### ISSUE THREAD

**Issue by cmm** [nojhan/liquidprompt#686]
Liquidprompt version: 
master

### Steps to Reproduce

1. Set `LP_TEMP_THRESHOLD` to something reachable
2. Reach the threshold
3. Observe the red and bold temperature appear in your prompt
4. Let the computer cool down
5. Observe the highest-measured temperature lingering in new prompts of the same shell

### Expected Behavior

Temperature should update in every prompt (the sample is taken anyway).

**Comment by Rycieos** [comment]
Easy reproduction. I seem to have done a stupid in commit 4c81ef4026c3105a260ff2b7e275bc8e50921c3b.
