### ISSUE TITLE
LP_DISABLED_VCS_PATH is deprecated is reported when copying the liquidpromptrc-dist

### ISSUE THREAD

**Issue by gdevenyi** [nojhan/liquidprompt#693]
The default config file only contains LP_DISABLED_VCS_PATHS however this warning is printed.

**Comment by Rycieos** [comment]
What Liquidprompt version, shell version, and OS version are you using? Please answer all the questions in the [Bug report template](https://github.com/nojhan/liquidprompt/blob/master/.github/ISSUE_TEMPLATE/bug.md).

**Comment by gdevenyi** [comment]
Shell: 4.4.20(1)-release

Operating system:
```
Distributor ID: Ubuntu
Description:    KDE neon User Edition 5.18
Release:        18.04
Codename:       bionic
```


Liquidprompt version:  cfad0e3f94c579c882e9a4c9fadb80d29b16913f

### Steps to Reproduce

1. Copy ~/liquidprompt/liquidpromptrc-dist to ~/.liquidpromptrc
2. source ~/liquidprompt/liquidprompt

### Expected Behavior
No warning

### Current Behavior

liquidprompt: LP_DISABLED_VCS_PATH is deprecated. Update your config to use LP_DISABLED_VCS_PATHS array.
### Possible Solution

**Comment by Rycieos** [comment]
I cannot reproduce. Can you try this without your shell config files?
```bash
env --unset=PS1 bash --norc --noprofile --login
source ~/liquidprompt/liquidprompt
```

I would expect the LP_DISABLED_VCS_PATH message to disappear.

If it does, you probably have `LP_DISABLED_VCS_PATH` set in your `.bashrc` or `.profile` or similar.

**Comment by gdevenyi** [comment]
> I would expect the LP_DISABLED_VCS_PATH message to disappear.

It still happens:
```
gdevenyi@machine:~$ env --unset=PS1 bash --norc --noprofile --login
bash-4.4$ source ~/liquidprompt/liquidprompt
liquidprompt: LP_DISABLED_VCS_PATH is deprecated. Update your config to use LP_DISABLED_VCS_PATHS array.
16:55:56 [gdevenyi@machine:~] $ 
```

I've found what's messing with this, I completely revamped all my environment recently, and I haven't logged out, it looks like something dbus-related is being helpful, from xession-errors:
```
dbus-update-activation-environment: setting LP_DISABLED_VCS_PATH=<REDACTED>
```

Not a bug, looks like window environment's fault.
