### ISSUE TITLE
Node Env Version Default

### ISSUE THREAD

**Issue by acatejr** [nojhan/liquidprompt#707]
### Description
The new feature that shows the node env (nvm) version is enabled by default.  Although a good enhancement, I spend most of my time in python and do not have a primary concern that the node version is displayed by default.

### How will this be useful?

Disabling the node version as default on, for me, would reduce visual noise on the command line.

### Example prompt

[userid:~/workspace/github.com/myid/projectname] branch:

NOT:
[userid:~/workspace/github.com/myid/projectname][node version number] branch:

**Comment by Rycieos** [comment]
I had enabled it by default as it has no performance detriment and it would only show up if a user had Node.js stuff specifically installed. And it is quite simple to disable.

But I can see the argument, and generally new stuff is disabled by default if it is not something everyone would want to use. I will probably make this change before 2.1 is released unless I get other feedback.

**Comment by acatejr** [comment]
Thank you.  I did find how to disable in liquidpromptrc.  So, it may not be worth your time to make the change.
