### ISSUE TITLE
Display virtualev `prompt` value 

### ISSUE THREAD

**Issue by frague59** [nojhan/liquidprompt#708]
When creating a virtualenv using venv in python, it's possible to set a `prompt` parameter, stored in the `./venv/pyvenv.cfg` file.

May be liquidprompt could display it instead of the \<venv directory\> name ? 

### Description

```shell
$ python3 -m venv --prompt yolo ./venv
$ . venv/bin/activate
[yolo] $
```

### How will this be useful?

I use the `venv` name for all my projects. This directory in inside the project tree. 

It should be useful when you work with *local* `venv` directories, then move around to another python project directory, to see you are still in the *previous* `venv`, not in the local one.
  
### Example prompt
^^

**Comment by Rycieos** [comment]
Makes sense to me. There is a catch though; while the `--prompt` option seems to have been added in version 3.6 ([docs](https://docs.python.org/3.10/library/venv.html)), the storing of it in the `pyvenv.cfg` seems to have been added in 3.8 (not documented). Before that, it was injected directly into the `bin/activate` file upon creation, and was stored no where else.

So we should be able to do something like this:

```bash
virtualenv_config="${VIRTUAL_ENV}/pyvenv.cfg"
if [[ -r "$virtualenv_config" ]]; then
  local line ret
  while IFS='' read -r line ; do
    if [[ $line == "prompt = " ]]; then
      line="${line#"prompt = '"}"
      line="${line#"'"}"
      __lp_escape "$line"
      lp_python_env="$ret"
      break
    fi
  done <"$virtualenv_config"
else
  # Usual display of venv directory name.
fi
```

But obviously it would only work on Python 3.8+. Still worth it?

**Comment by frague59** [comment]
Nice ! 

I think it would be useful, even if it is supported by python 3.8+ !

*modern* linux are 3.9+ now...
