### ISSUE TITLE
bash: __lp_before_command "$_": command not found

### ISSUE THREAD

**Issue by franzbischoff** [nojhan/liquidprompt#714]
Shell: 5.0.17(1)-release

Operating system: Linux 1e1ab5c3efaf 5.10.74.3-microsoft-standard-WSL2+ #3 SMP Wed Dec 1 01:17:29 WET 2021 x86_64 x86_64 x86_64 GNU/Linux
Liquidprompt version: v2.1.1

When using VSCode shell integration I receive this message `bash: __lp_before_command "$_": command not found` after every <ENTER>.
If I manually source the code after the shell is open, the error disappears.

Strangely, I have another computer with the same configuration that suddenly resolved this bug. 
I could not find any difference on .bashrc between these computers.

Is this any known bug?

Thanks.

**Comment by Rycieos** [comment]
This is a weird one. This is not a know bug, it looks like possibly a problem with your shell configuration:

> If I manually source the code after the shell is open, the error disappears.

My guess is that your environment is opening a subshell inside of your main shell, and the trap is being passed to the subshell, but the functions are not.

Try this inside of your bugged shell, if it is working correctly you should see the same return strings as I do:
```bash
$ trap -p
trap -- '__lp_before_command "$_"' DEBUG
$ declare -f __lp_before_command
__lp_before_command ()
{
...
```

If not, then Liquidprompt isn't being loaded in that shell. Confirm you have installed Liquidprompt correctly in your `.bashrc`. If it is installed, then VSCode probably is not loading that file correctly for some reason.

**Comment by franzbischoff** [comment]
![](https://i.imgur.com/Th3hfle.png)

**Comment by Rycieos** [comment]
Ah, there is the hint we need: `__vsc_preexec`. Must be a bug in their implementation.

Long story short, you aren't the first to find this. This was reported already as https://github.com/microsoft/vscode/issues/150423, albeit for the Starship prompt. They merged a fix already, but it hasn't been released yet. You will either need to wait, run the beta/insiders build, or disable the VSCode shell integration.

Their fix is super hacky though. Someone else proposed a better solution in https://github.com/microsoft/vscode/issues/150241.

Anyway, this is (was?) an external bug.

**Comment by franzbischoff** [comment]
Sorry to bother you with an external bug :-)
And Thanks for the LP!
