### ISSUE TITLE
Support for mosh connections

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#720]
Display an additional hint when a remote connection is set up using mosh over ssh.

### Description

Mosh is a remote terminal application that supports intermittent connectivity, allows roaming, and provides speculative local echo and line editing of user keystrokes. It actually uses SSH to set up the connection, providing additional features.
Supposedly, it can be detected: https://unix.stackexchange.com/questions/395491/detect-whether-the-current-terminal-is-through-mosh-or-not

The default theme already reserves potentially all colors for LP_ENABLE_SSH_COLORS (except for reverse red, which rightfully denotes telnet connections), so a specific color is not an option.
Additionally, mosh connection does provide the very same service than SSH, and thus may benefit from having different hosts being colored with different colors.

This leaves a few options when the connection is *mosh-over-ssh*: 

- Adding a mark to the hostname. The `@` being quite visually heavy, the best position would be *after* the hostname, before the period which is visually lighter. For instance: `[nojhan@hostname*:/path/here]`.
- Adding surrounding marks around the hostname, suggesting that the connection is somehow *managed* (by mosh, actually), e.g. `[nojhan@(hostname):/path/here]`
- Underlining the hostname, for the same reasons (any terminals should have good support for this style).
- Using the same colors, but in reverse mode (hence the hostname color being set on the background instead of the foreground as is the case with default ssh).

I personally think that underlining the hostname is the best option.

### How will this be useful?

Mosh behaving quite differently from a raw ssh connexion (most notably regarding latency management), it is nice to have a direct, visual, hint, as is Liquidprompt's motto.

**Comment by Rycieos** [comment]
This is a good suggestion. But it isn't so simple.

First, Liquidprompt already detects Mosh as SSH. Through the quirks of how a Mosh tunnel is set up, the SSH environment variables are still exposed in the Mosh shell, so Liquidprompt treats it like SSH. Maybe not entirely correct, but at least workable.

Second, your suggestion of underlining by default I take issue with. Most terminals use underlining for showing hyperlinks, which would be confusing if we made the hostname a link as part of #659.

Your specific request is to detect Mosh separately from SSH. This is hard. Mosh does not expose _any_ environment variables to allow for such detection (would be a good feature request for Mosh). Your linked post does have a workable solution, but `pstree` is a Linux only tool, not to mention is a forking call (although it would only be run once on shell startup).

Without a cross-platform (and ideally non-forking) way to detect Mosh, I do not see how this is possible (without a ton of custom code for each OS of parsing and walking through `ps` output or similar). If such a method is found, I will reconsider.

**Comment by nojhan** [comment]
Thanks for the analysis!
