### ISSUE TITLE
Generic environment variables tags

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#722]
Display a set of tags showing whether some environment variables are set or not.

### Description

Configuration would be an associative array of environment variable name => character.
By default, if the environment variable is set, the character is displayed.
Optionally, characters are always displayed, but with different colors if the variable is set or not.

**Comment by Rycieos** [comment]
Interesting idea. Could cut down on tool support requests, assuming the tools expose things as environment variables.

One catch is that Associative arrays were added to Bash in 4.0. As of right now, all Liquidprompt features are supported Bash 3.2+ and Zsh 5.0+. Thoughts on having some features that have a stricter set of requirements?

**Comment by nojhan** [comment]
Technically, an associative array is just an array of pair with fancy access. So we can configure this with an array of strings figuring a pair:
```bash
LP_ENV_TAGS=(
    "HTTP_PROXY ↥" # We may refactor proxy as just an entry here.
    "VERBOSE ⋁"   # May be multiple characters.
    "EDITOR %"     # '%' can be a placeholder for rendering the actual content of the variable.
    "DESKTOP_SESSION ∢"
)
LP_ENV_MARK_OPEN="{"
LP_ENV_SEP=" "
LP_ENV_MARK_CLOSE="}"
```
Would be rendered as: "{↥ ⋁ vi ∢}"

**Comment by nojhan** [comment]
FTR, I did not refactored the proxy in the generic code, as I felt it may considered as important by the user, and thus displayed apart from the section built by the generic code.

**Comment by Rycieos** [comment]
I agree, we should leave it, but add a section to the proxy config docs explaining how you can add a line to the env vars config to do the same thing.

**Comment by nojhan** [comment]
I realized it is not really possible to implement the proxy management with the env var section, because the proxy feature does in fact manage all the possible env var (lower/upper case, SSL, "all"). However, the env var section can only manage one variable at a time.

**Comment by Rycieos** [comment]
Ah, that is a fair point. Good to note that _usually_ they are lowercase (https://unix.stackexchange.com/a/212972/421569), but not always, and there are multiple that we want to check. So yes, probably best to not deprecate the proxy feature.

That will be an unusual case, since usually environment vars are either defined by POSIX, or defined by a specific program/project, and will not have different forms.

**Comment by nojhan** [comment]
Done in #754
