### ISSUE TITLE
Disk usage

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#730]
Display disk usage, if near to full.

### Description

Display the remaining free space on selected file systems if it goes below a threshold, just like other kind of sensors.
Probably should pay special (default?) attention to file systems hosting `/`, `/home` and `/boot`.

### How will this be useful?

Full disk are a rare source of problem, but it may be quite difficult to spot when it happens (as the system does not fail, but behave quite erratically).
I witnessed users tempted to reboot in such case, which render the debugging quite difficult after, albeit it would have been easy to fix right away while connected.
This would raise attention to the problem before it become difficult to solve.

**Comment by Rycieos** [comment]
I would not find this useful, but I'm sure some people would.

Biggest issue is gathering this data. I'm sure Linux probably has a sysfs interface, which would make this fast, but on other OSes we would need to do some hacky `df` parsing.

**Comment by nojhan** [comment]
Using `df` would have the advantage of being quite portable.

What about just checking the filesystem mounted for the current directory?

Zsh can do it with a one-liner:
```zsh
echo ${${=${(f)"$(df -P . 2>/dev/null)"}[2]}[5]%%%}
```

But for Bash I only came up with this:
```bash
FS=$'\n' read -d "" -r -a arr <<< "$(df -P . 2>/dev/null)"
IFS=" " read -r fs bc ut ds capa mo <<< "${arr[1]}" ; echo ${capa%%%}
```

**Comment by Rycieos** [comment]
> What about just checking the filesystem mounted for the current directory?

I like that idea a lot. I didn't know that `df` allows for a path argument.

> ```shell
> FS=$'\n' read -d "" -r -a arr <<< "$(df -P . 2>/dev/null)"
> IFS=" " read -r fs bc ut ds capa mo <<< "${arr[1]}" ; echo ${capa%%%}
> ```

That works, but I don't love needing two `read` calls, though it is only one external binary call.

**Comment by nojhan** [comment]
What about this:
```bash
read -d'' -r _ _ _ _ _ _ _ _ _ _ _ fs _ _ dispo perc mnt <<<$(df -P . 2>/dev/null)
```

**Comment by Rycieos** [comment]
That doesn't seem to work:
```bash
$ IFS=" " read -d'' -r _ _ _ _ _ _ _ _ _ _ _ _ _ used avail perc mnt <<<$(df -P . 2>/dev/null)
$ echo "$perc"

```
I think read doesn't work very well with multiple lines input...

**Comment by nojhan** [comment]
It's in fact a locale problem, currently solved with:
```bash
    LANG="en-US" read -d'' -r _ _ _ _ _ _ _ lp_disk_available _ lp_disk_mnt <<<$(df -P . 2>/dev/null)
```
(but please double check with your locale, just in case).

**Comment by Rycieos** [comment]
`LANG=C` is more portable. But either LANG did not work for me, I got `/dev/mapper/cl_host` and empty string as results. I tried padding fields out, and was only able to get empty strings.

**Comment by nojhan** [comment]
It's surprising that `-P` would give human-readable sizes, do you have any alias adding `-h`?

**Comment by Rycieos** [comment]
Ah yes, I do, will need to use `\` to prevent aliasas:

```bash
$ LANG=C \df -P .
Filesystem                 1024-blocks     Used Available Capacity Mounted on
/dev/mapper/cl_host-root     121354348 89580400  31773948      74% /
```

**Comment by nojhan** [comment]
Apparently the problem is that the empty string after `-d` should be spaced-separated, so that this would work on both my systems (MacOS and Ubuntu):
```bash
read -d ''  -r _ _ _ _ _ _ _ _ _ _ lp_disk_available _ lp_disk_mnt <<<$(LANG=C \df -k -P . 2 >/dev/null) ; echo "$lp_disk_available $lp_disk_mnt
```

**Comment by Rycieos** [comment]
That does appear to work correctly for me on Rocky Linux. Not on Cygwin though:
```bash
$ read -d ''  -r _ _ _ _ _ _ _ _ _ _ lp_disk_available _ lp_disk_mnt <<<$(LANG=C \df -k -P . 2>/dev/null) ; echo "$lp_disk_available $lp_disk_mnt"
450860060 23% /

$ LANG=C \df -P .
Filesystem                1024-blocks      Used  Available Capacity Mounted on
C:/Program Files/cygwin64  1999659004 450860152 1548798852      23% /
```
Not quite sure what went wrong there...

Also, you should set `IFS` before the `read` to be safe as well.

**Comment by nojhan** [comment]
The space in "Program Files" is surely the source of a split shift. We can probably bypass that with substring replacement of this specific path.

**Comment by Rycieos** [comment]
Ah, oof, yeah, that's difficult.

**Comment by nojhan** [comment]
What about:
```bash
local df=$(LANG=C \df -k -P . 2>/dev/null)
read -d ''  -r _ _ _ _ _ _ _ _ _ _ lp_disk_available _ lp_disk_mnt <<<"${df/Program Files/Program_Files}"
```

**Comment by nojhan** [comment]
You may try `feat/disk`, which has a first working version (without the doc so far).

**Comment by Rycieos** [comment]
> `${df/Program Files/Program_Files}`

I'm not a fan of that solution, as it only fixes this specific case. And it's not even a case that is likely to happen with Cygwin, as I installed it in a non-typical location.

I don't see a good solution though, parsing cli tools' output is never safe...

**Comment by nojhan** [comment]
True. But parsing systems files would be even more difficult...

**Comment by nojhan** [comment]
What about using only string parameters expansions?
```sh
    local nomount=${df% *} # Remove last element.
    local nocapa=${nomount% *} # Again.
    # remove trailing whitespace characters
    local nospace="${nocapa%"${nocapa##*[![:space:]]}"}"
    # Remove everything but last element.
    lp_disk_available="${nospace##* }"
```

**Comment by Rycieos** [comment]
That's a better solution, but it could have the same issue, since the last element is the mounted path, which could also include spaces.

Makes me wonder if we could do some spacing tricks to try to remove the path from the beginning:
```bash
df=$(LANG=C \df -k -P . 2>/dev/null)
short="${df#*1024-blocks}"
second="${df#*$'\n'}"
read -r _ lp_disk_available _ _ lp_disk_mnt <<<"${second:${#df}-${#short}-11}"
echo "$lp_disk_available $lp_disk_mnt"
```
That works for me.

**Comment by nojhan** [comment]
Clever! But you captured the used space, not the available one (which is the field after). Anyway, it seems to work, I'll make a PR when completed.

**Comment by nojhan** [comment]
Another part I don't like is the use of a fork to summon `bc` in `__lp_bytes_to_human`.

**Comment by Rycieos** [comment]
> Another part I don't like is the use of a fork to summon `bc` in `__lp_bytes_to_human`.

I don't see that function anywhere, did you add it to some PR?

**Comment by nojhan** [comment]
It was probably still on my local `feat/disk` branch. I pushed the current state.

**Comment by nojhan** [comment]
I drafted on PR #771, probaply easier to discuss with the code at hand.

**Comment by nojhan** [comment]
Done in #771
