### ISSUE TITLE
Automatic prompt_tag set to most frequent command

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#732]
Automatically set the prompt_tag to the most used command in the last *n* entry in history.

### Description

The prompt_tag command adds any user-defined keyword to the prompt for the current session, usually at the beginning (at least for the default theme).

This feature would allow the prompt_tag to be automatically defined from the most used command among the most recently used.

For instance, if `LP_ENABLE_TAG_FREQUENT=1`, run something equivalent to `history | tail -n 50 | cut -d' ' -f5 | uniq -c |sort -rn | head -n 1 | tr -s ' ' | cut -d " " -f 3` to get the most frequent command in the last 50 entries, and then use this as a prompt_tag.

I would strongly suggest to disable it by default.

### How will this be useful?

I tend to use one terminal for one task. For instance, I have a code editor in one, code build in another, and git in the last one. This is handy because the local history is consistent and easily accessible.

When switching from one to the other, I sometime get lost as to which is what (not for too long, thanks to LP, but still).
Recently, I started use the prompt_tag to solve this problem. But I still have to remind myself to actively do it. An automated option would be easier.

With such a feature, I would have an immediate visual clue on what terminal is for what task, without even thinking about it.

**Comment by Rycieos** [comment]
It's a good idea. Doesn't work on Zsh (probably just needs a small tweak), and needs `HISTTIMEFORMAT="" history` to work everywhere on Bash.

Only problem is speed. Calling 7 binaries in a pipeline is slow, even with the low amount of data. Maybe it can be done 100% in shell, but the only way I can think to do it would be with associative arrays (eg dictionaries), which aren't supported on Bash 3.2.

Probably it could be done in a single `awk` call, which would be much faster.

Another question is does it need to overwrite `prompt_tag`, or should it be its own data source?

**Comment by nojhan** [comment]
I would have let it overwrite the prompt_tag, for the sake of simplicity, but a user might be using it for her own commands, so maybe a specific variable may be a good idea. Plus, in DotMatrix, `LP_PS1_PREFIX` is not display as a prefix to the whole prompt, but the beginning of the middle line… so the name is now misleading. So maybe `prompt_tag` should fill up `LP_PROMPT_TAG` and themes put it where they want.

**Comment by nojhan** [comment]
Since #739 was closed for having a bad UX/cost ratio, maybe this should also be closed?

**Comment by Rycieos** [comment]
I agree. I'm willing to reconsider if anyone comes up with a faster method.
