### ISSUE TITLE
History sections

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#739]
Display latest commands in a list.

### Description

A function would display the `n` latest command in `history`, and display them as a list.

Needed features:
- optional shortening of long commands,
- optional removing of parts after command limits (;, &&, ||, etc.),
- optional color gradient for each item in the list (like fading from light to dark color).

E.g. with n=3: `[ls][git status][git filter-repo --analyze && tail -n+3./[…]`

### How will this be useful?

Probably not a good idea to add this to the default theme, but themes with several lines may use spare space to display this.

**Comment by Rycieos** [comment]
I think you will need to convince me of the usefulness here.

If I want to know what commands I just ran, I look up in my terminal and can see what I just typed. Why do I need to see it a second time?

On the other hand, I am not sure about adding data sources that aren't added to the default theme. The goal for themes was to add **all** data sources, and let users disable specific ones with config options. This would be an interesting change of that goal.

**Comment by nojhan** [comment]
Probably not immensely useful, but still would allow to have a very quick glance at history, instead of having lo look up, scroll up (if you cleared) or use the arrow keys. Every second helps, IMHO.

For example, I would find it useful, because I run build commands after coding (in another window), so that I very often don't remember what *exact* build command I've called in previous commands (and they are displayed far up scroll, given the large output).

Also, I've already been bitten several times by muscle-memory calling what I believed would have been the last build command, but was really something else (like starting the debugger, for instance). An immediate visual clue would help not making the mistake, and spare a few seconds.

Albeit, that may be rendered useless if it is visually difficult to parse (like with very long commands). But that may be managed, I guess.

As for the themes, I don't see any problem of some of them being highly specialized, to the point they would get rid of large data sets. For instance, I could very well imagine switching on a themes that would be more appropriate for the task at hand, hence lightening some visual clutter. LP already does that —if you think about it— with the declutching of VCS under the root user.

**Comment by Rycieos** [comment]
> LP already does that —if you think about it— with the declutching of VCS under the root user.

I understood that feature as a security measure. But now that you mention it, maybe it is a decluttering feature like you say.

I think this boils down to a complicated question: **should Liquid Prompt contain data sources that are optional for themes to include?**

My first reaction is to say "no". All our features and data sources are configurable, so you can turn them on and off when you want them. So why should every theme not implement every data source?

But, clearly not all themes will have room (or the organization) or the need to implement every data source, like the Powerline theme for example. So then the answer is "yes, but the best themes as well as the default theme should have all of them".

But you are requesting here a data source that would not be in the default theme. And would be very optional for other themes. Is this something we should do?

I suggested in a chat with @nojhan that we could devise a plugin system, but he rightly pointed out that it would probably be more complicated and difficult than it would be worth. But as the maintainer of Liquid Prompt, I do not want to be maintaining a bunch of data sources that will 1) not be used very much and 2) are highly user specific and would need a ton of customization options.

Another idea I proposed earlier is custom data source support: https://github.com/nojhan/liquidprompt/issues/540#issuecomment-1127795610. Similar to a plugin system, but not suggesting that users actually do plugins?

Clearly this needs more thought. Would love to hear ideas on this.

**Comment by nojhan** [comment]
That's indeed a good question. I can very well implement that just in my theme.

I like the idea of a custom data source section, which seems simple enough.
However, how hard is it now to make the very same thing just using the theme engine?
It's probably already be very simple: just two proxy functions and one holding the additional code and inserting it in the template. Probably just a matter of having an example in the documentation to allow power users to play with the idea, without the need of an additional "pluggable stuff" system.

**Comment by Rycieos** [comment]
> However, how hard is it now to make the very same thing just using the theme engine?

You are correct, it would be very simple.

However, for those that don't want to make a custom theme, having a way to insert custom data sources could be useful. We have already had a few requests for something similar (#622, #682). But it is already possible to do this with the default theme using template files, so maybe that is enough.

**Comment by nojhan** [comment]
I implemented something in [DotMatrix](https://github.com/nojhan/lp-dotmatrix) and played a bit with it. It was too visually heavy to display several of the last commands, so I ended displaying just the last one, along with the most frequently used in a given backlog (which is very close to #732, but it's probably more logical to have it in a "history" section anyway). Seems to work for now.

**Comment by nojhan** [comment]
After some month of tests, I think it is not completely worth the (very) slow implementation. It is somewhat useful, but not very much so.

**Comment by Rycieos** [comment]
Thanks for the feedback.

That is what I was afraid of. I think this is a good use case for extensions/plugins, if we ever figured out how to make such a system work.

Unless someone can suggest a more performant and space efficient implementation, I am closing this as "rejected as not a good fit for the default theme".
