### ISSUE TITLE
_lp_temperature:4: permission denied:

### ISSUE THREAD

**Issue by uhlhosting** [nojhan/liquidprompt#747]
Shell: zsh: command not found: 5.8.1

Operating system: Darwin Revengers.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  2 22:39:24 PDT 2022; root:xnu-8792.41.7~13/RELEASE_X86_64 x86_64

Liquid Prompt version:

### Steps to Reproduce

1. deployed via .zinit
2. 
3.

### Expected Behavior

_lp_temperature:4: permission denied:
### Current Behavior

after each cli used: _lp_temperature:4: permission denied:

**Comment by Rycieos** [comment]
You are missing what Liquid Prompt version you are running.

This is a weird issue, shouldn't be possible to get into. Can you post the output of these commands?
```bash
echo "'$_LP_TEMP_FUNCTION'"
set -x ; _lp_temperature ; set +x
```

**Comment by uhlhosting** [comment]
I solved it, seems that the config locations in zinit changed, and had to make some changes, now it all works well. Thanks.

**Comment by Rycieos** [comment]
Glad you solved it. Care to share for others that might have the same issue?
