### ISSUE TITLE
LP_VERSION

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#749]
Add a global variable holding current Liquid Prompt's version.

### Description

`LP_VERSION` should hold the current version.
At least as a string ("2.2") or even better, as an array (`LP_VERSION=(2 2 0)`).

### How will this be useful?

External themes way need that information, at least to warn the user if they were made for a lower version, and thus may not display all data.

**Comment by Rycieos** [comment]
This is a good idea. I think it makes more sense to expose a utility function to enable themes to check instead:

```bash
# Return true if the current Liquid Prompt version is greater than or equal to the specified version.
_lp_version() {  # major, minor, [patch]
```

Then a theme could use it to check, and either print an error message or a warning message.

On top of that, we could change the API of a theme's `_activate()` function where if it returns non-zero, the theme failed to activate, and we print a message saying so, and re-activate the previous theme.

Thoughts?

**Comment by nojhan** [comment]
I like the idea. But comparing semantic versioning strings is not trivial. Unless we restrict LP versions to three integers, forgetting about the string parts (beta, alpha, rc, etc.).

**Comment by Rycieos** [comment]
Good points. My gut reaction is to say ignore any detail finer than patch, as they are unreleased versions. But it wouldn't be too difficult to support, since we control exactly what string parts we can use (I have only ever used "alpha", "beta", and "rc"). It would make it easy if we require calls to the function to split apart the version sections as separate arguments, so we don't need to parse:

```bash
_LP_VERSION=(2 2 0 alpha 1)

# Return true if the current Liquid Prompt version is greater than or equal to the specified version.
# [OPTIONAL?] Return 1 if minor or less version difference, 2 if major difference.
_lp_version() {  # major, minor, [patch], [string], [number]
    local major="$1" minor="$2" patch="${3-}" string="${4-}" number="${5-}"
    if (( major > _LP_VERSION[0] )); then
        return 2
	elif (( major == _LP_VERSION[0] )); then
            if (( minor > _LP_VERSION[1] )); then
		return 1
            elif (( minor == _LP_VERSION[1] )) && [[ -n $patch ]]; then
                if (( patch > _LP_VERSION[2] )); then
                    return 1
                elif (( patch == _LP_VERSION[2] )) && [[ -n $string && -n $number ]]; then
                    if [[ $string == "${_LP_VERSION[3]}" ]]; then
                        if (( number > _LP_VERSION[4] )); then
                            return 1
                        fi
                    elif [[ ${_LP_VERSION[3]} == "alpha" || \
                        ( ${_LP_VERSION[3]} == "beta" && \
                        $string == "rc" ) ]]; then
                    return 1
                fi
            fi
        fi
    fi
	
    return 0
}
```
It's a bit verbose, but does cover all cases.

**Comment by nojhan** [comment]
I would set `lp_version="${major}.${minor}.${patch}-${string}-${number}"`, so that we may print the version error, or so that themes may display it ([Solid](https://github.com/nojhan/lp-solid) would display it, for instance).

**Comment by nojhan** [comment]
Merged.
