### ISSUE TITLE
Features overview link in README.md doesn't work

### ISSUE THREAD

**Issue by gortibaldik** [nojhan/liquidprompt#751]
Link in README.md leads to https://liquidprompt.readthedocs.io/en/stable/overview.html which doesn't exist.

**Comment by Rycieos** [comment]
Thanks. Yeah, look like that got merged in, while that link only exists on the "latest" version of the docs. @nojhan, what do you think we should do?

1. Remove the link until 2.2 release.
2. Point the link to the `latest` version until release.
3. Leave as is, and it will start working upon release.

**Comment by nojhan** [comment]
To me, it would make more sense if the Github's landing page would link toward the latest version, because it's more or less made for developers. But is there an up-to-date edge version of the doc on ReadTheDoc?

**Comment by Rycieos** [comment]
Yes there is, https://liquidprompt.readthedocs.io/en/latest/ tracks the latest master branch commit.
