### ISSUE TITLE
Up-to-date presets examples

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#755]
I think that the `liquidpromptrc-dist` file is an important tool for feature discovery.
As of now, it does not contain all the new features and should be updated.

More generally, should we consider shipping a (small) subset of presets?
In the main repository, or should we have external presets, just as we have external themes?

**Comment by Rycieos** [comment]
When I developed the documentation for v1.12, I decided that keeping the dist file up-to-date was not only too much work, but could never include all of the important details that the documentation includes. Hence the message I put at the top of the file.

Personally, I would like to see the file go away. I think it serves as a distraction, hiding the far better documentation. But I figured that an example is always helpful.

As for presets, other prompt projects have them, and I think they could be a helpful edition. However, many prompts (like Starship for example) do a lot of the display configuration through their config, while Liquid Prompt now does that through themes. I am not sure how much help presets would be, as there are few visual config options other than colors and marks.

If users would find them helpful, I could see adding them to the main repo.

**Comment by nojhan** [comment]
That's very valid points indeed. However, as a user I still find it handy to just browse a config file and edit the defaults, instead of having to go back and forth on a web page. But it's very true that the maintenance cost is probably too big.

How difficult would it be to automatically convert the `config.rst` to a config file that way be sourced?

Given that presets may be split in several files, shouldn't we also provide some alternative "sub-presets" in `presets/` (`contrib/presets/` or `themes/presets/`)? I am thinking of alternative color sets (for you guys with colorblindness) or sets of marks related to a given font, for instance.

**Comment by nojhan** [comment]
> Would you want the descriptions to also get copied into the file as comments? It would get very big very fast.

I think we can probably just take the first paragraph of the docstring.
And if it's still to big, only the `LP_ENABLE_*` variables.

> I think those are perfect examples of what presets would be good for. So yes, I think so. Probably they should go in `contrib/` since I doubt they will be kept current very often.

OK, let's do that. And also advertise them on the wiki, close to the themes.
