### ISSUE TITLE
"Environment Modules" support

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#763]
Support of [Environment Modules](https://modules.sourceforge.net/) in the dev env section.

### Description

Environment modules allow to load a shell configuration (generally for enabling some software).

A typical output of the `list` command is:

```
$ module list
Currently Loaded Modulefiles:
 1) Python/3.8.1   2) snakemake/7.16.1   3) gcc/9.2.0(default)   4) cmake/3.19.4 
```

Liquidprompt may display those modules the same way it already display information in the "dev env" section.

Version display may be configured out.

### How will this be useful?

Modules is a common tool on HPC clusters, and when working on such a remote server, it's a constant fight to remember which module is loaded.

### Example prompt

`[nojhan@maestro-submit:~/frictionlesser] <Python|snakemake|gcc|cmake> main(+17/-2)* ±`

`[nojhan@maestro-submit:~/frictionlesser] <Python:3.8.1|snakemake:7.16.1|gcc:9.2.0|cmake:3.19.4> main(+17/-2)* ±`

**Comment by nojhan** [comment]
Merged.

**Comment by chrisdane** [comment]
Thanks for implementing another feature to this great repo.

How can I deactivate this feature?
