### ISSUE TITLE
Too difficult to set up

### ISSUE THREAD

**Issue by kiteloopdesign** [nojhan/liquidprompt#765]
### Description

doc is very good at describing the low-level stuff for developers. However, for the final user, It took me some time to find how to do the simplest of things: loading a theme

From `liquidprompt-dist` file, the following info is given:

```
# If you want to use different themes and features,
# you can load the corresponding files here:
#source ~/.config/liquidprompt/nojhan.theme
#LP_PS1_FILE=~/.config/liquidprompt/nojhan.ps1
```
However these files do not exist on the liquidprompt installation folder...

This is also contradictory to what actually needs to be done. Basically this:

```
source themes/powerline/powerline.theme
lp_theme lp_theme powerline
```

Documentation in rdt is not clear on this, info on how to set the theme should be first line!

![image](https://user-images.githubusercontent.com/17339330/219899306-d270d829-d313-48ec-9ca8-7db6e1f1c8c2.png)

![image](https://user-images.githubusercontent.com/17339330/219899339-e3b00ccc-a5bd-4b62-9335-374967ab6867.png)

**Comment by kiteloopdesign** [comment]
Also this doesn't seem to work:
```
source liquid.theme 
lp_theme liquid
```
Thanks

**Comment by nojhan** [comment]
That's a good point! Thanks for having taken the time to report it, this is very useful to us.

The documentation of the next release (not online on RTD at the moment, but can be built from the source) is already a little better, and we will take special care to make the theme switch clearer.

**Comment by Rycieos** [comment]
> The documentation of the next release (not online on RTD at the moment, but can be built from the source) 

This isn't exactly correct, as the `master` branch is always built and can be seen here: https://liquidprompt.readthedocs.io/en/latest/. But the default version does track the latest release.

However, you are correct that we can improve this section. Thanks for the suggestion!

**Comment by nojhan** [comment]
On top of the PR #767, I also added a short installation instruction on [the related wiki page](https://github.com/nojhan/liquidprompt/wiki/Themes), hope that helps.

**Comment by nojhan** [comment]
Fixed.
