### ISSUE TITLE
time for root user is not reset on each commands. For regular user it works well

### ISSUE THREAD

**Issue by sputnick-dev** [nojhan/liquidprompt#774]
Shell: `GNU bash, version 5.1.16`

Operating system:
```
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa
```

Liquid Prompt version:
```
# dpkg -l liquidprompt
ii  liquidprompt   1.11-3ubuntu1 all          adaptative prompt for bash & zsh
```

### Steps to Reproduce

1. log as root: `sudo -s`

### Expected Behavior

I expect the time to be reset on any commands like for regular user

### Current Behavior

```
θ64° root@ultrabook:~ 17h21m4s # true
θ61° root@ultrabook:~ 17h23m4s # 
```

### Possible Solution

No idea, I need to reset with `exec bash`

**Comment by Rycieos** [comment]
If it works correctly after running `exec bash`, I'm a bit stumped.

That said, you are running version 1.11, which is almost 7 years old, and unsupported. The versions shipped in Ubuntu based distros have not been updated since then. There have been quite a few improvements to the runtime feature between v1.11 and v2.1. Please try updating to the latest stable release and reproduce the issue.

**Comment by sputnick-dev** [comment]
disabled this non needed feature:

    cp ~/liquidprompt/liquidpromptrc-dist ~/.config/liquidpromptrc
    
then

```
# Show runtime of the last command if over LP_RUNTIME_THRESHOLD
# Recommended value is 0
# Debian default is 1, only active in bash
LP_ENABLE_RUNTIME=0

# Minimal runtime to be displayed
# Recommended value is 2
LP_RUNTIME_THRESHOLD=0

```

**Comment by sputnick-dev** [comment]
With the latest git version, my user prompt get f*ùcked:

    \[\]⌂61%\[\]stable±\[\]   stardust@ultrabook:~/sources/liquidprompt   130 

Going back to the old stable one

**Comment by Rycieos** [comment]
Feel free to open an issue for that, assuming you weren't using a custom theme file that used private functions (if you were, see the [2.0 upgrade notes](https://liquidprompt.readthedocs.io/en/stable/upgrading/v2.0.html)). All versions are supposed to be backwards compatible to v1.11.
