### ISSUE TITLE
[documentation] Outdated info on oh-my-posh

### ISSUE THREAD

**Issue by ShrykeWindgrace** [nojhan/liquidprompt#777]
The page https://github.com/nojhan/liquidprompt/blob/master/docs/overview.rst says that `oh-my-posh` is limited to Zsh. That's a bit surprising since it was initially conceived as a powershell prompt engine; anyway, currently oh-my-posh supports quite a list of shells.

Judging by the contents of the comparison table on the same  page (section on shells), that's just a honest slip; I'll open PR shortly.

Cheers

**Comment by Rycieos** [comment]
Thanks for pointing this out. I'll assign this to @nojhan as he wrote that part of the docs.

I'll have to take another look at oh-my-posh, see how good it is.
